'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {CHURCH_LOGO,LEGACY_LOGO} from '../brand';
import {SB,KEY} from '../../lib/sb';

const onlyDigits=(v:string)=>v.replace(/\D/g,'');
const formatCpf=(v:string)=>onlyDigits(v).slice(0,11).replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2');
const formatPhone=(v:string)=>{const d=onlyDigits(v).replace(/^55(?=\d{10,11}$)/,'').slice(0,11);if(d.length<=2)return d;if(d.length<=6)return `(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=10)return `(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;return `(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`};
const defaults:any[]=[{field_key:'full_name',label:'Nome completo',field_type:'text',is_required:true,sort_order:10,width:'full'},{field_key:'birth_date',label:'Data de nascimento',field_type:'date',is_required:true,sort_order:20,width:'half'},{field_key:'cpf',label:'CPF',field_type:'cpf',is_required:true,sort_order:30,width:'half'},{field_key:'whatsapp',label:'WhatsApp',field_type:'tel',is_required:true,sort_order:40,width:'half'},{field_key:'email',label:'E-mail',field_type:'email',is_required:true,sort_order:50,width:'half'},{field_key:'housing_type',label:'Tipo de moradia',field_type:'select',is_required:true,sort_order:60,width:'full',options:[{value:'house',label:'Casa'},{value:'apartment',label:'Apartamento'},{value:'other',label:'Outro'}]},{field_key:'street',label:'Rua',field_type:'text',is_required:true,sort_order:70,width:'full'},{field_key:'neighborhood',label:'Bairro',field_type:'text',is_required:true,sort_order:80,width:'half'},{field_key:'city',label:'Cidade',field_type:'text',is_required:true,sort_order:90,width:'half'},{field_key:'has_solar',label:'Possui energia solar?',field_type:'select',is_required:true,sort_order:100,width:'full',options:[{value:'yes',label:'Sim'},{value:'no',label:'Não'}]},{field_key:'privacy',label:'Política de Privacidade',field_type:'checkbox',is_required:true,sort_order:110,width:'full'},{field_key:'marketing_consent',label:'Consentimento de marketing',field_type:'checkbox',is_required:false,sort_order:120,width:'full'}];
export default function Cadastro(){
 const [config,setConfig]=useState<any>(null),[values,setValues]=useState<any>({city:'Campos dos Goytacazes',housing_type:'house'}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const next=typeof window!=='undefined'?new URLSearchParams(location.search).get('next')||'/':'',orgSlug=typeof window!=='undefined'?new URLSearchParams(location.search).get('org')||'':'';
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('semeando_visitor')||'null');if(v?.id){location.replace(next.startsWith('/')?next:'/');return}}catch{};(async()=>{try{const r=await fetch(`${SB}/functions/v1/public-org-config${orgSlug?`?org=${encodeURIComponent(orgSlug)}`:''}`,{headers:{apikey:KEY}}),d=await r.json();if(r.ok){setConfig(d);const b=d.branding||{},root=document.documentElement;root.style.setProperty('--orange',b.primary_color||'#ff7417');root.style.setProperty('--bg',b.background_color||'#070709');root.style.setProperty('--card',b.surface_color||'#131317');root.style.setProperty('--text',b.text_color||'#f7f7f9');root.style.setProperty('--muted',b.muted_color||'#9b9ba6');root.style.setProperty('--brand-button-radius',`${b.button_radius||13}px`);root.style.setProperty('--brand-card-radius',`${b.card_radius||21}px`)}}catch{}})()},[]);
 const fields=(config?.fields?.length?config.fields:defaults).filter((f:any)=>f.is_enabled!==false).sort((a:any,b:any)=>a.sort_order-b.sort_order),branding=config?.branding||{},org=config?.organization;
 const groups=useMemo(()=>{const out:any[]=[];for(let i=0;i<fields.length;i++){const f=fields[i];if(f.width==='half'&&fields[i+1]?.width==='half'){out.push([f,fields[++i]])}else out.push([f])}return out},[config]);
 function set(k:string,v:any){setValues((x:any)=>({...x,[k]:v}))}
 function renderField(f:any){if(f.field_key==='privacy')return <label className="consent-box" key={f.field_key}><input type="checkbox" checked={!!values.privacy} onChange={e=>set('privacy',e.target.checked)}/><span>Li e aceito a <a href="/privacidade" target="_blank">Política de Privacidade</a> e autorizo o tratamento dos meus dados para acesso às galerias.</span></label>;
 if(f.field_key==='marketing_consent')return <label className="consent-box optional" key={f.field_key}><input type="checkbox" checked={!!values.marketing_consent} onChange={e=>set('marketing_consent',e.target.checked)}/><span>{f.help_text||'Quero receber comunicações e novidades desta organização.'} <em>Opcional.</em></span></label>;
 const common={required:!!f.is_required,value:values[f.field_key]??'',placeholder:f.placeholder||'',onChange:(e:any)=>set(f.field_key,e.target.value)} as any;
 let input:any;if(f.field_type==='select')input=<select {...common}><option value="">Selecione</option>{(f.options||[]).map((o:any)=><option value={o.value} key={o.value}>{o.label}</option>)}</select>;
 else if(f.field_type==='textarea')input=<textarea {...common}/>;
 else if(f.field_type==='checkbox')input=<input type="checkbox" checked={!!values[f.field_key]} onChange={e=>set(f.field_key,e.target.checked)}/>;
 else if(f.field_type==='date')input=<input type="date" {...common}/>;
 else if(f.field_type==='cpf')input=<input inputMode="numeric" {...common} value={values[f.field_key]??''} onChange={e=>set(f.field_key,formatCpf(e.target.value))}/>;
 else if(f.field_type==='tel')input=<input inputMode="tel" {...common} value={values[f.field_key]??''} onChange={e=>set(f.field_key,formatPhone(e.target.value))}/>;
 else input=<input type={f.field_type==='email'?'email':f.field_type==='number'?'number':'text'} {...common}/>;
 return <label key={f.field_key}>{f.label}{input}{f.help_text&&<small className="muted" style={{fontWeight:500}}>{f.help_text}</small>}</label>}
 async function submit(e:FormEvent){e.preventDefault();setError('');for(const f of fields){if(f.is_required&&f.field_key!=='privacy'){const v=values[f.field_key];if(v===undefined||v===null||v===''){setError(`Preencha o campo obrigatório: ${f.label}.`);return}}}if(!values.privacy){setError('Aceite a Política de Privacidade para continuar.');return}setBusy(true);try{const payload:any={organization_id:org?.id,privacy:!!values.privacy,marketing_consent:!!values.marketing_consent,custom_fields:{}};const known=new Set(['full_name','email','cpf','birth_date','housing_type','street','neighborhood','city','whatsapp','has_solar']);for(const [k,v] of Object.entries(values)){if(['privacy','marketing_consent'].includes(k))continue;if(known.has(k))payload[k]=k==='cpf'||k==='whatsapp'?onlyDigits(String(v)):k==='has_solar'?v==='yes':v;else payload.custom_fields[k]=v}const r=await fetch(`${SB}/functions/v1/visitor-register`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível concluir o cadastro.');localStorage.setItem('semeando_visitor',JSON.stringify({id:d.visitor.id,full_name:d.visitor.full_name,organization_id:org?.id,registered_at:new Date().toISOString(),marketing_consent:d.visitor.marketing_consent}));location.href=next.startsWith('/')?next:'/'}catch(err:any){setError(err.message||'Erro inesperado.')}finally{setBusy(false)}}
 const logo=branding.logo_url||CHURCH_LOGO,name=branding.platform_name||'Semeando Memórias',display=branding.organization_display_name||org?.name||'Igreja Semeando Amor';
 return <main className="register-page" style={{backgroundColor:branding.background_color||undefined,color:branding.text_color||undefined}}><div className="register-shell" style={{borderRadius:branding.card_radius||undefined}}><section className="register-brand" style={branding.cover_url?{backgroundImage:`linear-gradient(160deg,#000b,#0007),url(${branding.cover_url})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><a className="brand-lockup" href="/"><img src={logo} alt="Logo"/><div><strong>{name}</strong><span>{display}</span></div></a><div className="register-copy"><span className="hero-kicker">Acesso às galerias</span><h1>{branding.welcome_title||<>Antes de entrar,<br/><em>queremos conhecer você.</em></>}</h1><p>{branding.welcome_subtitle||`Seu cadastro libera o acesso às fotos e recursos disponibilizados por ${display}.`}</p><div className="register-benefits"><span>✓ Acesso às galerias autorizadas</span><span>✓ Busca facial quando disponível</span><span>✓ Cadastro feito uma única vez neste aparelho</span></div></div>{branding.show_developer_signature!==false&&<div className="register-developer"><span>Tecnologia e desenvolvimento</span><img src={LEGACY_LOGO} alt="Legacy Solar"/><strong>Legacy Solar</strong></div>}</section>
 <form className="register-card" onSubmit={submit} style={{borderRadius:branding.card_radius||undefined}}><div><span className="eyebrow">Cadastro</span><h2>{branding.registration_title||'Libere seu acesso'}</h2><p className="muted">{branding.registration_subtitle||'Preencha os dados abaixo.'}</p></div>{error&&<p className="notice">{error}</p>}{groups.map((g:any[],i:number)=>g.length===2?<div className="form-row" key={i}>{g.map(renderField)}</div>:renderField(g[0]))}<button className="btn register-submit" disabled={busy} style={{borderRadius:branding.button_radius||undefined}}>{busy?'Validando e cadastrando...':'Continuar para as fotos'}</button><p className="form-footnote">Seus dados não são públicos. Campos opcionais podem ser deixados em branco.</p></form></div></main>
}
