'use client';
import {FormEvent,useEffect,useState} from 'react';
import {CHURCH_LOGO,LEGACY_LOGO} from '../brand';
import {SB,KEY} from '../../lib/sb';
export default function Cadastro(){
 const [form,setForm]=useState({full_name:'',housing_type:'house',street:'',neighborhood:'',city:'Campos dos Goytacazes',whatsapp:'',privacy:false,marketing_consent:false});
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const next=typeof window!=='undefined'?new URLSearchParams(location.search).get('next')||'/':'';
 useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('semeando_visitor')||'null');if(v?.id){const n=next.startsWith('/')?next:'/';location.replace(n)}}catch{}},[]);
 async function submit(e:FormEvent){e.preventDefault();setError('');if(!form.privacy){setError('Aceite a Política de Privacidade para continuar.');return}setBusy(true);try{const r=await fetch(`${SB}/functions/v1/visitor-register`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível concluir o cadastro.');const v=d.visitor;localStorage.setItem('semeando_visitor',JSON.stringify({id:v.id,full_name:v.full_name,registered_at:new Date().toISOString(),marketing_consent:v.marketing_consent}));location.href=next.startsWith('/')?next:'/'}catch(err:any){setError(err.message||'Erro inesperado.')}finally{setBusy(false)}}
 return <main className="register-page"><div className="register-shell"><section className="register-brand"><a className="brand-lockup" href="/"><img src={CHURCH_LOGO} alt="Logo Igreja Semeando Amor"/><div><strong>Semeando Memórias</strong><span>Igreja Semeando Amor</span></div></a><div className="register-copy"><span className="hero-kicker">Acesso às galerias</span><h1>Antes de entrar,<br/><em>queremos conhecer você.</em></h1><p>Seu cadastro é gratuito e libera o acesso às fotos dos eventos da Igreja Semeando Amor.</p><div className="register-benefits"><span>✓ Acesso às galerias publicadas</span><span>✓ Busca facial por selfie</span><span>✓ Cadastro feito uma única vez neste aparelho</span></div></div><div className="register-developer"><span>Tecnologia e desenvolvimento</span><img src={LEGACY_LOGO} alt="Legacy Solar"/><strong>Legacy Solar</strong></div></section>
 <form className="register-card" onSubmit={submit}><div><span className="eyebrow">Cadastro de visitante</span><h2>Libere seu acesso</h2><p className="muted">Preencha os dados abaixo. Leva menos de 1 minuto.</p></div>{error&&<p className="notice">{error}</p>}
 <label>Nome completo<input autoComplete="name" required placeholder="Seu nome completo" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label>
 <label>Tipo de moradia<select required value={form.housing_type} onChange={e=>setForm({...form,housing_type:e.target.value})}><option value="house">Casa</option><option value="apartment">Apartamento</option><option value="other">Outro</option></select></label>
 <label>Rua<input autoComplete="street-address" required placeholder="Nome da rua" value={form.street} onChange={e=>setForm({...form,street:e.target.value})}/></label>
 <div className="form-row"><label>Bairro<input required value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})}/></label><label>Cidade<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label></div>
 <label>WhatsApp<input inputMode="tel" autoComplete="tel" required placeholder="(22) 99999-9999" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label>
 <label className="consent-box"><input type="checkbox" checked={form.privacy} onChange={e=>setForm({...form,privacy:e.target.checked})}/><span>Li e aceito a <a href="/privacidade" target="_blank">Política de Privacidade</a> e autorizo o tratamento dos meus dados para controle de acesso às galerias.</span></label>
 <label className="consent-box optional"><input type="checkbox" checked={form.marketing_consent} onChange={e=>setForm({...form,marketing_consent:e.target.checked})}/><span>Quero receber contato da <b>Legacy Solar</b> sobre economia de energia, energia solar e oportunidades relacionadas. <em>Opcional.</em></span></label>
 <button className="btn register-submit" disabled={busy}>{busy?'Cadastrando...':'Continuar para as fotos'}</button><p className="form-footnote">Seus dados não são públicos. O consentimento comercial é opcional e pode ser revogado.</p></form></div></main>
}
