'use client';
import {useEffect,useMemo,useState} from 'react';
import {KEY,SB,session} from '../../../lib/sb';
import s from './access.module.css';

export default function AccessCenter(){
 const [data,setData]=useState<any>(null),[status,setStatus]=useState<Record<string,any>>({}),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 async function token(){const ss=await session();if(!ss?.access_token){location.href='/admin/login';throw new Error('Sessão expirada.')}return ss.access_token}
 async function accessCall(organization_id:string,action='status'){const t=await token();const r=await fetch(`${SB}/functions/v1/developer-access-invite`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({organization_id,action})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao consultar acesso.');return d}
 async function load(){setLoading(true);try{const t=await token();const r=await fetch(`${SB}/functions/v1/developer-console`,{headers:{apikey:KEY,Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar clientes.');setData(d);const pairs=await Promise.all((d.organizations||[]).map(async(o:any)=>{try{return[o.id,await accessCall(o.id)]}catch{return[o.id,{error:true}]}}));setStatus(Object.fromEntries(pairs))}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const orgs=useMemo(()=>{const n=q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return (data?.organizations||[]).filter((o:any)=>!n||[o.name,o.email,o.slug,status[o.id]?.administrator?.email].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(n))},[data,q,status]);
 async function resend(id:string){setBusy(id);setMsg('');try{const d=await accessCall(id,'resend_invite');setMsg(`Link de acesso enviado para ${d.email}.`);const fresh=await accessCall(id);setStatus(x=>({...x,[id]:fresh}))}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 if(loading)return <main className={s.loading}>Carregando acessos...</main>;
 const pending=orgs.filter((o:any)=>status[o.id]?.administrator?.status==='pending').length;
 return <main className={s.page}><header><div><a href="/developer/clientes">← Clientes</a><span>GESTÃO DE ACESSOS</span><h1>Acessos dos clientes</h1><p>Acompanhe primeiro acesso, convites e recuperação de senha.</p></div><div className={s.kpi}><b>{pending}</b><small>convites pendentes</small></div></header>{msg&&<div className={s.notice}>{msg}</div>}<input className={s.search} value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar organização ou administrador..."/><section className={s.list}>{orgs.map((o:any)=>{const a=status[o.id]?.administrator;const active=a?.status==='active';return <article key={o.id}><div className={s.avatar}>{o.name?.charAt(0)?.toUpperCase()||'C'}</div><div className={s.main}><b>{o.name}</b><small>{a?.email||o.email||'Administrador não localizado'}</small><div><span className={active?s.ok:s.pending}>{active?'PRIMEIRO ACESSO CONCLUÍDO':'CONVITE PENDENTE'}</span><span>{active&&a?.first_access_at?`Ativado em ${new Date(a.first_access_at).toLocaleString('pt-BR')}`:a?.last_invite_at?`Último envio ${new Date(a.last_invite_at).toLocaleString('pt-BR')}`:'Aguardando ativação'}</span></div></div><div className={s.actions}><a href={`/developer/clientes/${o.id}`}>Ficha 360º</a>{a&&<button disabled={busy===o.id} onClick={()=>resend(o.id)}>{busy===o.id?'Enviando...':active?'Enviar recuperação':'Reenviar convite'}</button>}</div></article>})}{!orgs.length&&<div className={s.empty}>Nenhum cliente encontrado.</div>}</section></main>;
}
