'use client';
import {useEffect,useState} from 'react';
import {CHURCH_LOGO,LEGACY_LOGO} from './brand';
import {SB,KEY} from '../lib/sb';
type Ev={id:string;title:string;slug:string;event_date?:string;location?:string;cover_url?:string;face_search_enabled:boolean;is_paid:boolean};
export default function Home(){
 const [events,setEvents]=useState<Ev[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const r=await fetch(`${SB}/rest/v1/events?status=eq.published&select=id,title,slug,event_date,location,cover_url,face_search_enabled,is_paid&order=event_date.desc.nullslast,created_at.desc`,{headers:{apikey:KEY}});if(r.ok)setEvents(await r.json())}finally{setLoading(false)}})()},[]);
 function openEvent(slug:string){let visitor=null;try{visitor=JSON.parse(localStorage.getItem('semeando_visitor')||'null')}catch{};location.href=visitor?.id?`/evento/${slug}`:`/cadastro?next=${encodeURIComponent(`/evento/${slug}`)}`}
 return <main className="landing">
  <header className="home-nav"><a className="brand-lockup" href="/"><img src={CHURCH_LOGO} alt="Logo Igreja Semeando Amor"/><div><strong>Semeando Memórias</strong><span>Igreja Semeando Amor</span></div></a><a className="admin-link" href="/admin/login">Área administrativa</a></header>
  <section className="home-hero"><div className="hero-copy"><span className="hero-kicker">Galeria oficial • Igreja Semeando Amor</span><h1>Seus momentos.<br/><em>Seu legado em imagens.</em></h1><p>Encontre fotos dos eventos de forma simples, segura e inteligente. Faça seu cadastro uma única vez neste aparelho e use a busca facial quando disponível.</p><div className="hero-actions"><a className="btn hero-primary" href="#eventos">Acessar galerias</a><a className="hero-secondary" href="#como">Como funciona ↓</a></div><div className="hero-trust"><span>✓ Cadastro gratuito</span><span>✓ Busca facial com consentimento</span><span>✓ Sua selfie não é armazenada</span></div></div>
   <div className="hero-visual"><div className="hero-logo-orbit"><img src={CHURCH_LOGO} alt="Igreja Semeando Amor"/></div><div className="floating-card fc-one"><b>🤳</b><span>Envie uma selfie</span><small>ou escolha uma foto</small></div><div className="floating-card fc-two"><b>◎</b><span>Busca inteligente</span><small>encontre você no evento</small></div><div className="floating-card fc-three"><b>⚡</b><span>Resultado rápido</span><small>suas fotos em instantes</small></div></div>
  </section>
  <section id="como" className="home-strip"><article><span>01</span><div><strong>Cadastre-se</strong><p>Informe seus dados para liberar o acesso às galerias.</p></div></article><article><span>02</span><div><strong>Escolha o evento</strong><p>Acesse o álbum que deseja visualizar.</p></div></article><article><span>03</span><div><strong>Encontre você</strong><p>Veja todas as fotos ou utilize a busca facial.</p></div></article></section>
  <section id="eventos" className="events-section"><div className="section-heading"><div><span className="eyebrow">Galerias publicadas</span><h2>Eventos</h2></div><p>Selecione um evento para acessar as fotos</p></div>
   {loading?<div className="events-skeleton"><div/><div/></div>:events.length?<div className="event-cards">{events.map(e=><article className="event-card" key={e.id}><div className="event-card-cover" style={e.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,#0005),url(${e.cover_url})`}:{}}><div className="event-chips">{e.face_search_enabled&&<span className="face-chip">◎ Busca facial</span>}<span className={e.is_paid?'paid-chip':'free-chip'}>{e.is_paid?'Pago':'Gratuito'}</span></div></div><div className="event-card-body"><span className="event-meta">{e.event_date?new Date(e.event_date+'T12:00:00').toLocaleDateString('pt-BR'):'Evento'}{e.location?` • ${e.location}`:''}</span><h3>{e.title}</h3><p>{e.is_paid?'Pré-visualize as fotos protegidas e escolha suas favoritas.':'Acesse as fotos publicadas deste evento.'}</p><button className="btn event-open" onClick={()=>openEvent(e.slug)}>Abrir galeria</button></div></article>)}</div>:<div className="empty-events">Nenhuma galeria publicada no momento.</div>}
  </section>
  <section className="privacy-band"><div><span className="privacy-icon">🔒</span><div><strong>Privacidade em primeiro lugar</strong><p>O reconhecimento facial é opcional e exige consentimento específico. A foto de referência é utilizada somente durante a busca e não fica armazenada.</p></div></div><a href="/privacidade">Política de Privacidade →</a></section>
  <footer className="home-footer"><div className="footer-church"><img src={CHURCH_LOGO} alt=""/><div><strong>Igreja Semeando Amor</strong><span>Semeando Memórias</span></div></div><div className="developer-signature"><small>Desenvolvido por</small><img src={LEGACY_LOGO} alt="Legacy Solar"/><div><b>Legacy Solar</b><span>Energia que gera legado</span></div></div></footer>
 </main>
}
