'use client';
import {useEffect,useState} from 'react';
import {CHURCH_LOGO,DEVELOPER_LOGO,DEVELOPER_NAME,DEVELOPER_TAGLINE} from './brand';
import {SB,KEY} from '../lib/sb';
import {readVisitorSession} from '../lib/visitor-session';
type Ev={id:string;title:string;slug:string;event_date?:string;location?:string;cover_url?:string;face_search_enabled:boolean;is_paid:boolean;organization_name?:string;organization_logo?:string};
export default function Home(){
 const [events,setEvents]=useState<Ev[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{const authHash=new URLSearchParams(location.hash.replace(/^#/,'')),authType=authHash.get('type');if(authHash.get('access_token')&&(authType==='invite'||authType==='recovery')){location.replace(`/admin/primeiro-acesso${location.hash}`);return}(async()=>{try{localStorage.removeItem('semeando_private_gallery_access');const r=await fetch(`${SB}/functions/v1/gallery-catalog`,{headers:{apikey:KEY}}),d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível carregar as galerias.');setEvents(d.events||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}})()},[]);
 function openEvent(slug:string){const visitor=readVisitorSession();location.href=visitor?.id?`/evento/${slug}`:`/cadastro?next=${encodeURIComponent(`/evento/${slug}`)}`}
 return <main className="landing">
  <header className="home-nav"><a className="brand-lockup" href="/"><img src={CHURCH_LOGO} alt="Legacy Semeando Memórias"/><div><strong>Legacy Semeando Memórias</strong><span>Galerias de eventos</span></div></a><a className="admin-link" href="/acesso">Acesso da gestão</a></header>
  <section className="home-hero"><div className="hero-copy"><span className="hero-kicker">GALERIAS PÚBLICAS DA PLATAFORMA</span><h1>Seus momentos.<br/><em>Seu legado em imagens.</em></h1><p>Encontre galerias públicas de eventos em um único lugar. Álbuns privados aparecem somente para quem recebe o link exclusivo do responsável.</p><div className="hero-actions"><a className="btn hero-primary" href="#eventos">Acessar galerias públicas</a><a className="hero-secondary" href="#como">Como funciona ↓</a></div><div className="hero-trust"><span>✓ Cadastro gratuito</span><span>✓ Busca facial com consentimento</span><span>✓ Álbuns privados protegidos por link</span></div></div>
   <div className="hero-visual"><div className="hero-logo-orbit"><img src={CHURCH_LOGO} alt="Legacy Semeando Memórias"/></div><div className="floating-card fc-one"><b>🌐</b><span>Álbuns públicos</span><small>disponíveis na plataforma</small></div><div className="floating-card fc-two"><b>🔗</b><span>Álbuns privados</span><small>somente pelo link do cliente</small></div><div className="floating-card fc-three"><b>⚡</b><span>Busca inteligente</span><small>encontre suas fotos rápido</small></div></div>
  </section>
  <section id="como" className="home-strip"><article><span>01</span><div><strong>Escolha um evento</strong><p>Veja somente os álbuns que os responsáveis publicaram para todos.</p></div></article><article><span>02</span><div><strong>Cadastre-se</strong><p>Faça o cadastro uma única vez neste aparelho para acessar as galerias.</p></div></article><article><span>03</span><div><strong>Encontre você</strong><p>Quando disponível, use a busca facial com consentimento.</p></div></article></section>
  <section id="eventos" className="events-section"><div className="section-heading"><div><span className="eyebrow">Galerias públicas</span><h2>Eventos disponíveis</h2></div><p>Somente eventos marcados como públicos aparecem aqui.</p></div>
   {error&&<div className="empty-events">{error}</div>}{loading?<div className="events-skeleton"><div/><div/></div>:events.length?<div className="event-cards">{events.map(e=><article className="event-card" key={e.id}><div className="event-card-cover" style={e.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,#0005),url(${e.cover_url})`}:{}}><div className="event-chips">{e.face_search_enabled&&<span className="face-chip">◎ Busca facial</span>}<span className={e.is_paid?'paid-chip':'free-chip'}>{e.is_paid?'Pago':'Gratuito'}</span></div></div><div className="event-card-body"><span className="event-meta">{e.organization_name||'Legacy Semeando Memórias'}</span><span className="event-meta">{e.event_date?new Date(e.event_date+'T12:00:00').toLocaleDateString('pt-BR'):'Evento'}{e.location?` • ${e.location}`:''}</span><h3>{e.title}</h3><p>{e.is_paid?'Pré-visualize as fotos protegidas e escolha suas favoritas.':'Acesse as fotos publicadas deste evento.'}</p><button className="btn event-open" onClick={()=>openEvent(e.slug)}>Abrir galeria</button></div></article>)}</div>:!error&&<div className="empty-events">Nenhuma galeria pública no momento.</div>}
  </section>
  <section className="privacy-band"><div><span className="privacy-icon">🔒</span><div><strong>Público quando o cliente quiser. Privado quando precisar.</strong><p>Cada organização decide quais eventos aparecem nesta vitrine e quais ficam disponíveis somente por um link privado.</p></div></div><a href="/privacidade">Política de Privacidade →</a></section>
  <footer className="home-footer"><div className="footer-church"><img src={CHURCH_LOGO} alt=""/><div><strong>Legacy Semeando Memórias</strong><span>Galerias inteligentes</span></div></div><div className="developer-signature"><small>Desenvolvido por</small><img src={DEVELOPER_LOGO} alt={DEVELOPER_NAME}/><div><b>{DEVELOPER_NAME}</b><span>{DEVELOPER_TAGLINE}</span></div></div></footer>
  <style jsx>{`@media(max-width:500px){.home-nav{padding:16px 14px;gap:10px}.brand-lockup{gap:8px}.brand-lockup img{width:46px;height:46px}.brand-lockup strong{font-size:12px}.brand-lockup span{display:none}.admin-link{flex:none;padding:9px 10px;font-size:10px}}`}</style>
 </main>
}
