'use client';
import {useEffect,useMemo,useState} from 'react';
import {KEY,SB,readSession} from '../../lib/sb';
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function BillingCenter(){const[orgs,setOrgs]=useState<any[]>([]),[orgId,setOrgId]=useState(''),[detail,setDetail]=useState<any>(null),[gateway,setGateway]=useState<any>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[billingType,setBillingType]=useState('PIX'),[cycle,setCycle]=useState('MONTHLY'),[dueDays,setDueDays]=useState('3');const selected=useMemo(()=>orgs.find(x=>x.id===orgId),[orgs,orgId]);
 async function token(){const s=readSession();if(!s?.access_token){location.href='/acesso';throw Error('Sessão expirada.')}return s.access_token}
 async function devConsole(){const t=await token();const r=await fetch(`${SB}/functions/v1/developer-console`,{headers:{apikey:KEY,Authorization:`Bearer ${t}`}}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao carregar clientes.');return d}
 async function billing(action:string,extra:any={}){const t=await token();const r=await fetch(`${SB}/functions/v1/developer-billing`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({action,organization_id:orgId,...extra})}),d=await r.json();if(!r.ok)throw Error(d.message||d.error||'Falha no faturamento.');return d}
 async function client360(id:string){const t=await token();const r=await fetch(`${SB}/functions/v1/developer-client360?organization_id=${encodeURIComponent(id)}`,{headers:{apikey:KEY,Authorization:`Bearer ${t}`}}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao carregar cliente.');return d}
 async function loadBase(){try{const d=await devConsole(),list=d.organizations||[];setOrgs(list);if(!orgId&&list.length)setOrgId(list[0].id)}catch(e:any){setMsg(e.message)}}useEffect(()=>{loadBase()},[]);
 async function loadOrg(){if(!orgId)return;setBusy(true);setMsg('');try{const[d,g]=await Promise.all([client360(orgId),billing('gateway_status')]);setDetail(d);setGateway(g)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}useEffect(()=>{if(orgId)loadOrg()},[orgId]);
 async function act(fn:()=>Promise<any>,ok:string){setBusy(true);setMsg('');try{await fn();await loadOrg();setMsg(ok)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const sub=detail?.subscription||{},charge=detail?.latest_subscription_charge||null;
 return <main className="page"><header><div><a href="/developer">← Developer</a><span>FATURAMENTO</span><h1>Centro de Faturamento</h1><p>Assinaturas, cobranças e ciclo de inadimplência em um único lugar.</p></div><a className="link" href="/developer/entregas">Entregas</a></header>{msg&&<div className="notice">{msg}</div>}
 <section className="panel"><label>Cliente<select value={orgId} onChange={e=>setOrgId(e.target.value)}>{orgs.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label>{selected&&<div className="summary"><div><span>Cliente</span><b>{selected.name}</b><small>{selected.document_number||'CPF/CNPJ não cadastrado'}</small></div><div><span>Status</span><b>{sub.status||selected.status||'—'}</b><small>{sub.provider||'sem gateway'}</small></div><div><span>Mensalidade</span><b>{money(sub.amount)}</b><small>{sub.plan_id?'assinatura local':'sem plano'}</small></div><div><span>Próxima cobrança</span><b>{sub.next_billing_at?new Date(sub.next_billing_at).toLocaleDateString('pt-BR'):'—'}</b><small>{sub.provider_subscription_id?'recorrência ativa':'sem recorrência'}</small></div></div>}</section>
 <section className="panel"><div className="panelHead"><div><span>ASAAS</span><h2>Gateway</h2></div><b className={gateway?.configured?'ok':'off'}>{gateway?.configured?`Conectado • ${gateway.environment}`:'Aguardando credenciais'}</b></div><div className="summary"><div><span>Recorrência</span><b>{sub.provider_subscription_id?'Ativa':'Inativa'}</b><small>{sub.provider_subscription_id||'nenhuma assinatura Asaas'}</small></div><div><span>Última cobrança</span><b>{charge?.status||'—'}</b><small>{charge?money(charge.amount):'nenhuma cobrança'}</small></div><div><span>Atraso</span><b>{sub.overdue_since?new Date(sub.overdue_since).toLocaleDateString('pt-BR'):'—'}</b><small>{sub.grace_ends_at?`tolerância até ${new Date(sub.grace_ends_at).toLocaleDateString('pt-BR')}`:'sem atraso'}</small></div></div></section>
 <section className="panel"><span>AUTOMAÇÃO</span><h2>Assinatura recorrente</h2><p>O Asaas gera as próximas cobranças automaticamente. O sistema acompanha cada pagamento pelo webhook e bloqueia o acesso se a tolerância vencer.</p><div className="controls"><label>Forma<select value={billingType} onChange={e=>setBillingType(e.target.value)}><option value="PIX">PIX</option><option value="BOLETO">Boleto</option></select></label><label>Ciclo<select value={cycle} onChange={e=>setCycle(e.target.value)}><option value="MONTHLY">Mensal</option><option value="YEARLY">Anual</option></select></label><label>Primeiro vencimento<select value={dueDays} onChange={e=>setDueDays(e.target.value)}><option value="1">1 dia</option><option value="3">3 dias</option><option value="5">5 dias</option><option value="7">7 dias</option></select></label></div><div className="actions">{!sub.provider_subscription_id?<button disabled={busy||!gateway?.configured||!sub.id} onClick={()=>act(()=>billing('create_subscription',{billing_type:billingType,cycle,due_days:Number(dueDays)}),'Assinatura recorrente criada.')}>Ativar recorrência</button>:<><button disabled={busy} className="alt" onClick={()=>act(()=>billing('sync_subscription'),'Assinatura sincronizada com o Asaas.')}>Sincronizar</button><button disabled={busy} className="danger" onClick={()=>confirm('Cancelar a recorrência deste cliente?')&&act(()=>billing('cancel_subscription'),'Recorrência cancelada.')}>Cancelar recorrência</button></>}</div></section>
 <section className="panel"><span>COBRANÇA AVULSA</span><h2>Gerar cobrança manual</h2><p>Use somente para primeira cobrança, ajuste ou exceção. Para mensalidade normal, prefira recorrência.</p><div className="controls"><label>Forma<select value={billingType} onChange={e=>setBillingType(e.target.value)}><option value="PIX">PIX</option><option value="BOLETO">Boleto</option><option value="CREDIT_CARD">Cartão</option><option value="UNDEFINED">Cliente escolhe</option></select></label><label>Vencimento<select value={dueDays} onChange={e=>setDueDays(e.target.value)}><option value="1">1 dia</option><option value="3">3 dias</option><option value="5">5 dias</option><option value="7">7 dias</option></select></label><button disabled={busy||!gateway?.configured||!sub.id} onClick={()=>act(()=>billing('create_charge',{billing_type:billingType,due_days:Number(dueDays)}),'Cobrança criada.')}>Gerar cobrança</button></div>{charge?.invoice_url&&<a className="invoice" href={charge.invoice_url} target="_blank">Abrir última fatura ↗</a>}</section>
 <style jsx>{`.page{max-width:1180px;margin:auto;padding:92px 18px 50px;color:#f4f4f5}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:22px}header a{color:#ff8b42;text-decoration:none;font-weight:800}header span,.panel>span,.panelHead span{font-size:10px;letter-spacing:.18em;color:#ff8b42;font-weight:900}h1{font-size:34px;margin:7px 0}h2{margin:5px 0 8px}.panel{background:#15171c;border:1px solid #2c3038;border-radius:18px;padding:18px;margin:14px 0}.panelHead{display:flex;justify-content:space-between;gap:16px;align-items:center}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.summary>div{background:#101216;border:1px solid #272b32;border-radius:13px;padding:13px;display:grid;gap:4px}.summary span,label span{font-size:10px;color:#9299a3}.summary b{font-size:15px}.summary small{color:#858b94}.controls{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.controls label,.panel>label{display:grid;gap:6px;min-width:180px;font-size:11px;color:#adb2ba}.panel>label select{margin-top:7px}select{background:#0e1014;color:#fff;border:1px solid #333944;border-radius:10px;padding:11px}.actions{display:flex;gap:9px;margin-top:14px;flex-wrap:wrap}button,.invoice,.link{border:0;background:#ff7417;color:#111;padding:11px 14px;border-radius:10px;font-weight:900;text-decoration:none;cursor:pointer}.alt{background:#282c34;color:#fff}.danger{background:#7f2929;color:#fff}.ok{color:#6ee7a7}.off{color:#ff9f66}.notice{background:#241a14;border:1px solid #5b3825;border-radius:12px;padding:12px}.invoice{display:inline-block;margin-top:13px}.panel p,header p{color:#989fa9}.link{background:#242932;color:#fff}@media(max-width:760px){.summary{grid-template-columns:1fr 1fr}header{display:block}.link{display:inline-block;margin-top:12px}.controls label{min-width:100%}}`}</style></main>}
