(()=>{'use strict';
const ID='v67remote';let active=false,wake=null;
const $=s=>document.querySelector(s);
const css=`#${ID}{display:none;position:fixed;inset:0;z-index:2147483500;background:#080a0d;color:#fff;font-family:Inter,system-ui,sans-serif;overflow:auto}#${ID}.on{display:block}.v67top{position:sticky;top:0;z-index:4;display:flex;align-items:center;gap:10px;padding:12px 14px;background:#0f1217ee;backdrop-filter:blur(12px);border-bottom:1px solid #2a3039}.v67brand{font-weight:900;letter-spacing:.07em;font-size:12px}.v67sp{flex:1}.v67status{font-size:10px;font-weight:900;padding:6px 9px;border-radius:999px;background:#17351e;color:#8ff49f}.v67status.off{background:#3b1818;color:#ff9999}.v67close{border:1px solid #3b424d;background:#171b21;color:#fff;border-radius:10px;padding:8px 10px;font-weight:900}.v67wrap{max-width:760px;margin:auto;padding:12px}.v67grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.v67card{background:#11161d;border:1px solid #2c3540;border-radius:15px;padding:13px}.v67card.full{grid-column:1/-1}.v67label{font-size:9px;letter-spacing:.13em;font-weight:900;color:#ff8a00;margin-bottom:6px}.v67now{font-size:clamp(21px,5vw,34px);font-weight:900;line-height:1.08}.v67next{font-size:clamp(16px,3.7vw,24px);font-weight:800;color:#d6dbe3}.v67preview{font-size:15px;font-weight:700;white-space:pre-line;color:#dfe4eb;max-height:92px;overflow:hidden}.v67controls{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:10px}.v67btn{min-height:58px;border:1px solid #343d49;background:#171d25;color:#fff;border-radius:13px;font-weight:900;font-size:13px}.v67btn.take{background:#f57c00;border-color:#ff9800;color:#15100a;font-size:16px}.v67btn.dark{background:#050607}.v67section{margin-top:10px;background:#10151b;border:1px solid #29323d;border-radius:15px;padding:12px}.v67section h3{margin:0 0 9px;font-size:10px;letter-spacing:.11em;color:#aeb7c3}.v67row{display:flex;gap:7px}.v67row input{min-width:0;flex:1;background:#080b0f;border:1px solid #343d49;color:#fff;border-radius:11px;padding:12px;font-size:14px}.v67small{border:1px solid #343d49;background:#171d25;color:#fff;border-radius:10px;padding:10px 11px;font-weight:900;font-size:11px}.v67presets{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;margin-top:8px}.v67hint{font-size:9px;color:#7f8995;margin-top:8px}.v67entry{position:fixed;right:16px;bottom:72px;z-index:99998;background:#111923;color:#fff;border:1px solid #f57c00;border-radius:999px;padding:11px 15px;font-weight:900;box-shadow:0 8px 24px #0009}@media(max-width:520px){.v67wrap{padding:9px}.v67grid{grid-template-columns:1fr}.v67card.full{grid-column:auto}.v67controls{grid-template-columns:repeat(3,1fr)}.v67btn{min-height:62px;font-size:12px}.v67presets{grid-template-columns:repeat(2,1fr)}.v67brand{font-size:10px}}`;
function text(sels,f='—'){for(const s of sels){const e=$(s);if(e&&e.textContent.trim())return e.textContent.trim()}return f}
function clickSel(sel,re){let e=sel&&$(sel);if(!e&&re)e=[...document.querySelectorAll('button,[role=button],.btn,.take')].filter(x=>!x.closest('#'+ID)).find(x=>re.test((x.textContent||'').trim()));if(e){e.click();return true}return false}
function sync(){if(!active)return;$('#v67now').textContent=text(['#v65now','#v60dock .v60body .v60card:nth-child(1) b'],'Pronto para o culto');$('#v67next').textContent=text(['#v65next','#v60dock .v60body .v60card:nth-child(2) b'],'Fim do roteiro');$('#v67preview').textContent=text(['#v66preview','#previewText','#preview .big','#preview .previewText'],'Preview pronto');status()}
function status(){let e=$('#v67status');if(!e)return;e.textContent=navigator.onLine?'● ONLINE':'● OFFLINE';e.classList.toggle('off',!navigator.onLine)}
async function keepAwake(on){try{if(on&&'wakeLock'in navigator){wake=await navigator.wakeLock.request('screen');wake.addEventListener('release',()=>{wake=null})}else if(!on&&wake){await wake.release();wake=null}}catch{}}
function stage(p){if(window.SemeandoV62?.patch)return window.SemeandoV62.patch(p)}
function notice(v){let input=$('#v67notice');if(input)input.value=v||'';stage({stageNotice:v||''})}
function timer(min){stage({timerEnd:min?new Date(Date.now()+min*60000).toISOString():null})}
function act(a){if(a==='prev')clickSel('#v60prev',/anterior|voltar/i);if(a==='take'){clickSel('#take',/ao ar|take/i);navigator.vibrate?.(45)}if(a==='next')clickSel('#v60next',/próximo|avançar/i);if(a==='black')clickSel('#black',/blackout/i);if(a==='clear')clickSel('#clear',/limpar|clear/i);if(a==='undo')clickSel('#undo',/desfazer|undo/i);setTimeout(sync,100)}
function build(){if($( '#'+ID))return;let st=document.createElement('style');st.id='v67style';st.textContent=css;document.head.appendChild(st);let d=document.createElement('div');d.id=ID;d.innerHTML=`<div class="v67top"><span class="v67brand">SEMEANDO LIVE · V6.7 CONTROLE REMOTO</span><span class="v67sp"></span><span id="v67status" class="v67status">● ONLINE</span><button id="v67close" class="v67close">✕</button></div><main class="v67wrap"><div class="v67grid"><section class="v67card"><div class="v67label">AGORA</div><div id="v67now" class="v67now">Pronto para o culto</div></section><section class="v67card"><div class="v67label">PRÓXIMO</div><div id="v67next" class="v67next">Fim do roteiro</div></section><section class="v67card full"><div class="v67label">PREVIEW</div><div id="v67preview" class="v67preview">Preview pronto</div></section></div><div class="v67controls"><button class="v67btn" data-a="prev">◀ ANTERIOR</button><button class="v67btn take" data-a="take">▶ AO AR</button><button class="v67btn" data-a="next">PRÓXIMO ▶</button><button class="v67btn dark" data-a="black">⬛ BLACKOUT</button><button class="v67btn" data-a="clear">✕ LIMPAR</button><button class="v67btn" data-a="undo">↶ DESFAZER</button></div><section class="v67section"><h3>AVISO PRIVADO PARA O STAGE</h3><div class="v67row"><input id="v67notice" placeholder="Ex.: Pastor, faltam 5 minutos"><button id="v67send" class="v67small">ENVIAR</button></div><div class="v67presets"><button class="v67small" data-note="5 minutos">5 MIN</button><button class="v67small" data-note="Encerrar">ENCERRAR</button><button class="v67small" data-note="Aguardar">AGUARDAR</button><button class="v67small" data-note="Pode subir">PODE SUBIR</button></div><div class="v67hint">Esse aviso aparece somente na tela Stage.</div></section><section class="v67section"><h3>TIMER DO PALCO</h3><div class="v67presets"><button class="v67small" data-timer="5">5 MIN</button><button class="v67small" data-timer="10">10 MIN</button><button class="v67small" data-timer="15">15 MIN</button><button class="v67small" data-timer="0">ZERAR</button></div></section></main>`;document.body.appendChild(d);d.addEventListener('click',e=>{let a=e.target.closest('[data-a]')?.dataset.a;if(a)act(a);let n=e.target.closest('[data-note]')?.dataset.note;if(n!=null)notice(n);let t=e.target.closest('[data-timer]')?.dataset.timer;if(t!=null)timer(Number(t))});$('#v67send').onclick=()=>notice($('#v67notice').value.trim());$('#v67close').onclick=()=>toggle(false);status()}
async function toggle(on=!active){build();active=on;$('#'+ID).classList.toggle('on',active);document.body.style.overflow=active?'hidden':'';localStorage.setItem('sl_v67_remote',active?'1':'0');await keepAwake(active);sync()}
function entry(){if($('#v67entry'))return;let b=document.createElement('button');b.id='v67entry';b.className='v67entry';b.textContent='📱 Controle Remoto';b.onclick=()=>toggle(true);document.body.appendChild(b)}
function boot(){if(new URLSearchParams(location.search).get('view')==='output')return;build();entry();addEventListener('online',status);addEventListener('offline',status);document.addEventListener('visibilitychange',()=>{if(active&&!document.hidden)keepAwake(true)});new MutationObserver(()=>sync()).observe(document.body,{subtree:true,childList:true,characterData:true});let q=new URLSearchParams(location.search);if(q.get('remote')==='1'||localStorage.getItem('sl_v67_remote')==='1')toggle(true);window.SemeandoV67={toggle,sync,notice,timer}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();