(()=>{'use strict';
const q=new URLSearchParams(location.search),isOutput=q.get('view')==='output',channel=q.get('channel')||'audience',BC='sl-v71-health',KEY='sl_v71_last_state',LOCK='sl_v71_safety_lock';let bus=null,last={},armedUntil=0;
const $=s=>document.querySelector(s);const now=()=>Date.now();
function css(){if($('#v71css'))return;const s=document.createElement('style');s.id='v71css';s.textContent=`#v71safety{margin-top:10px;border:1px solid #35414d;background:linear-gradient(180deg,#111923,#090e14);border-radius:15px;padding:12px;color:#fff}.v71h{display:flex;align-items:center;gap:8px}.v71h b{font-size:11px;letter-spacing:.08em}.v71h small{font-size:8px;color:#8d99a7}.v71sp{flex:1}.v71ready{font-size:9px;font-weight:900;padding:6px 9px;border-radius:999px;background:#17351e;color:#92f2a1}.v71ready.warn{background:#3d2710;color:#ffc36d}.v71grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:10px}.v71card{border:1px solid #303b48;background:#10171f;border-radius:10px;padding:9px}.v71card b{display:block;font-size:9px}.v71card small{display:block;font-size:8px;color:#8995a3;margin-top:4px}.v71dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#596573;margin-right:5px}.v71dot.ok{background:#36c96c;box-shadow:0 0 10px #36c96c88}.v71dot.bad{background:#ef5350}.v71actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.v71btn{border:1px solid #374452;background:#151d26;color:#fff;border-radius:9px;padding:9px 10px;font-size:9px;font-weight:850}.v71btn.on{border-color:#f57c00;background:#2a180a;color:#ffb15e}.v71btn.danger{border-color:#7a3434;color:#ffaaaa}.v71hint{font-size:8px;color:#788493;margin-top:8px}.v71toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2147483600;background:#171d24;color:#fff;border:1px solid #495563;border-radius:12px;padding:11px 14px;font:800 11px system-ui;box-shadow:0 12px 32px #000a}.v71armed{border-color:#f57c00!important;box-shadow:0 0 0 2px #f57c0033!important}@media(max-width:760px){.v71grid{grid-template-columns:1fr 1fr}.v71h small{display:none}}`;document.head.appendChild(s)}
function send(type,data={}){const m={type,channel,t:now(),...data};try{bus?.postMessage(m)}catch{} }
function heartbeat(){if(isOutput)send('heartbeat',{visible:!document.hidden,online:navigator.onLine})}
function snapshot(){if(isOutput)return;const s={t:now(),online:navigator.onLine,now:$('#v65now')?.textContent?.trim()||'',next:$('#v65next')?.textContent?.trim()||'',preview:$('#v65preview')?.textContent?.trim()||'',live:$('#v65live')?.textContent?.trim()||''};localStorage.setItem(KEY,JSON.stringify(s))}
function getSnap(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}
function toast(t){document.querySelector('.v71toast')?.remove();const d=document.createElement('div');d.className='v71toast';d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
function lockOn(){return localStorage.getItem(LOCK)!=='0'}function setLock(v){localStorage.setItem(LOCK,v?'1':'0');paint()}
function status(ch){return now()-(last[ch]||0)<5500}
function paint(){const root=$('#v71safety');if(!root)return;const online=navigator.onLine,fs=!!document.fullscreenElement,service=!!($('#serviceSelect')?.value||$('#serviceTitle')?.textContent?.trim()||$('#v60dock'));const checks=[online,service];const ready=checks.every(Boolean);const badge=$('#v71ready');badge.textContent=ready?'● PRONTO':'● ATENÇÃO';badge.classList.toggle('warn',!ready);const map={net:[online,'Internet',online?'Conectado':'Sem conexão'],service:[service,'Culto',service?'Roteiro disponível':'Verificar culto'],screen:[fs,'Tela cheia',fs?'Ativa':'Opcional'],lock:[lockOn(),'Proteção',lockOn()?'Críticos protegidos':'Desativada']};Object.entries(map).forEach(([k,v])=>{const e=$('#v71-'+k);if(!e)return;e.querySelector('.v71dot').className='v71dot '+(v[0]?'ok':'bad');e.querySelector('small').textContent=v[2]});['audience','broadcast','stage','lobby'].forEach(ch=>{const e=$('#v71out-'+ch);if(e){const ok=status(ch);e.querySelector('.v71dot').className='v71dot '+(ok?'ok':'bad');e.querySelector('small').textContent=ok?'Saída respondendo':'Não detectada neste navegador'}});$('#v71lock')?.classList.toggle('on',lockOn())}
function intercept(e){if(isOutput||!lockOn())return;const b=e.target.closest('#black,#clear,#v65black,#v65clear,[data-a="black"],[data-a="clear"]');if(!b)return;if(now()<armedUntil){armedUntil=0;b.classList.remove('v71armed');return}e.preventDefault();e.stopImmediatePropagation();armedUntil=now()+3000;b.classList.add('v71armed');toast('Proteção ativa: toque novamente em até 3 segundos para confirmar.');setTimeout(()=>b.classList.remove('v71armed'),3100)}
function openAll(){if(window.SemeandoV70?.open)['audience','broadcast','stage','lobby'].forEach((ch,i)=>setTimeout(()=>window.SemeandoV70.open(ch),i*180));else toast('Broadcast Pro ainda não carregou.')}
function emergencyUndo(){const b=$('#undo')||$('#v65undo');if(b){b.click();toast('Última ação desfeita.')}else toast('Comando Desfazer não encontrado.')}
function panel(){if(isOutput||$('#v71safety'))return;css();const host=document.querySelector('[data-panel="production"] .prodGrid')||document.querySelector('[data-panel="production"]')||$('#operator');if(!host)return;const s=getSnap(),d=document.createElement('section');d.id='v71safety';d.innerHTML=`<div class="v71h"><div><b>V7.1 · SEGURANÇA OPERACIONAL</b><small>Pré-culto, diagnóstico e proteção contra erros</small></div><span class="v71sp"></span><span id="v71ready" class="v71ready">● PRONTO</span></div><div class="v71grid"><div class="v71card" id="v71-net"><b><span class="v71dot"></span>INTERNET</b><small>Verificando...</small></div><div class="v71card" id="v71-service"><b><span class="v71dot"></span>CULTO</b><small>Verificando...</small></div><div class="v71card" id="v71-screen"><b><span class="v71dot"></span>TELA CHEIA</b><small>Verificando...</small></div><div class="v71card" id="v71-lock"><b><span class="v71dot"></span>PROTEÇÃO</b><small>Verificando...</small></div><div class="v71card" id="v71out-audience"><b><span class="v71dot"></span>TELÃO</b><small>Aguardando...</small></div><div class="v71card" id="v71out-broadcast"><b><span class="v71dot"></span>TRANSMISSÃO</b><small>Aguardando...</small></div><div class="v71card" id="v71out-stage"><b><span class="v71dot"></span>STAGE</b><small>Aguardando...</small></div><div class="v71card" id="v71out-lobby"><b><span class="v71dot"></span>LOBBY</b><small>Aguardando...</small></div></div><div class="v71actions"><button class="v71btn on" id="v71lock">🔒 Proteger comandos críticos</button><button class="v71btn" id="v71openall">Abrir/reabrir 4 saídas</button><button class="v71btn" id="v71full">Tela cheia</button><button class="v71btn danger" id="v71undo">↶ Desfazer emergência</button><button class="v71btn" id="v71reload">↻ Recarregar interface</button></div><div class="v71hint">Blackout e Limpar exigem confirmação em dois toques quando a proteção está ativa.${s.t?' Último estado local salvo às '+new Date(s.t).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})+'.':''}</div>`;host.prepend(d);$('#v71lock').onclick=()=>setLock(!lockOn());$('#v71openall').onclick=openAll;$('#v71full').onclick=()=>document.documentElement.requestFullscreen?.();$('#v71undo').onclick=emergencyUndo;$('#v71reload').onclick=()=>location.reload();paint()}
function boot(){css();try{bus=new BroadcastChannel(BC);bus.onmessage=e=>{if(e.data?.type==='heartbeat'){last[e.data.channel]=e.data.t;paint()}}}catch{};if(isOutput){heartbeat();setInterval(heartbeat,1800);addEventListener('visibilitychange',heartbeat);return}if(localStorage.getItem(LOCK)==null)localStorage.setItem(LOCK,'1');document.addEventListener('click',intercept,true);addEventListener('online',paint);addEventListener('offline',paint);document.addEventListener('fullscreenchange',paint);setInterval(()=>{snapshot();paint()},1500);let n=0,t=setInterval(()=>{panel();if($('#v71safety')||++n>50)clearInterval(t)},100);window.SemeandoV71={snapshot:getSnap,lock:setLock,status:()=>({...last})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();