import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { RekognitionClient, CreateCollectionCommand, DeleteCollectionCommand, DescribeCollectionCommand, IndexFacesCommand, SearchFacesByImageCommand, ListCollectionsCommand } from "npm:@aws-sdk/client-rekognition@3.883.0";

const SB=(Deno.env.get('SUPABASE_URL')||'https://mdhlhriakqqsocopravb.supabase.co').trim();
const ANON=(Deno.env.get('SUPABASE_ANON_KEY')||'').trim();
const SERVICE=(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim();
const AWS_REGION=(Deno.env.get('AWS_REGION')||'sa-east-1').trim();
const AWS_ACCESS_KEY_ID=(Deno.env.get('AWS_ACCESS_KEY_ID')||'').trim();
const AWS_SECRET_ACCESS_KEY=(Deno.env.get('AWS_SECRET_ACCESS_KEY')||'').trim();
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,x-client-info,apikey,content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
function j(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors,'Content-Type':'application/json'}})}
function awsReady(){return !!(AWS_ACCESS_KEY_ID&&AWS_SECRET_ACCESS_KEY)}
function client(){if(!awsReady())throw new Error('AWS_REKOGNITION_NOT_CONFIGURED');return new RekognitionClient({region:AWS_REGION,credentials:{accessKeyId:AWS_ACCESS_KEY_ID,secretAccessKey:AWS_SECRET_ACCESS_KEY}})}
function collectionId(eventId:string){return `sm-${eventId.replace(/-/g,'')}`.slice(0,255)}
function adminHeaders(auth:string){return {apikey:ANON,Authorization:auth}}
function svcHeaders(){return {apikey:SERVICE,Authorization:`Bearer ${SERVICE}`,'Content-Type':'application/json'}}
async function requireAdmin(req:Request){const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))throw new Error('Sessão administrativa necessária.');const ur=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:ANON,Authorization:auth}});const u=await ur.json();if(!ur.ok||!u?.id)throw new Error('Sessão inválida ou expirada.');const pr=await fetch(`${SB}/rest/v1/admin_profiles?user_id=eq.${encodeURIComponent(u.id)}&is_active=eq.true&select=role`,{headers:adminHeaders(auth)});const p=await pr.json();if(!pr.ok||!p?.length)throw new Error('Usuário sem permissão administrativa.');return {auth,user:u}}
function jpgUrl(url:string,w=1600,q=80){if(!/res\.cloudinary\.com\//.test(url))return url;return url.replace('/upload/','/upload/f_jpg,c_limit,w_'+w+',q_'+q+'/')}
async function imageBytes(url:string){let r=await fetch(jpgUrl(url,1600,80));if(!r.ok)throw new Error('Não foi possível preparar a foto para reconhecimento.');let b=new Uint8Array(await r.arrayBuffer());if(b.byteLength>5*1024*1024){r=await fetch(jpgUrl(url,1200,70));if(!r.ok)throw new Error('Não foi possível reduzir a foto.');b=new Uint8Array(await r.arrayBuffer())}if(b.byteLength>5*1024*1024)throw new Error('Foto acima do limite de 5 MB do reconhecimento.');return b}
async function getEvent(id:string){const r=await fetch(`${SB}/rest/v1/events?id=eq.${encodeURIComponent(id)}&select=id,title,slug,face_search_enabled`,{headers:svcHeaders()});const d=await r.json();if(!r.ok||!d?.[0])throw new Error('Evento não encontrado.');return d[0]}
async function exactCount(path:string){const r=await fetch(`${SB}/rest/v1/${path}`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`,Prefer:'count=exact'}});if(!r.ok)throw new Error('Falha ao contar registros.');return Number((r.headers.get('content-range')||'').split('/')[1]||0)}
async function collectionExists(cid:string){try{await client().send(new DescribeCollectionCommand({CollectionId:cid}));return true}catch(e:any){if(e?.name==='ResourceNotFoundException')return false;throw e}}

// Fluxo legado preservado para recuperação completa da coleção.
async function doPrepareIndex(eventId:string){if(!awsReady())return j({error:'AWS_REKOGNITION_NOT_CONFIGURED'},503);if(!eventId)return j({error:'event_id é obrigatório.'},400);const ev=await getEvent(eventId),cid=collectionId(eventId),rek=client();try{await rek.send(new DeleteCollectionCommand({CollectionId:cid}))}catch(e:any){if(e?.name!=='ResourceNotFoundException')console.log('delete collection',e?.name||e)}await rek.send(new CreateCollectionCommand({CollectionId:cid}));await fetch(`${SB}/rest/v1/face_index?event_id=eq.${encodeURIComponent(eventId)}`,{method:'DELETE',headers:svcHeaders()});await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(eventId)}`,{method:'DELETE',headers:svcHeaders()});await fetch(`${SB}/rest/v1/face_collections`,{method:'POST',headers:{...svcHeaders(),Prefer:'return=representation'},body:JSON.stringify({event_id:eventId,collection_id:cid,status:'indexing',indexed_photos:0,indexed_faces:0})});await fetch(`${SB}/rest/v1/events?id=eq.${encodeURIComponent(eventId)}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_search_enabled:true})});await fetch(`${SB}/rest/v1/photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'pending'})});const total=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&select=id`);return j({ok:true,mode:'full',event:{id:ev.id,title:ev.title},collection_id:cid,total_photos:total,batch_size:8})}

async function doPrepareIncremental(eventId:string){if(!awsReady())return j({error:'AWS_REKOGNITION_NOT_CONFIGURED'},503);if(!eventId)return j({error:'event_id é obrigatório.'},400);const ev=await getEvent(eventId),cid=collectionId(eventId);const cr=await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(eventId)}&select=collection_id,status,indexed_photos,indexed_faces&limit=1`,{headers:svcHeaders()}),cols=await cr.json();const healthy=cr.ok&&cols?.[0]?.collection_id===cid&&await collectionExists(cid);if(!healthy)return await doPrepareIndex(eventId);await fetch(`${SB}/rest/v1/photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.failed`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'pending'})});const pending=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.pending&select=id`);const indexedPhotos=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.indexed&select=id`);const faceTotal=await exactCount(`face_index?event_id=eq.${encodeURIComponent(eventId)}&select=id`);await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(eventId)}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({status:pending?'indexing':'ready',indexed_photos:indexedPhotos,indexed_faces:faceTotal,last_error:null,updated_at:new Date().toISOString(),...(pending?{}:{indexed_at:new Date().toISOString()})})});await fetch(`${SB}/rest/v1/events?id=eq.${encodeURIComponent(eventId)}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_search_enabled:true})});return j({ok:true,mode:'incremental',event:{id:ev.id,title:ev.title},collection_id:cid,total_photos:pending,already_indexed:indexedPhotos,total_faces:faceTotal,batch_size:8,done:pending===0})}

async function indexPhoto(eventId:string,cid:string,p:any){const existing=await exactCount(`face_index?event_id=eq.${encodeURIComponent(eventId)}&photo_id=eq.${encodeURIComponent(p.id)}&select=id`);if(existing>0){await fetch(`${SB}/rest/v1/photos?id=eq.${p.id}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'indexed'})});return {faces:existing,reused:true}}const bytes=await imageBytes(p.secure_url);const out=await client().send(new IndexFacesCommand({CollectionId:cid,Image:{Bytes:bytes},ExternalImageId:p.id,QualityFilter:'AUTO',MaxFaces:100}));const rows=(out.FaceRecords||[]).filter(x=>x.Face?.FaceId).map(x=>({event_id:eventId,photo_id:p.id,provider_face_id:x.Face!.FaceId!,confidence:x.Face?.Confidence??null,bounding_box:x.Face?.BoundingBox||null}));if(rows.length){const sr=await fetch(`${SB}/rest/v1/face_index`,{method:'POST',headers:svcHeaders(),body:JSON.stringify(rows)});if(!sr.ok)throw new Error((await sr.text())||'Falha ao salvar índice facial')}await fetch(`${SB}/rest/v1/photos?id=eq.${p.id}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'indexed'})});return {faces:rows.length,reused:false}}

async function doIndexBatch(eventId:string,offset:number,limit:number){if(!awsReady())return j({error:'AWS_REKOGNITION_NOT_CONFIGURED'},503);if(!eventId)return j({error:'event_id é obrigatório.'},400);offset=Math.max(0,Number(offset||0));limit=Math.min(10,Math.max(1,Number(limit||8)));const cid=collectionId(eventId);const r=await fetch(`${SB}/rest/v1/photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&select=id,secure_url,original_filename&order=created_at.asc&offset=${offset}&limit=${limit}`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}});const photos=await r.json();if(!r.ok)throw new Error(photos?.message||'Falha ao carregar fotos.');let indexedPhotos=0,indexedFaces=0,failed=0;const failures:any[]=[];for(const p of photos){try{const x=await indexPhoto(eventId,cid,p);indexedPhotos++;indexedFaces+=x.faces}catch(e:any){failed++;failures.push({photo_id:p.id,name:p.original_filename,error:e?.message||String(e)});await fetch(`${SB}/rest/v1/photos?id=eq.${p.id}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'failed'})})}}const nextOffset=offset+photos.length;const total=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&select=id`);const done=nextOffset>=total;const faceTotal=await exactCount(`face_index?event_id=eq.${encodeURIComponent(eventId)}&select=id`);const patch={status:done?'ready':'indexing',indexed_photos:nextOffset,indexed_faces:faceTotal,last_error:failed?JSON.stringify(failures).slice(0,4000):null,indexed_at:done?new Date().toISOString():null,updated_at:new Date().toISOString()};await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(eventId)}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify(patch)});return j({ok:true,mode:'full',offset,next_offset:nextOffset,total_photos:total,processed:photos.length,indexed_photos:indexedPhotos,indexed_faces:indexedFaces,total_faces:faceTotal,failed,failures,done})}

async function doIndexPendingBatch(eventId:string,limit:number){if(!awsReady())return j({error:'AWS_REKOGNITION_NOT_CONFIGURED'},503);if(!eventId)return j({error:'event_id é obrigatório.'},400);limit=Math.min(10,Math.max(1,Number(limit||8)));const cid=collectionId(eventId);if(!await collectionExists(cid))return j({error:'Coleção facial não encontrada. Execute a preparação novamente.',needs_full_rebuild:true},409);const r=await fetch(`${SB}/rest/v1/photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.pending&select=id,secure_url,original_filename&order=created_at.asc&limit=${limit}`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}}),photos=await r.json();if(!r.ok)throw new Error(photos?.message||'Falha ao carregar fotos pendentes.');let indexedPhotos=0,indexedFaces=0,failed=0;const failures:any[]=[];for(const p of photos){try{const x=await indexPhoto(eventId,cid,p);indexedPhotos++;indexedFaces+=x.faces}catch(e:any){failed++;failures.push({photo_id:p.id,name:p.original_filename,error:e?.message||String(e)});await fetch(`${SB}/rest/v1/photos?id=eq.${p.id}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({face_index_status:'failed'})})}}const pending=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.pending&select=id`);const indexedTotal=await exactCount(`photos?event_id=eq.${encodeURIComponent(eventId)}&deleted_at=is.null&status=eq.published&face_index_status=eq.indexed&select=id`);const faceTotal=await exactCount(`face_index?event_id=eq.${encodeURIComponent(eventId)}&select=id`);const done=pending===0;await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(eventId)}`,{method:'PATCH',headers:svcHeaders(),body:JSON.stringify({status:done?'ready':'indexing',indexed_photos:indexedTotal,indexed_faces:faceTotal,last_error:failed?JSON.stringify(failures).slice(0,4000):null,indexed_at:done?new Date().toISOString():null,updated_at:new Date().toISOString()})});return j({ok:true,mode:'incremental',processed:photos.length,indexed_photos:indexedPhotos,indexed_faces:indexedFaces,total_faces:faceTotal,remaining:pending,indexed_total:indexedTotal,failed,failures,done})}

async function search(body:any){if(!awsReady())return j({error:'AWS_REKOGNITION_NOT_CONFIGURED'},503);if(body.consent!==true)return j({error:'CONSENT_REQUIRED'},400);const slug=String(body.event_slug||''),base64=String(body.image_base64||'');if(!slug||!base64)return j({error:'Evento e selfie são obrigatórios.'},400);const er=await fetch(`${SB}/rest/v1/events?slug=eq.${encodeURIComponent(slug)}&status=eq.published&face_search_enabled=eq.true&select=id,title`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}});const evs=await er.json();if(!er.ok||!evs?.[0])return j({error:'Busca facial indisponível para este evento.'},404);const ev=evs[0];const colR=await fetch(`${SB}/rest/v1/face_collections?event_id=eq.${encodeURIComponent(ev.id)}&status=eq.ready&select=collection_id`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}});const cols=await colR.json();if(!colR.ok||!cols?.[0])return j({error:'Índice facial ainda não está pronto.'},409);const clean=base64.replace(/^data:image\/(jpeg|jpg|png);base64,/i,'');let bytes:Uint8Array;try{bytes=Uint8Array.from(atob(clean),c=>c.charCodeAt(0))}catch{return j({error:'Imagem inválida.'},400)}if(bytes.byteLength>5*1024*1024)return j({error:'Selfie acima de 5 MB.'},400);const rek=client();let out;try{out=await rek.send(new SearchFacesByImageCommand({CollectionId:cols[0].collection_id,Image:{Bytes:bytes},FaceMatchThreshold:85,MaxFaces:500,QualityFilter:'AUTO'}))}catch(e:any){if(e?.name==='InvalidParameterException')return j({error:'Não consegui detectar um rosto nítido. Tente outra selfie.'},422);throw e}const byPhoto=new Map<string,number>();for(const m of out.FaceMatches||[]){const pid=m.Face?.ExternalImageId;if(pid)byPhoto.set(pid,Math.max(byPhoto.get(pid)||0,Number(m.Similarity||0)))}const ids=[...byPhoto.keys()];let photos:any[]=[];if(ids.length){const expr=`(${ids.join(',')})`;const pr=await fetch(`${SB}/rest/v1/photos?id=in.${encodeURIComponent(expr)}&deleted_at=is.null&status=eq.published&select=id,secure_url,original_filename`,{headers:{apikey:SERVICE,Authorization:`Bearer ${SERVICE}`}});if(pr.ok)photos=await pr.json()}photos=photos.map(p=>({...p,similarity:byPhoto.get(p.id)||0})).sort((a,b)=>b.similarity-a.similarity);await fetch(`${SB}/rest/v1/face_search_consents`,{method:'POST',headers:svcHeaders(),body:JSON.stringify({event_id:ev.id,consent_version:'v1',consent_text:'Autorizo o uso temporário da minha selfie exclusivamente para localizar minhas fotos neste evento. A selfie não é armazenada.'})});return j({ok:true,event:{id:ev.id,title:ev.title},matches:photos.length,photos})}

Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method==='GET')return j({ok:true,provider:'aws_rekognition',region:AWS_REGION,configured:awsReady(),incremental_indexing:true});if(req.method!=='POST')return j({error:'Método não suportado.'},405);try{const body=await req.json();const action=String(body.action||'');if(action==='status')return j({ok:true,provider:'aws_rekognition',region:AWS_REGION,configured:awsReady(),incremental_indexing:true});if(action==='validate'){if(!awsReady())return j({ok:false,configured:false},503);await client().send(new ListCollectionsCommand({MaxResults:1}));return j({ok:true,configured:true,credentials_valid:true,region:AWS_REGION});}if(action==='prepare_index'){await requireAdmin(req);return await doPrepareIndex(String(body.event_id||''));}if(action==='index_batch'){await requireAdmin(req);return await doIndexBatch(String(body.event_id||''),Number(body.offset||0),Number(body.limit||8));}if(action==='prepare_incremental'){await requireAdmin(req);return await doPrepareIncremental(String(body.event_id||''));}if(action==='index_pending_batch'){await requireAdmin(req);return await doIndexPendingBatch(String(body.event_id||''),Number(body.limit||8));}if(action==='search')return await search(body);return j({error:'Ação inválida.'},400)}catch(e:any){console.error(e);return j({error:e?.message||'Erro inesperado.'},500)}});
