'use client';

import {useEffect,useMemo,useState} from 'react';
import JSZip from 'jszip';
import {SB,KEY,adminHeaders,session} from '../../../../../lib/sb';

type Photo={id:string;secure_url:string;original_filename:string|null;source_type:string;face_index_status:string};
type DriveFile={id:string;name:string;mime_type?:string;size?:number;thumbnail_url?:string};
type IcloudFile={id:string;name:string;size?:number|null;width?:number|null;height?:number|null;thumbnail_url?:string|null};
type ZipSnapshot={name:string;size:number;data:ArrayBuffer};
type FailedZip={file:File;error:string};
type ImportJob={id:string;source_type:string;source_name:string|null;status:string;total_items:number;processed_items:number;imported_items:number;skipped_items:number;failed_items:number;error_message:string|null;created_at:string;updated_at:string;completed_at:string|null};

const IMAGE_RE=/\.(jpe?g|png|webp|heic|heif|gif|avif)$/i;
const MODERN_ICLOUD_RE=/^https:\/\/(?:share\.)?icloud\.com\/photos\/[A-Za-z0-9_-]+/i;
const MODERN_ICLOUD_WWW_RE=/^https:\/\/www\.icloud\.com\/photos\/#/i;
const ACTIVE_JOB=new Set(['pending','discovering','ready','processing','needs_worker']);
const yieldUi=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
function isImportableZipEntry(name:string){const normalized=String(name||'').replace(/^\/+/,''),base=normalized.split('/').pop()||'';return !normalized.startsWith('__MACOSX/')&&!base.startsWith('._')&&IMAGE_RE.test(base)}

export default function Fotos({params}:{params:{slug:string}}){
 const [event,setEvent]=useState<any>(null),[photos,setPhotos]=useState<Photo[]>([]),[files,setFiles]=useState<File[]>([]),[uploading,setUploading]=useState(false),[msg,setMsg]=useState('');
 const [drive,setDrive]=useState(''),[driveFiles,setDriveFiles]=useState<DriveFile[]>([]),[selectedDrive,setSelectedDrive]=useState<string[]>([]),[driveBusy,setDriveBusy]=useState(false);
 const [selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState(''),[indexing,setIndexing]=useState(false),[progress,setProgress]=useState('');
 const [zipFiles,setZipFiles]=useState<ZipSnapshot[]>([]),[zipBusy,setZipBusy]=useState(false),[zipFailed,setZipFailed]=useState<FailedZip[]>([]);
 const [icloud,setIcloud]=useState(''),[icloudFiles,setIcloudFiles]=useState<IcloudFile[]>([]),[selectedIcloud,setSelectedIcloud]=useState<string[]>([]),[icloudBusy,setIcloudBusy]=useState(false);
 const [importJobs,setImportJobs]=useState<ImportJob[]>([]),[jobsBusy,setJobsBusy]=useState(false);
 const hasActiveJobs=importJobs.some(j=>ACTIVE_JOB.has(j.status));

 async function guard(){const s=await session();if(!s?.access_token){location.href='/admin/login';return null}return s}
 async function loadPhotos(eventId:string){const pr=await fetch(`${SB}/rest/v1/photos?event_id=eq.${eventId}&deleted_at=is.null&select=id,secure_url,original_filename,source_type,face_index_status&order=created_at.desc`,{headers:await adminHeaders(false)});if(pr.ok)setPhotos(await pr.json())}
 async function refreshImportJobs(eventId?:string){const id=eventId||event?.id;if(!id)return;const s=await session();if(!s?.access_token)return;const r=await fetch(`${SB}/functions/v1/media-import?event_id=${encodeURIComponent(id)}`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});if(r.ok){const d=await r.json();setImportJobs(d.jobs||[])}}
 async function load(){if(!(await guard()))return;const er=await fetch(`${SB}/rest/v1/events?slug=eq.${encodeURIComponent(params.slug)}&select=*`,{headers:await adminHeaders(false)});const es=await er.json();if(!er.ok||!es?.[0]){setMsg('Evento não encontrado.');return}setEvent(es[0]);await Promise.all([loadPhotos(es[0].id),refreshImportJobs(es[0].id)])}
 useEffect(()=>{load()},[params.slug]);
 useEffect(()=>{if(!event?.id||!hasActiveJobs)return;const id=setInterval(async()=>{await refreshImportJobs(event.id);await loadPhotos(event.id)},3000);return()=>clearInterval(id)},[event?.id,hasActiveJobs]);
 const shown=useMemo(()=>photos.filter(p=>(p.original_filename||'').toLowerCase().includes(filter.toLowerCase())),[photos,filter]);

 async function uploadOneFile(f:File,sourceType='upload'){if(!event)throw new Error('Evento não carregado.');const fd=new FormData();fd.append('file',f);fd.append('upload_preset','semeando_memorias');fd.append('folder',`semeando-memorias/eventos/${event.slug}`);const cr=await fetch('https://api.cloudinary.com/v1_1/to3hnwdl/image/upload',{method:'POST',body:fd});const c=await cr.json();if(!cr.ok)throw new Error(c?.error?.message||`Erro em ${f.name}`);const row={event_id:event.id,cloudinary_asset_id:c.asset_id,public_id:c.public_id,secure_url:c.secure_url,width:c.width||null,height:c.height||null,bytes:c.bytes||null,format:c.format||null,original_filename:f.name,status:'published',source_type:sourceType};const sr=await fetch(`${SB}/rest/v1/photos`,{method:'POST',headers:{...await adminHeaders(),Prefer:'return=representation'},body:JSON.stringify(row)});if(!sr.ok)throw new Error((await sr.json())?.message||'Falha ao registrar foto.')}
 async function upload(){if(!event||!files.length)return;setUploading(true);setMsg('');let ok=0,failed=0;try{for(let i=0;i<files.length;i++){setProgress(`${i+1} de ${files.length} fotos enviadas`);try{await uploadOneFile(files[i]);ok++}catch{failed++}}setFiles([]);setMsg(`${ok} foto(s) enviada(s)${failed?`, ${failed} falha(s)`:''}.`);await loadPhotos(event.id)}finally{setProgress('');setUploading(false)}}

 // iOS/iCloud Drive may revoke the picker-backed File handle after onChange.
 // Copy the bytes immediately while the permission is still valid.
 async function selectZip(list:FileList|null){const picked=Array.from(list||[]);setZipFiles([]);setZipFailed([]);if(!picked.length)return;setZipBusy(true);setMsg('');try{const owned:ZipSnapshot[]=[];for(let i=0;i<picked.length;i++){const f=picked[i];setProgress(`Preparando ZIP ${i+1} de ${picked.length}: ${f.name}`);try{owned.push({name:f.name,size:f.size,data:await f.arrayBuffer()})}catch(e:any){throw new Error(`Não foi possível copiar ${f.name} enquanto o acesso ao arquivo estava ativo. ${e?.message||''}`)}}setZipFiles(owned);setMsg(`${owned.length} ZIP(s) pronto(s) para importar.`)}catch(e:any){setMsg(e?.message||'Não foi possível ler o ZIP. Se ele estiver no iCloud Drive, salve-o em Downloads/Arquivos e selecione novamente.')}finally{setProgress('');setZipBusy(false)}}
 async function importZip(){if(!event||!zipFiles.length)return;setZipBusy(true);setMsg('');setZipFailed([]);try{let total=0,done=0,ok=0,failed=0;const opened:{name:string;entries:any[]}[]=[];for(const snap of zipFiles){setProgress(`Lendo ${snap.name}...`);const zip=await JSZip.loadAsync(snap.data);const entries=Object.values(zip.files).filter((e:any)=>!e.dir&&isImportableZipEntry(e.name));opened.push({name:snap.name,entries});total+=entries.length}for(const group of opened){for(const e of group.entries){done++;setProgress(`${done} de ${total} fotos enviadas`);try{const blob=await (e as any).async('blob');const name=(e as any).name.split('/').pop()||`foto-${done}`;const file=new File([blob],name,{type:blob.type||'application/octet-stream'});try{await uploadOneFile(file,'zip');ok++}catch(err:any){failed++;setZipFailed(v=>[...v,{file,error:err?.message||'Falha no upload'}])}}catch(err:any){failed++;setMsg(`Falha ao extrair ${(e as any).name}: ${err?.message||'erro desconhecido'}`)}if(done%5===0)await yieldUi()}}setZipFiles([]);setMsg(`ZIP concluído: ${ok} importada(s)${failed?`, ${failed} falha(s)`:''}${total===0?' — nenhuma imagem compatível encontrada':''}.`);await loadPhotos(event.id)}catch(e:any){setMsg(e?.message||'Não foi possível ler o ZIP.')}finally{setProgress('');setZipBusy(false)}}
 async function retryZipFailures(){if(!zipFailed.length)return;setZipBusy(true);setMsg('');const current=[...zipFailed],still:FailedZip[]=[];let ok=0;try{for(let i=0;i<current.length;i++){setProgress(`${i+1} de ${current.length} falhas sendo repetidas`);try{await uploadOneFile(current[i].file,'zip');ok++}catch(e:any){still.push({file:current[i].file,error:e?.message||'Falha no upload'})}}setZipFailed(still);setMsg(`${ok} falha(s) recuperada(s)${still.length?`; ${still.length} ainda pendente(s)`:''}.`);await loadPhotos(event.id)}finally{setProgress('');setZipBusy(false)}}

 function isModernIcloud(link:string){return MODERN_ICLOUD_RE.test(link)||MODERN_ICLOUD_WWW_RE.test(link)}
 async function startModernIcloud(){if(!event)return;const link=icloud.trim(),s=await guard();if(!s)return;setJobsBusy(true);setIcloudBusy(true);setMsg('');try{const r=await fetch(`${SB}/functions/v1/media-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'create_icloud_job',event_id:event.id,link})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível iniciar a importação do iCloud.');setMsg('Importação do iCloud iniciada. A descoberta e o envio continuam no backend; você pode sair desta página e acompanhar o status ao voltar.');await refreshImportJobs(event.id)}catch(e:any){setMsg(e.message)}finally{setJobsBusy(false);setIcloudBusy(false)}}
 async function previewIcloud(){const link=icloud.trim();if(!link)return;if(isModernIcloud(link)){setIcloudFiles([]);setSelectedIcloud([]);setMsg('Este é um link moderno do iCloud Fotos. Ele será analisado pelo worker seguro no backend ao clicar em “Importar todas as fotos”. O progresso ficará salvo nesta página.');return}setIcloudBusy(true);setMsg('');setIcloudFiles([]);setSelectedIcloud([]);try{const r=await fetch(`${SB}/functions/v1/icloud-import?link=${encodeURIComponent(link)}`,{headers:{apikey:KEY}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível ler o link do iCloud.');setIcloudFiles(d.files||[]);setSelectedIcloud((d.files||[]).map((x:IcloudFile)=>x.id));setMsg(`${d.count||0} imagem(ns) encontrada(s) no iCloud${d.album_name?` • ${d.album_name}`:''}.`)}catch(e:any){setMsg(e.message)}finally{setIcloudBusy(false)}}
 async function importIcloud(ids?:string[]){if(!event)return;const link=icloud.trim();if(!link)return;if(isModernIcloud(link)){await startModernIcloud();return}setIcloudBusy(true);setMsg('');try{let chosen=ids||selectedIcloud;if(!chosen.length){const r=await fetch(`${SB}/functions/v1/icloud-import?link=${encodeURIComponent(link)}`,{headers:{apikey:KEY}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível ler o link do iCloud.');setIcloudFiles(d.files||[]);chosen=(d.files||[]).map((x:IcloudFile)=>x.id);setSelectedIcloud(chosen)}if(!chosen.length)throw new Error('Nenhuma imagem foi encontrada nesse link do iCloud.');const s=await guard();if(!s)return;let imported=0,failed=0,skipped=0;for(let i=0;i<chosen.length;i+=20){setProgress(`iCloud: ${Math.min(i+20,chosen.length)} de ${chosen.length} processadas`);const r=await fetch(`${SB}/functions/v1/icloud-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({link,event_id:event.id,photo_guids:chosen.slice(i,i+20)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha na importação do iCloud.');imported+=d.imported||0;failed+=d.failed||0;skipped+=d.skipped||0}setMsg(`iCloud concluído: ${imported} nova(s) foto(s)${skipped?`, ${skipped} já existente(s)`:''}${failed?`, ${failed} falha(s)`:''}.`);await loadPhotos(event.id)}catch(e:any){setMsg(e.message)}finally{setProgress('');setIcloudBusy(false)}}
 async function retryImportJob(jobId:string){const s=await guard();if(!s)return;setJobsBusy(true);try{const r=await fetch(`${SB}/functions/v1/media-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'retry_failed',job_id:jobId})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível repetir as falhas.');setMsg('As fotos que falharam foram reenfileiradas.');await refreshImportJobs(event?.id)}catch(e:any){setMsg(e.message)}finally{setJobsBusy(false)}}

 async function listDrive(){if(!drive.trim())return;setDriveBusy(true);setMsg('');try{const r=await fetch(`${SB}/functions/v1/drive-import?folder=${encodeURIComponent(drive.trim())}`,{headers:{apikey:KEY}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível listar a pasta.');setDriveFiles(d.files||[]);setSelectedDrive((d.files||[]).map((x:DriveFile)=>x.id));setMsg(`${d.count||0} imagem(ns) encontrada(s) no Drive.`)}catch(e:any){setMsg(e.message)}finally{setDriveBusy(false)}}
 async function importDrive(){if(!event||!selectedDrive.length)return;setDriveBusy(true);setMsg('');try{const s=await guard();if(!s)return;const chosen=driveFiles.filter(f=>selectedDrive.includes(f.id));let imported=0,failed=0;for(let i=0;i<chosen.length;i+=100){const r=await fetch(`${SB}/functions/v1/drive-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({folder_url:drive,event_id:event.id,files:chosen.slice(i,i+100)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha na importação.');imported+=d.imported||0;failed+=d.failed||0}setMsg(`Importação concluída: ${imported} nova(s) foto(s)${failed?`, ${failed} falha(s)`:''}.`);await loadPhotos(event.id)}catch(e:any){setMsg(e.message)}finally{setDriveBusy(false)}}

 async function softDelete(ids:string[]){if(!ids.length||!confirm(`Excluir ${ids.length} foto(s) da galeria?`))return;const r=await fetch(`${SB}/rest/v1/photos?id=in.(${ids.join(',')})`,{method:'PATCH',headers:await adminHeaders(),body:JSON.stringify({deleted_at:new Date().toISOString()})});if(r.ok){setSelected([]);setMsg('Fotos removidas da galeria.');loadPhotos(event.id)}else setMsg('Não foi possível remover as fotos.')}
 async function indexFaces(){if(!event)return;setIndexing(true);setMsg('');setProgress('Verificando fotos novas para reconhecimento...');try{const s=await guard();if(!s)return;const h={apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'};let r=await fetch(`${SB}/functions/v1/face-recognition`,{method:'POST',headers:h,body:JSON.stringify({action:'prepare_incremental',event_id:event.id})});let d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao preparar índice.');const mode=d.mode||'full',total=Number(d.total_photos||0);if(d.done||total===0){setProgress('');setMsg(`Reconhecimento já está atualizado. ${d.total_faces||0} rosto(s) no índice.`);await loadPhotos(event.id);return}if(mode==='incremental'){let processed=0;while(true){setProgress(`Indexando novas fotos: ${Math.min(processed+1,total)} a ${Math.min(processed+8,total)} de ${total}...`);r=await fetch(`${SB}/functions/v1/face-recognition`,{method:'POST',headers:h,body:JSON.stringify({action:'index_pending_batch',event_id:event.id,limit:8})});d=await r.json();if(!r.ok)throw new Error(d.error||'Falha no reconhecimento incremental.');processed+=Number(d.processed||0);if(d.done)break}}else{let offset=0;while(true){setProgress(`Reconstruindo índice: ${Math.min(offset+1,total)} a ${Math.min(offset+8,total)} de ${total}...`);r=await fetch(`${SB}/functions/v1/face-recognition`,{method:'POST',headers:h,body:JSON.stringify({action:'index_batch',event_id:event.id,offset,limit:8})});d=await r.json();if(!r.ok)throw new Error(d.error||'Falha no reconhecimento.');offset=d.next_offset||offset+8;if(d.done)break}}setProgress('');setMsg(`Reconhecimento atualizado. ${d.total_faces||0} rosto(s) no índice.`);await loadPhotos(event.id)}catch(e:any){setProgress('');setMsg(e.message)}finally{setIndexing(false)}}
 async function disableFace(){if(!event)return;const r=await fetch(`${SB}/rest/v1/events?id=eq.${event.id}`,{method:'PATCH',headers:await adminHeaders(),body:JSON.stringify({face_search_enabled:false})});if(r.ok){setMsg('Busca facial desativada para este evento.');load()}}
 function jobPercent(j:ImportJob){return j.total_items>0?Math.min(100,Math.round((j.processed_items/j.total_items)*100)):0}

 return <main className="wrap photo-admin">
  <div className="top"><div><a className="event-back-link" href="/admin">← Voltar ao painel</a><span className="eyebrow">Gerenciar fotos</span><h1>{event?.title||'Evento'}</h1><p className="muted">Envie fotos, importe ZIP, Google Drive e use links do iCloud para trazer grandes lotes de imagens.</p></div><a className="btn alt" href={`/evento/${params.slug}`}>Ver galeria</a></div>
  {msg&&<p className="notice">{msg}</p>}{progress&&<p className="notice">{progress}</p>}

  <section className="panel"><div className="section-title"><div><span className="eyebrow">Upload local</span><h2>Enviar fotos</h2></div><span className="muted small">JPG, PNG, HEIC e outros formatos de imagem</span></div><div className="upload"><input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length>0&&<div className="actions"><strong>{files.length} arquivo(s) selecionado(s)</strong><button className="btn" disabled={uploading} onClick={upload}>{uploading?'Enviando...':'Enviar fotos'}</button><button className="btn alt" onClick={()=>setFiles([])}>Limpar</button></div>}</div></section>

  <section className="panel"><div className="section-title"><div><span className="eyebrow">Arquivo compactado</span><h2>Importar ZIP de fotos</h2></div><span className="muted small">O ZIP é copiado no momento da seleção para evitar perda de permissão do iCloud Drive</span></div><div className="upload"><input type="file" accept=".zip,application/zip,application/x-zip-compressed" multiple onChange={e=>selectZip(e.target.files)}/>{zipFiles.length>0&&<div className="actions"><strong>{zipFiles.length} ZIP(s) pronto(s)</strong><button className="btn" disabled={zipBusy} onClick={importZip}>{zipBusy?'Importando ZIP...':'Ler ZIP e importar fotos'}</button><button className="btn alt" onClick={()=>setZipFiles([])}>Limpar</button></div>}</div>{zipFailed.length>0&&<div className="notice" style={{marginTop:12}}><strong>{zipFailed.length} foto(s) falharam.</strong> <button className="btn alt" disabled={zipBusy} onClick={retryZipFailures}>Tentar novamente só as falhas</button></div>}<p className="muted small">Arquivos que não são imagens e metadados ocultos do macOS são ignorados. JPG/JPEG, PNG, WEBP, HEIC/HEIF, GIF e AVIF são aceitos pelo extrator; o Cloudinary valida o formato final.</p></section>

  <section className="panel"><span className="eyebrow">iCloud Fotos</span><h2>Importar por link do iCloud</h2><p className="muted">Cole um link público do app Fotos. Links modernos são descobertos por um navegador seguro no backend e ficam registrados como um job persistente.</p><div className="toolbar"><input className="growInput" value={icloud} onChange={e=>{setIcloud(e.target.value);setIcloudFiles([]);setSelectedIcloud([])}} placeholder="https://share.icloud.com/photos/..."/><button className="btn" disabled={icloudBusy||jobsBusy||!icloud.trim()} onClick={()=>importIcloud()}>{icloudBusy||jobsBusy?'Iniciando...':'Importar todas as fotos'}</button><button className="btn alt" disabled={icloudBusy||!icloud.trim()} onClick={previewIcloud}>Ver antes</button></div>{icloudFiles.length>0&&<><div className="driveActions actions"><button className="btn alt" onClick={()=>setSelectedIcloud(icloudFiles.map(f=>f.id))}>Selecionar todos</button><button className="btn alt" onClick={()=>setSelectedIcloud([])}>Limpar seleção</button><button className="btn" disabled={icloudBusy||!selectedIcloud.length} onClick={()=>importIcloud(selectedIcloud)}>Importar {selectedIcloud.length} selecionada(s)</button></div><div className="driveList">{icloudFiles.map(f=><label className="driveItem" key={f.id}><input type="checkbox" checked={selectedIcloud.includes(f.id)} onChange={e=>setSelectedIcloud(e.target.checked?[...selectedIcloud,f.id]:selectedIcloud.filter(x=>x!==f.id))}/><span>{f.name}</span></label>)}</div></>}
   {importJobs.filter(j=>j.source_type==='icloud').length>0&&<div style={{marginTop:16}}><div className="section-title"><div><strong>Importações recentes</strong><p className="muted small">O status permanece salvo mesmo depois de fechar a página.</p></div><button className="btn alt" disabled={jobsBusy} onClick={()=>refreshImportJobs(event?.id)}>Atualizar</button></div><div className="driveList">{importJobs.filter(j=>j.source_type==='icloud').map(j=><div className="driveItem" key={j.id} style={{display:'block'}}><div className="section-title"><strong>{j.source_name||'iCloud Fotos'}</strong><span className="muted small">{j.status==='discovering'?'Localizando fotos...':j.status==='processing'?'Processando...':j.status==='completed'?'Concluído':j.status==='partial'?'Concluído com falhas':j.status==='failed'?'Falhou':j.status}</span></div><div className="muted small">{j.total_items>0?`${j.processed_items} / ${j.total_items} • ${jobPercent(j)}%`:'Aguardando contagem das fotos'}{j.imported_items?` • ${j.imported_items} importada(s)`:''}{j.failed_items?` • ${j.failed_items} falha(s)`:''}</div>{j.total_items>0&&<progress value={j.processed_items} max={j.total_items} style={{width:'100%',marginTop:8}}/>}{j.error_message&&<p className="muted small">{j.error_message}</p>}{j.failed_items>0&&<button className="btn alt" disabled={jobsBusy} onClick={()=>retryImportJob(j.id)}>Tentar novamente somente falhas</button>}</div>)}</div></div>}
   <div className="notice" style={{marginTop:12}}>O Semeando Memórias não envia chaves privadas ao navegador. O link do iCloud é processado pelo backend e as fotos concluídas entram no evento com reconhecimento facial pendente.</div>
  </section>

  <section className="panel"><span className="eyebrow">Google Drive</span><h2>Importar pasta</h2><div className="toolbar"><input className="growInput" value={drive} onChange={e=>setDrive(e.target.value)} placeholder="Cole o link da pasta do Google Drive"/><button className="btn" disabled={driveBusy} onClick={listDrive}>{driveBusy?'Aguarde...':'Verificar pasta'}</button></div>{driveFiles.length>0&&<><div className="driveActions actions"><button className="btn alt" onClick={()=>setSelectedDrive(driveFiles.map(f=>f.id))}>Selecionar todos</button><button className="btn alt" onClick={()=>setSelectedDrive([])}>Limpar seleção</button><button className="btn" disabled={driveBusy||!selectedDrive.length} onClick={importDrive}>Importar {selectedDrive.length} selecionada(s)</button></div><div className="driveList">{driveFiles.map(f=><label className="driveItem" key={f.id}><input type="checkbox" checked={selectedDrive.includes(f.id)} onChange={e=>setSelectedDrive(e.target.checked?[...selectedDrive,f.id]:selectedDrive.filter(x=>x!==f.id))}/><span>{f.name}</span></label>)}</div></>}</section>

  <section className="panel"><div className="section-title"><div><span className="eyebrow">Busca facial</span><h2>Reconhecimento</h2></div>{event?.face_search_enabled?<span className="face-ready">✓ Ativo</span>:<span className="muted">Desativado</span>}</div><p className="muted">Ao atualizar, o sistema prioriza somente fotos novas ou pendentes. A reconstrução completa fica reservada para quando a coleção facial não existir ou precisar ser recuperada.</p><div className="actions"><button className="btn" disabled={indexing||!photos.length} onClick={indexFaces}>{indexing?'Indexando...':event?.face_search_enabled?'Atualizar reconhecimento':'Ativar reconhecimento'}</button>{event?.face_search_enabled&&<button className="btn alt" onClick={disableFace}>Desativar</button>}</div></section>

  <section className="panel"><div className="section-title"><div><span className="eyebrow">Biblioteca</span><h2>{photos.length} foto(s)</h2></div><div className="actions"><input className="filter-input" placeholder="Filtrar por nome" value={filter} onChange={e=>setFilter(e.target.value)}/>{selected.length>0&&<button className="btn danger" onClick={()=>softDelete(selected)}>Excluir {selected.length}</button>}</div></div><div className="grid">{shown.map(p=><div className={`photo ${selected.includes(p.id)?'selected':''}`} style={{backgroundImage:`url(${p.secure_url})`}} key={p.id} onClick={()=>setSelected(selected.includes(p.id)?selected.filter(x=>x!==p.id):[...selected,p.id])}><input className="photo-check" type="checkbox" checked={selected.includes(p.id)} readOnly/><button className="photo-delete" onClick={e=>{e.stopPropagation();softDelete([p.id])}}>×</button><span>{p.original_filename||'Foto'}</span></div>)}</div></section>
 </main>
}
