'use client';
import {useEffect,useMemo,useState} from 'react';
import JSZip from 'jszip';
import heic2any from 'heic2any';
import {SB,KEY,adminHeaders,session} from '../../../../../lib/sb';

type Photo={id:string;secure_url:string;original_filename:string|null;source_type:string;face_index_status:string};
type DriveFile={id:string;name:string;mime_type?:string;size?:number;thumbnail_url?:string};
type ZipItem={name:string;data:ArrayBuffer};
type ICloudPhoto={guid:string;name:string;size?:number;width?:number;height?:number;checksum?:string};
const storage=(b:any)=>{const n=Number(b||0);return n>=1073741824?`${(n/1073741824).toFixed(2)} GB`:`${(n/1048576).toFixed(1)} MB`};
const CLOUDINARY_MAX=10*1024*1024;
const UPLOAD_TARGET=Math.floor(9.4*1024*1024);
const mb=(n:number)=>(n/1048576).toFixed(1);

async function toCanvasBlob(source:Blob,maxSide:number,quality:number){
 const url=URL.createObjectURL(source);try{
  const img=await new Promise<HTMLImageElement>((resolve,reject)=>{const x=new Image();x.onload=()=>resolve(x);x.onerror=()=>reject(new Error('Não foi possível abrir a imagem para otimização.'));x.src=url});
  const scale=Math.min(1,maxSide/Math.max(img.naturalWidth,img.naturalHeight));
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));
  const ctx=canvas.getContext('2d');if(!ctx)throw new Error('O navegador não conseguiu preparar a imagem.');ctx.drawImage(img,0,0,canvas.width,canvas.height);
  const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',quality));if(!blob)throw new Error('Não foi possível compactar a imagem.');return blob;
 }finally{URL.revokeObjectURL(url)}
}
async function prepareLargeImage(file:File,onProgress?:(t:string)=>void){
 if(file.size<CLOUDINARY_MAX)return{file,optimized:false,originalSize:file.size};
 onProgress?.(`Otimizando ${file.name} (${mb(file.size)} MB) para o limite de upload...`);
 let source:Blob=file;
 const heic=/\.(heic|heif)$/i.test(file.name)||/heic|heif/i.test(file.type);
 if(heic){const converted=await heic2any({blob:file,toType:'image/jpeg',quality:.96});source=Array.isArray(converted)?converted[0]:converted}
 let maxSide=7000,quality=.94,best:Blob|null=null;
 for(let i=0;i<10;i++){
  const out=await toCanvasBlob(source,maxSide,quality);best=out;if(out.size<=UPLOAD_TARGET)break;
  if(quality>.78)quality-=.04;else maxSide=Math.round(maxSide*.88);
 }
 if(!best||best.size>=CLOUDINARY_MAX)throw new Error(`${file.name} tem ${mb(file.size)} MB e não foi possível reduzi-la automaticamente para menos de 10 MB.`);
 const base=file.name.replace(/\.[^.]+$/,'');
 return{file:new File([best],`${base}.jpg`,{type:'image/jpeg',lastModified:file.lastModified}),optimized:true,originalSize:file.size};
}

export default function Fotos({params}:{params:{slug:string}}){
 const [event,setEvent]=useState<any>(null),[photos,setPhotos]=useState<Photo[]>([]),[files,setFiles]=useState<File[]>([]),[uploading,setUploading]=useState(false),[msg,setMsg]=useState(''),[drive,setDrive]=useState(''),[driveFiles,setDriveFiles]=useState<DriveFile[]>([]),[selectedDrive,setSelectedDrive]=useState<string[]>([]),[driveBusy,setDriveBusy]=useState(false),[selected,setSelected]=useState<string[]>([]),[filter,setFilter]=useState(''),[indexing,setIndexing]=useState(false),[progress,setProgress]=useState(''),[zipFiles,setZipFiles]=useState<ZipItem[]>([]),[zipBusy,setZipBusy]=useState(false),[icloud,setIcloud]=useState(''),[icloudPhotos,setIcloudPhotos]=useState<ICloudPhoto[]>([]),[selectedIcloud,setSelectedIcloud]=useState<string[]>([]),[icloudBusy,setIcloudBusy]=useState(false),[entitlements,setEntitlements]=useState<any>(null);

 async function guard(){const s=await session();if(!s?.access_token){location.href='/admin/login';return null}return s}
 async function getEntitlements(eventId:string,count=0,bytes=0){const s=await guard();if(!s)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/functions/v1/plan-entitlements`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,photo_count:count,bytes})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível validar o plano.');return d}
 async function ensureQuota(count:number,bytes:number){if(!event)return null;const d=await getEntitlements(event.id,count,bytes);setEntitlements(d);if(!d.allowed?.upload_photos){const p=d.plan?.name||'atual',rp=d.remaining?.photos,rs=d.remaining?.storage_bytes;const reason=rp!==null&&Number(rp)<count?`restam ${Math.max(0,Number(rp||0))} foto(s)`:(rs!==null?`restam ${storage(rs)} de armazenamento`:'cota esgotada');throw new Error(`Limite do plano ${p} atingido: ${reason}.`)}return d}
 async function load(){const s=await guard();if(!s)return;const er=await fetch(`${SB}/rest/v1/events?slug=eq.${encodeURIComponent(params.slug)}&select=*`,{headers:await adminHeaders(false)});const es=await er.json();if(!er.ok||!es?.[0]){setMsg('Evento não encontrado.');return}setEvent(es[0]);const pr=await fetch(`${SB}/rest/v1/photos?event_id=eq.${es[0].id}&deleted_at=is.null&select=id,secure_url,original_filename,source_type,face_index_status&order=created_at.desc`,{headers:await adminHeaders(false)});if(pr.ok)setPhotos(await pr.json());try{setEntitlements(await getEntitlements(es[0].id))}catch{setEntitlements(null)}}
 useEffect(()=>{load()},[params.slug]);
 const shown=useMemo(()=>photos.filter(p=>(p.original_filename||'').toLowerCase().includes(filter.toLowerCase())),[photos,filter]);

 async function upload(){if(!event||!files.length)return;setUploading(true);setMsg('');setProgress('');let ok=0,optimized=0;try{await ensureQuota(files.length,0);for(let i=0;i<files.length;i++){setProgress(`Preparando foto ${i+1} de ${files.length}...`);const r=await uploadOneFile(files[i]);ok++;if(r)optimized++}setFiles([]);setProgress('');setMsg(`${ok} foto(s) enviada(s) com sucesso.${optimized?` ${optimized} arquivo(s) acima de 10 MB foram otimizados automaticamente em alta qualidade.`:''}`);await load()}catch(e:any){setProgress('');setMsg(e.message||'Erro no envio.')}finally{setUploading(false)}}
 async function uploadOneFile(original:File){if(!event)throw new Error('Evento não carregado.');const prepared=await prepareLargeImage(original,setProgress);const f=prepared.file;await ensureQuota(1,f.size);const fd=new FormData();fd.append('file',f);fd.append('upload_preset','semeando_memorias');fd.append('folder',`semeando-memorias/eventos/${event.slug}`);const cr=await fetch('https://api.cloudinary.com/v1_1/to3hnwdl/image/upload',{method:'POST',body:fd});const c=await cr.json();if(!cr.ok){const raw=String(c?.error?.message||'');if(/file size too large|maximum is/i.test(raw))throw new Error(`${original.name} ultrapassa o limite de 10 MB por imagem do armazenamento atual.`);throw new Error(raw||`Erro ao enviar ${original.name}`)}const row={event_id:event.id,cloudinary_asset_id:c.asset_id,public_id:c.public_id,secure_url:c.secure_url,width:c.width||null,height:c.height||null,bytes:c.bytes||null,format:c.format||null,original_filename:original.name,status:'published',source_type:'upload'};const sr=await fetch(`${SB}/rest/v1/photos`,{method:'POST',headers:{...await adminHeaders(),Prefer:'return=representation'},body:JSON.stringify(row)});if(!sr.ok){const d=await sr.json().catch(()=>({}));throw new Error(d?.details||d?.message||'Falha ao registrar foto.')}return prepared.optimized}

 async function selectZip(input:HTMLInputElement){const picked=Array.from(input.files||[]);if(!picked.length)return;setZipBusy(true);setMsg('');setProgress('Copiando o ZIP para memória para evitar perda de permissão do arquivo...');try{const items:ZipItem[]=[];for(let i=0;i<picked.length;i++){setProgress(`Preparando ZIP ${i+1} de ${picked.length}...`);items.push({name:picked[i].name,data:await picked[i].arrayBuffer()})}setZipFiles(items);setProgress('');setMsg(`${items.length} ZIP(s) pronto(s) para leitura.`)}catch(e:any){setZipFiles([]);setProgress('');setMsg(e?.message||'O navegador não conseguiu ler o ZIP selecionado. Tente selecionar o arquivo novamente.')}finally{input.value='';setZipBusy(false)}}
 async function importZip(){if(!event||!zipFiles.length)return;setZipBusy(true);setMsg('');setProgress('Lendo arquivo ZIP...');try{let total=0,ok=0,failed=0,optimized=0;for(const zipFile of zipFiles){const zip=await JSZip.loadAsync(zipFile.data);const entries=Object.values(zip.files).filter((e:any)=>!e.dir&&/\.(jpe?g|png|webp|heic|heif|gif|avif)$/i.test(e.name));total+=entries.length;for(let i=0;i<entries.length;i++){const e:any=entries[i];setProgress(`ZIP ${zipFile.name}: enviando ${i+1} de ${entries.length}...`);try{const blob=await e.async('blob');const name=e.name.split('/').pop()||`foto-${i+1}`;const f=new File([blob],name,{type:blob.type||'application/octet-stream'});if(await uploadOneFile(f))optimized++;ok++}catch{failed++}}}setZipFiles([]);setProgress('');setMsg(`ZIP concluído: ${ok} foto(s) importada(s)${optimized?`, ${optimized} otimizada(s) por exceder 10 MB`:''}${failed?`, ${failed} falha(s)`:''}${total===0?' — nenhuma imagem compatível encontrada.':''}.`);await load()}catch(e:any){setProgress('');setMsg(e?.message||'Não foi possível ler o ZIP. Se o arquivo estiver no iCloud/OneDrive, copie-o para uma pasta local do computador e selecione novamente.')}finally{setZipBusy(false)}}

 async function listIcloud(){const link=icloud.trim();if(!link)return;setIcloudBusy(true);setMsg('');setIcloudPhotos([]);setSelectedIcloud([]);try{const s=await guard();if(!s)return;const r=await fetch(`${SB}/functions/v1/icloud-import?link=${encodeURIComponent(link)}`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível ler o link do iCloud.');const found:ICloudPhoto[]=d.photos||[];setIcloudPhotos(found);setSelectedIcloud(found.map(x=>x.guid));setMsg(`${d.count||found.length} foto(s) encontrada(s) no iCloud${d.album?` • ${d.album}`:''}.`)}catch(e:any){setMsg(e.message)}finally{setIcloudBusy(false)}}
 async function importIcloud(){if(!event||!selectedIcloud.length)return;setIcloudBusy(true);setMsg('');try{const s=await guard();if(!s)return;const chosen=icloudPhotos.filter(p=>selectedIcloud.includes(p.guid));let imported=0,skipped=0,failed=0;for(let i=0;i<chosen.length;i+=25){setProgress(`iCloud: importando ${i+1} a ${Math.min(i+25,chosen.length)} de ${chosen.length}...`);const r=await fetch(`${SB}/functions/v1/icloud-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({link:icloud,event_id:event.id,guids:chosen.slice(i,i+25).map(x=>x.guid)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao importar do iCloud.');imported+=d.imported||0;skipped+=d.skipped||0;failed+=d.failed||0}setProgress('');setMsg(`iCloud concluído: ${imported} nova(s) foto(s)${skipped?`, ${skipped} já existente(s)`:''}${failed?`, ${failed} falha(s)`:''}.`);await load()}catch(e:any){setProgress('');setMsg(e.message)}finally{setIcloudBusy(false)}}

 async function listDrive(){if(!drive.trim())return;setDriveBusy(true);setMsg('');try{const r=await fetch(`${SB}/functions/v1/drive-import?folder=${encodeURIComponent(drive.trim())}`,{headers:{apikey:KEY}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível listar a pasta.');setDriveFiles(d.files||[]);setSelectedDrive((d.files||[]).map((x:DriveFile)=>x.id));setMsg(`${d.count||0} imagem(ns) encontrada(s) no Drive.`)}catch(e:any){setMsg(e.message)}finally{setDriveBusy(false)}}
 async function importDrive(){if(!event||!selectedDrive.length)return;setDriveBusy(true);setMsg('');try{const s=await guard();if(!s)return;const chosen=driveFiles.filter(f=>selectedDrive.includes(f.id));let imported=0,failed=0;for(let i=0;i<chosen.length;i+=100){const r=await fetch(`${SB}/functions/v1/drive-import`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({folder_url:drive,event_id:event.id,files:chosen.slice(i,i+100)})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha na importação.');imported+=d.imported||0;failed+=d.failed||0}setMsg(`Importação concluída: ${imported} nova(s) foto(s)${failed?`, ${failed} falha(s)`:''}.`);await load()}catch(e:any){setMsg(e.message)}finally{setDriveBusy(false)}}

 async function softDelete(ids:string[]){if(!ids.length||!confirm(`Excluir ${ids.length} foto(s) da galeria?`))return;const r=await fetch(`${SB}/rest/v1/photos?id=in.(${ids.join(',')})`,{method:'PATCH',headers:await adminHeaders(),body:JSON.stringify({deleted_at:new Date().toISOString()})});if(r.ok){setSelected([]);setMsg('Fotos removidas da galeria.');load()}else setMsg('Não foi possível remover as fotos.')}
 async function indexFaces(){if(!event)return;setIndexing(true);setMsg('');setProgress('Preparando reconhecimento facial...');try{if(entitlements?.plan&&!entitlements?.allowed?.face_search)throw new Error(`O reconhecimento facial não está disponível no plano ${entitlements.plan.name}.`);const s=await guard();if(!s)return;const h={apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'};let r=await fetch(`${SB}/functions/v1/face-recognition`,{method:'POST',headers:h,body:JSON.stringify({action:'prepare_index',event_id:event.id})});let d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao preparar índice.');let offset=0,total=d.total_photos||photos.length;while(true){setProgress(`Indexando fotos ${Math.min(offset+1,total)} a ${Math.min(offset+8,total)} de ${total}...`);r=await fetch(`${SB}/functions/v1/face-recognition`,{method:'POST',headers:h,body:JSON.stringify({action:'index_batch',event_id:event.id,offset,limit:8})});d=await r.json();if(!r.ok)throw new Error(d.error||'Falha no reconhecimento.');offset=d.next_offset||offset+8;if(d.done)break}setProgress('');setMsg(`Reconhecimento atualizado. ${d.total_faces||0} rosto(s) indexado(s).`);await load()}catch(e:any){setProgress('');setMsg(e.message)}finally{setIndexing(false)}}
 async function disableFace(){if(!event)return;const r=await fetch(`${SB}/rest/v1/events?id=eq.${event.id}`,{method:'PATCH',headers:await adminHeaders(),body:JSON.stringify({face_search_enabled:false})});if(r.ok){setMsg('Busca facial desativada para este evento.');load()}}

 return <main className="wrap photo-admin"><div className="top"><div><a className="event-back-link" href="/admin">← Voltar ao painel</a><span className="eyebrow">Gerenciar fotos</span><h1>{event?.title||'Evento'}</h1><p className="muted">Envie fotos, importe ZIP, Google Drive ou cole um link público do iCloud para trazer as imagens diretamente ao álbum.</p></div><a className="btn alt" href={`/evento/${params.slug}`}>Ver galeria</a></div>{msg&&<p className="notice">{msg}</p>}{progress&&<p className="notice">{progress}</p>}

 {entitlements&&<section className="panel"><div className="section-title"><div><span className="eyebrow">Plano e consumo</span><h2>{entitlements.plan?.name||'Operação interna'}</h2></div><span className={entitlements.allowed?.upload_photos?'face-ready':'status-off'}>{entitlements.allowed?.upload_photos?'✓ Upload liberado':'Limite atingido'}</span></div>{entitlements.plan?<div className="actions"><span className="muted small">Fotos: <b>{entitlements.usage?.photos||0}</b>{entitlements.plan.photo_limit!=null?` / ${entitlements.plan.photo_limit}`:' / ilimitado'}</span><span className="muted small">Armazenamento: <b>{storage(entitlements.usage?.storage_bytes)}</b>{entitlements.remaining?.storage_bytes!=null?` • ${storage(entitlements.remaining.storage_bytes)} restante`:''}</span><span className="muted small">Reconhecimento facial: <b>{entitlements.allowed?.face_search?'incluído':'não incluído'}</b></span></div>:<p className="muted small">Esta organização não possui plano comercial vinculado; os limites comerciais não são aplicados.</p>}</section>}

 <section className="panel"><div className="section-title"><div><span className="eyebrow">Upload local</span><h2>Enviar fotos</h2></div><span className="muted small">JPG, PNG, HEIC e outros formatos de imagem • acima de 10 MB são otimizadas automaticamente</span></div><div className="upload"><input type="file" accept="image/*" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/>{files.length>0&&<div className="actions"><strong>{files.length} arquivo(s) selecionado(s)</strong><button className="btn" disabled={uploading||!!(entitlements?.plan&&!entitlements?.allowed?.upload_photos)} onClick={upload}>{uploading?'Enviando...':'Enviar fotos'}</button><button className="btn alt" onClick={()=>setFiles([])}>Limpar</button></div>}</div></section>

 <section className="panel"><div className="section-title"><div><span className="eyebrow">Arquivo compactado</span><h2>Importar ZIP de fotos</h2></div><span className="muted small">O navegador copia o ZIP imediatamente para evitar perda de permissão do arquivo</span></div><div className="upload"><input type="file" accept=".zip,application/zip,application/x-zip-compressed" multiple disabled={zipBusy||!!(entitlements?.plan&&!entitlements?.allowed?.upload_photos)} onChange={e=>selectZip(e.currentTarget)}/>{zipFiles.length>0&&<div className="actions"><strong>{zipFiles.length} ZIP(s) preparado(s)</strong><button className="btn" disabled={zipBusy} onClick={importZip}>{zipBusy?'Importando ZIP...':'Ler ZIP e importar fotos'}</button><button className="btn alt" onClick={()=>setZipFiles([])}>Limpar</button></div>}</div><p className="muted small">Se o ZIP estiver sincronizado pelo iCloud Drive ou OneDrive e ainda der erro, copie o arquivo para Downloads/Área de Trabalho antes de selecionar.</p></section>

 <section className="panel"><div className="section-title"><div><span className="eyebrow">iCloud Fotos</span><h2>Importar diretamente pelo link</h2></div><span className="muted small">share.icloud.com/photos/...</span></div><p className="muted">Cole o link público criado no app Fotos. O sistema tenta ler as imagens no servidor e enviá-las diretamente ao álbum, sem abrir o site do iCloud.</p><div className="toolbar"><input className="growInput" value={icloud} onChange={e=>{setIcloud(e.target.value);setIcloudPhotos([]);setSelectedIcloud([])}} placeholder="https://share.icloud.com/photos/..."/><button className="btn" disabled={icloudBusy||!icloud.trim()||!!(entitlements?.plan&&!entitlements?.allowed?.upload_photos)} onClick={listIcloud}>{icloudBusy?'Lendo iCloud...':'Ler fotos do iCloud'}</button></div>{icloudPhotos.length>0&&<><div className="driveActions actions"><button className="btn alt" onClick={()=>setSelectedIcloud(icloudPhotos.map(p=>p.guid))}>Selecionar todas</button><button className="btn alt" onClick={()=>setSelectedIcloud([])}>Limpar seleção</button><button className="btn" disabled={icloudBusy||!selectedIcloud.length} onClick={importIcloud}>Importar {selectedIcloud.length} foto(s)</button></div><div className="driveList">{icloudPhotos.map((p,i)=><label className="driveItem" key={p.guid}><input type="checkbox" checked={selectedIcloud.includes(p.guid)} onChange={e=>setSelectedIcloud(e.target.checked?[...selectedIcloud,p.guid]:selectedIcloud.filter(x=>x!==p.guid))}/><span>{p.name||`Foto ${i+1}`}{p.width&&p.height?` • ${p.width}×${p.height}`:''}</span></label>)}</div></>}</section>

 <section className="panel"><span className="eyebrow">Google Drive</span><h2>Importar pasta</h2><div className="toolbar"><input className="growInput" value={drive} onChange={e=>setDrive(e.target.value)} placeholder="Cole o link da pasta do Google Drive"/><button className="btn" disabled={driveBusy||!!(entitlements?.plan&&!entitlements?.allowed?.upload_photos)} onClick={listDrive}>{driveBusy?'Aguarde...':'Verificar pasta'}</button></div>{driveFiles.length>0&&<><div className="driveActions actions"><button className="btn alt" onClick={()=>setSelectedDrive(driveFiles.map(f=>f.id))}>Selecionar todos</button><button className="btn alt" onClick={()=>setSelectedDrive([])}>Limpar seleção</button><button className="btn" disabled={driveBusy||!selectedDrive.length} onClick={importDrive}>Importar {selectedDrive.length} selecionada(s)</button></div><div className="driveList">{driveFiles.map(f=><label className="driveItem" key={f.id}><input type="checkbox" checked={selectedDrive.includes(f.id)} onChange={e=>setSelectedDrive(e.target.checked?[...selectedDrive,f.id]:selectedDrive.filter(x=>x!==f.id))}/><span>{f.name}</span></label>)}</div></>}</section>

 <section className="panel"><div className="section-title"><div><span className="eyebrow">Busca facial</span><h2>Reconhecimento</h2></div>{event?.face_search_enabled?<span className="face-ready">✓ Ativo</span>:entitlements?.plan&&!entitlements?.allowed?.face_search?<span className="status-off">Não incluído no plano</span>:<span className="muted">Desativado</span>}</div><p className="muted">Ao ativar ou atualizar, o sistema analisa as fotos publicadas do evento para permitir que o visitante encontre suas imagens por selfie.</p><div className="actions"><button className="btn" disabled={indexing||!photos.length||!!(entitlements?.plan&&!entitlements?.allowed?.face_search)} onClick={indexFaces}>{indexing?'Indexando...':event?.face_search_enabled?'Atualizar reconhecimento':'Ativar reconhecimento'}</button>{event?.face_search_enabled&&<button className="btn alt" onClick={disableFace}>Desativar</button>}</div></section>

 <section className="panel"><div className="section-title"><div><span className="eyebrow">Biblioteca</span><h2>{photos.length} foto(s)</h2></div><div className="actions"><input className="filter-input" placeholder="Filtrar por nome" value={filter} onChange={e=>setFilter(e.target.value)}/>{selected.length>0&&<button className="btn danger" onClick={()=>softDelete(selected)}>Excluir {selected.length}</button>}</div></div><div className="grid">{shown.map(p=><div className={`photo ${selected.includes(p.id)?'selected':''}`} style={{backgroundImage:`url(${p.secure_url})`}} key={p.id} onClick={()=>setSelected(selected.includes(p.id)?selected.filter(x=>x!==p.id):[...selected,p.id])}><input className="photo-check" type="checkbox" checked={selected.includes(p.id)} readOnly/><button className="photo-delete" onClick={e=>{e.stopPropagation();softDelete([p.id])}}>×</button><span>{p.original_filename||'Foto'}</span></div>)}</div></section>
 </main>
}