'use client';
import {useEffect,useRef,useState} from 'react';
import {KEY,SB,readSession} from '../../lib/sb';

type UserInfo={email?:string;user_metadata?:{full_name?:string;name?:string;avatar_url?:string}};
export default function AccountMenu(){
 const [open,setOpen]=useState(false),[user,setUser]=useState<UserInfo|null>(null),[role,setRole]=useState('Acesso'),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{(async()=>{const s=readSession();if(!s?.access_token)return;try{const r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});if(r.ok)setUser(await r.json());const d=await fetch(`${SB}/functions/v1/developer-console`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});if(d.ok)setRole('Desenvolvedor');else{const a=await fetch(`${SB}/functions/v1/admin-access`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});const j=await a.json().catch(()=>({}));const rr=j?.profile?.role;setRole(rr==='administrator'?'Administrador':rr==='manager'?'Gerente':rr==='photographer'?'Fotógrafo':rr==='attendant'?'Atendente':'Acesso administrativo')}}catch{}})();const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};const profile=(e:Event)=>setUser((e as CustomEvent).detail||null);document.addEventListener('mousedown',close);window.addEventListener('semeando-profile-updated',profile);return()=>{document.removeEventListener('mousedown',close);window.removeEventListener('semeando-profile-updated',profile)}},[]);
 if(!readSession()?.access_token)return null;
 const name=user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email?.split('@')[0]||'Usuário';const avatar=user?.user_metadata?.avatar_url;
 function logout(){localStorage.removeItem('semeando_admin_session');sessionStorage.removeItem('semeando_admin_session');location.href='/acesso'}
 return <div ref={ref} className="account-menu-wrap"><button className="account-trigger" onClick={()=>setOpen(x=>!x)} aria-label="Abrir menu da conta">{avatar?<img src={avatar} alt=""/>:<span>{name.charAt(0).toUpperCase()}</span>}<div><b>{name}</b><small>{role}</small></div><i>⌄</i></button>{open&&<div className="account-pop"><div className="account-head">{avatar?<img src={avatar} alt=""/>:<span>{name.charAt(0).toUpperCase()}</span>}<div><b>{name}</b><small>{user?.email}</small><em>{role}</em></div></div><a href="/conta">◎ Meu acesso</a><a href="/conta?tab=seguranca">🔒 Segurança</a><a href="/conta?tab=suporte">◌ Suporte</a><button onClick={logout}>↪ Sair</button></div>}<style jsx>{`
.account-menu-wrap{position:fixed;z-index:90;right:18px;top:max(14px,env(safe-area-inset-top));font-family:inherit}.account-trigger{height:48px;display:flex;align-items:center;gap:9px;border:1px solid #30343c;background:#15171cf2;backdrop-filter:blur(16px);border-radius:15px;padding:5px 10px 5px 6px;color:#fff;box-shadow:0 12px 34px #0006}.account-trigger img,.account-trigger>span{width:36px;height:36px;border-radius:11px;object-fit:cover;display:grid;place-items:center;background:#ff7417;font-weight:900}.account-trigger div{display:grid;text-align:left;line-height:1.05;max-width:150px}.account-trigger b{font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.account-trigger small{font-size:9px;color:#b4bac3;margin-top:4px}.account-trigger i{font-style:normal;color:#858b95}.account-pop{position:absolute;right:0;top:56px;width:260px;padding:10px;border:1px solid #3a404a;background:#121419fa;backdrop-filter:blur(22px);border-radius:17px;box-shadow:0 22px 60px #0009;display:grid;gap:3px}.account-head{display:flex;gap:11px;align-items:center;padding:8px 8px 13px;border-bottom:1px solid #292c33;margin-bottom:4px}.account-head img,.account-head>span{width:48px;height:48px;border-radius:14px;object-fit:cover;display:grid;place-items:center;background:#ff7417;font-size:20px;font-weight:950}.account-head div{display:grid;min-width:0}.account-head b{font-size:13px}.account-head small{font-size:10px;color:#b0b5be;overflow:hidden;text-overflow:ellipsis}.account-head em{font-style:normal;font-size:9px;color:#ff9852;margin-top:3px;font-weight:800}.account-pop a,.account-pop button{border:0;background:transparent;color:#f0f2f5;text-decoration:none;text-align:left;border-radius:10px;padding:11px 12px;font-size:12px;font-weight:800}.account-pop a:hover,.account-pop button:hover{background:#24272e}.account-pop button{border-top:1px solid #292c33;border-radius:0;margin-top:3px;color:#ffad7b}@media(max-width:700px){.account-menu-wrap{right:10px}.account-trigger div{display:none}.account-trigger{padding-right:7px}.account-trigger i{display:none}.account-pop{width:min(280px,calc(100vw - 20px))}}
`}</style></div>
}
