'use client';
import {useEffect,useMemo,useState} from 'react';
import {KEY,SB,money} from '../../lib/sb';

type Gateway={ready:boolean;message?:string;environment?:string};
const storageKey=(slug:string)=>`semeando_paid_cart:${slug}`;
const orderKey=(slug:string)=>`semeando_paid_order:${slug}`;

function currentSlug(){const m=location.pathname.match(/\/evento\/([^/?#]+)/);return m?.[1]?decodeURIComponent(m[1]):''}
function photoIdFromPreview(src:string){try{return new URL(src,location.origin).searchParams.get('id')||''}catch{return ''}}
function previewFromCard(el:HTMLElement){const direct=el.dataset.previewUrl||'';if(direct)return direct;const img=el.querySelector<HTMLImageElement>('img[data-paid-preview]');if(img?.currentSrc||img?.src)return img.currentSrc||img.src;const bg=el.style.backgroundImage||getComputedStyle(el).backgroundImage;return bg.match(/url\(["']?(.*?)["']?\)/)?.[1]||''}

export default function PaidPhotoPreviewBridge(){
 const [src,setSrc]=useState(''),[photoId,setPhotoId]=useState(''),[similarity,setSimilarity]=useState(''),[cart,setCart]=useState<string[]>([]),[gateway,setGateway]=useState<Gateway>({ready:false}),[price,setPrice]=useState(0),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const slug=typeof window==='undefined'?'':currentSlug();
 const total=useMemo(()=>Number((price*cart.length).toFixed(2)),[price,cart.length]);
 const selected=!!photoId&&cart.includes(photoId);
 useEffect(()=>{if(!slug)return;try{setCart(JSON.parse(localStorage.getItem(storageKey(slug))||'[]'))}catch{setCart([])};(async()=>{try{const r=await fetch(`${SB}/functions/v1/photo-purchase`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({action:'status',event_slug:slug})});const d=await r.json();if(r.ok){setGateway(d.gateway||{ready:false});setPrice(Number(d.price_per_photo||0))}}catch{}})()},[slug]);
 useEffect(()=>{if(slug)localStorage.setItem(storageKey(slug),JSON.stringify(cart))},[cart,slug]);
 useEffect(()=>{const click=(e:MouseEvent)=>{const el=(e.target as HTMLElement)?.closest?.('.paid-photo') as HTMLElement|null;if(!el)return;const nextSrc=previewFromCard(el);if(!nextSrc)return;e.preventDefault();e.stopPropagation();setSrc(nextSrc);setPhotoId(el.dataset.photoId||photoIdFromPreview(nextSrc));setSimilarity(el.querySelector('[data-similarity]')?.textContent||'');setMessage('')};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[]);
 useEffect(()=>{if(!src)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')setSrc('')};document.addEventListener('keydown',esc);document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',esc);document.body.style.overflow=''}},[src]);
 function toggle(id=photoId){if(!id)return;setCart(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function checkout(photoIds=cart){if(!slug||!photoIds.length)return;if(!gateway.ready){setMessage(gateway.message||'O pagamento está sendo configurado. Suas fotos permanecerão salvas no carrinho.');return}let visitor:any=null;try{visitor=JSON.parse(localStorage.getItem('semeando_visitor')||'null')}catch{};if(!visitor?.id){setMessage('Seu cadastro não foi localizado. Entre novamente no álbum para continuar.');return}setBusy(true);setMessage('Preparando pagamento...');try{const r=await fetch(`${SB}/functions/v1/photo-purchase`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({action:'create_order',event_slug:slug,visitor_id:visitor.id,photo_ids:photoIds})});const d=await r.json();if(!r.ok)throw new Error(d.message||d.error||'Não foi possível criar o pagamento.');if(d.order?.id&&d.access_token)localStorage.setItem(orderKey(slug),JSON.stringify({order_id:d.order.id,access_token:d.access_token}));if(d.order?.invoice_url){setMessage('Pagamento criado. Abrindo o checkout seguro...');location.href=d.order.invoice_url}else setMessage('Pedido criado. Aguarde a liberação do pagamento.')}catch(e:any){setMessage(e.message||'Não foi possível finalizar agora.')}finally{setBusy(false)}}
 function buyNow(){if(!photoId)return;const next=cart.includes(photoId)?cart:[...cart,photoId];if(next.length!==cart.length)setCart(next);void checkout(next)}
 if(!src&&cart.length===0)return null;
 return <>
  {cart.length>0&&<div className="pp-cart"><div><b>🛒 {cart.length} foto{cart.length>1?'s':''}</b><span>{price>0?money(total):'Selecionadas'}</span></div><button disabled={busy} onClick={()=>void checkout()}>{busy?'Preparando...':'Finalizar compra'}</button></div>}
  {src&&<div className="pp-back" role="dialog" aria-modal="true" onClick={()=>setSrc('')}><section className="pp-card" onClick={e=>e.stopPropagation()}><button className="pp-close" onClick={()=>setSrc('')} aria-label="Fechar">×</button><div className="pp-image"><img src={src} alt="Prévia protegida"/></div><div className="pp-info"><div><span>PRÉVIA PROTEGIDA</span><h2>Sua foto foi encontrada</h2><p>Esta é uma prévia com proteção. O arquivo original em alta qualidade continua bloqueado até a conclusão da compra.</p>{similarity&&<small>{similarity}</small>}</div><div className="pp-lock">🔒 Original protegido</div></div><div className="pp-actions"><button className={selected?'remove':''} onClick={()=>toggle()}>{selected?'✓ No carrinho · remover':'🛒 Adicionar ao carrinho'}</button><button className="buy" disabled={busy} onClick={buyNow}>{busy?'Preparando...':'Comprar agora'}</button></div>{message&&<div className="pp-message">{message}</div>}</section></div>}
  <style jsx>{`.pp-back{position:fixed;inset:0;z-index:9999;background:#000d;backdrop-filter:blur(12px);display:grid;place-items:center;padding:16px}.pp-card{position:relative;width:min(760px,100%);max-height:92vh;background:#111419;border:1px solid #343a43;border-radius:22px;overflow:auto;box-shadow:0 30px 90px #000}.pp-close{position:absolute;z-index:2;right:12px;top:12px;width:42px;height:42px;border:0;border-radius:999px;background:#0b0d10dd;color:#fff;font-size:28px}.pp-image{background:#080a0d;display:grid;place-items:center;max-height:62vh;overflow:auto}.pp-image img{display:block;max-width:100%;max-height:62vh;object-fit:contain}.pp-info{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:16px 18px 10px}.pp-info span{color:#ff8a3d;font-size:10px;letter-spacing:.15em;font-weight:950}.pp-info h2{margin:5px 0;font-size:22px}.pp-info p{margin:0;color:#a5abb4;font-size:12px;line-height:1.55;max-width:560px}.pp-info small{display:inline-block;margin-top:8px;background:#242931;padding:6px 8px;border-radius:8px}.pp-lock{white-space:nowrap;background:#23180f;border:1px solid #5d3922;color:#ffad79;padding:10px 12px;border-radius:11px;font-size:11px;font-weight:900}.pp-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:0 18px 16px}.pp-actions button{border:0;border-radius:12px;padding:13px 14px;background:#292f38;color:#fff;font-weight:900}.pp-actions .buy{background:#ff7417}.pp-actions .remove{background:#1d3327;color:#8fe0ae}.pp-message{margin:0 18px 16px;padding:10px 12px;background:#20242b;border-radius:10px;color:#c8ccd2;font-size:12px}.pp-cart{position:fixed;z-index:9998;left:50%;bottom:max(14px,env(safe-area-inset-bottom));transform:translateX(-50%);width:min(620px,calc(100% - 20px));display:flex;align-items:center;justify-content:space-between;gap:12px;background:#15191fee;border:1px solid #39414c;border-radius:16px;padding:10px 12px;box-shadow:0 18px 55px #0009;backdrop-filter:blur(14px)}.pp-cart>div{display:grid}.pp-cart span{font-size:11px;color:#aeb4bd}.pp-cart button{border:0;border-radius:11px;padding:11px 14px;background:#ff7417;color:#fff;font-weight:900}@media(max-width:650px){.pp-back{padding:8px}.pp-card{border-radius:16px}.pp-info{display:grid}.pp-lock{justify-self:start}.pp-info h2{font-size:19px}.pp-actions{grid-template-columns:1fr}.pp-cart{font-size:12px}}`}</style>
 </>
}
