'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {CHURCH_LOGO,LEGACY_LOGO} from '../brand';
import {SB,KEY,adminHeaders,nativeShare,session,slugify,requireActiveAdminAccess} from '../../lib/sb';
type GalleryAccess='public'|'face_only'|'closed';type Tab='home'|'events'|'leads'|'users';
type Ev={id:string;title:string;slug:string;event_date:string|null;location:string|null;status:string;face_search_enabled:boolean;gallery_access:GalleryAccess;is_paid:boolean;price_per_photo:number|null;full_album_price:number|null;preview_limit:number;cover_url:string|null;photo_count?:number};
type Lead={id:string;full_name:string;housing_type:string;street:string;neighborhood:string;city:string;whatsapp:string;marketing_consent:boolean;created_at:string};type User={user_id:string;full_name:string;email:string;role:string;is_active:boolean};
const roleNames:Record<string,string>={developer:'Developer Mestre',administrator:'Administrador',manager:'Gerente',photographer:'Fotógrafo',attendant:'Atendimento',finance:'Financeiro',viewer:'Visualizador'};
export default function Admin(){
 const [tab,setTab]=useState<Tab>('home'),[access,setAccess]=useState<any>(null),[events,setEvents]=useState<Ev[]>([]),[leads,setLeads]=useState<Lead[]>([]),[users,setUsers]=useState<User[]>([]),[msg,setMsg]=useState(''),[entitlements,setEntitlements]=useState<any>(null),[ready,setReady]=useState(false);
 const [modal,setModal]=useState(false),[editing,setEditing]=useState<Ev|null>(null),[title,setTitle]=useState(''),[slug,setSlug]=useState(''),[date,setDate]=useState(''),[locationV,setLocation]=useState(''),[paid,setPaid]=useState(false),[perPhoto,setPerPhoto]=useState(''),[album,setAlbum]=useState(''),[limit,setLimit]=useState('20'),[cover,setCover]=useState<File|null>(null),[saving,setSaving]=useState(false),[visible,setVisible]=useState(true),[galleryAccess,setGalleryAccess]=useState<GalleryAccess>('face_only');
 const [userModal,setUserModal]=useState(false),[ufull,setUfull]=useState(''),[uemail,setUemail]=useState(''),[upass,setUpass]=useState(''),[urole,setUrole]=useState('attendant'),[usaving,setUsaving]=useState(false);
 const perms=useMemo(()=>new Set<string>(access?.permissions||[]),[access]);const has=(p:string)=>perms.has('*')||perms.has(p);
 async function ensure(){const s=await session();if(!s?.access_token){location.href='/acesso';return null}return s}
 async function loadEntitlements(){const s=await ensure();if(!s)return null;try{const r=await fetch(`${SB}/functions/v1/plan-entitlements`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:'{}'}),d=await r.json();if(r.ok){setEntitlements(d);return d}}catch{}return null}
 async function loadEvents(){if(!has('events.view'))return;const s=await ensure();if(!s)return;const r=await fetch(`${SB}/rest/v1/events?select=id,title,slug,event_date,location,status,face_search_enabled,gallery_access,is_paid,price_per_photo,full_album_price,preview_limit,cover_url&order=created_at.desc`,{headers:await adminHeaders(false)}),d=await r.json();if(!r.ok)return;const enriched=await Promise.all(d.map(async(e:Ev)=>{if(!has('photos.view'))return{...e,photo_count:0};const pr=await fetch(`${SB}/rest/v1/photos?event_id=eq.${e.id}&deleted_at=is.null&select=id`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,Prefer:'count=exact'}}),cr=pr.headers.get('content-range');return{...e,photo_count:cr?Number(cr.split('/')[1]||0):0}}));setEvents(enriched);if(has('events.create'))await loadEntitlements()}
 async function loadLeads(){if(!has('leads.view'))return;const r=await fetch(`${SB}/rest/v1/visitors?select=id,full_name,housing_type,street,neighborhood,city,whatsapp,marketing_consent,created_at&order=created_at.desc`,{headers:await adminHeaders(false)});if(r.ok)setLeads(await r.json())}
 async function loadUsers(){if(!has('users.view'))return;const s=await ensure();if(!s)return;const r=await fetch(`${SB}/functions/v1/admin-users`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}}),d=await r.json();if(r.ok)setUsers(d.users||[])}
 useEffect(()=>{(async()=>{const a=await requireActiveAdminAccess();if(!a)return;setAccess(a);setReady(true)})()},[]);
 useEffect(()=>{if(!ready)return;loadEvents();loadLeads();loadUsers();if(has('events.view'))setTab('events');else if(has('leads.view'))setTab('leads');else if(has('users.view'))setTab('users');else setTab('home')},[ready,access]);
 const photos=useMemo(()=>events.reduce((a,e)=>a+(e.photo_count||0),0),[events]);
 function open(e?:Ev){if(e&&!has('events.edit'))return setMsg('Seu perfil não permite editar eventos.');if(!e&&!has('events.create'))return setMsg('Seu perfil não permite criar eventos.');if(!e&&entitlements?.plan&&!entitlements?.allowed?.create_event)return setMsg(`Limite do plano ${entitlements.plan.name} atingido.`);setEditing(e||null);setTitle(e?.title||'');setSlug(e?.slug||'');setDate(e?.event_date||'');setLocation(e?.location||'');setVisible(e?e.status==='published':true);setGalleryAccess(e?.gallery_access||(entitlements?.plan&&!entitlements?.allowed?.face_search?'public':'face_only'));setPaid(!!e?.is_paid);setPerPhoto(e?.price_per_photo!=null?String(e.price_per_photo):'');setAlbum(e?.full_album_price!=null?String(e.full_album_price):'');setLimit(String(e?.preview_limit||20));setCover(null);setModal(true)}
 async function saveEvent(ev:FormEvent){ev.preventDefault();if(editing&&!has('events.edit'))return;if(!editing&&!has('events.create'))return;setSaving(true);setMsg('');try{let coverUrl=editing?.cover_url||null;if(cover){const fd=new FormData();fd.append('file',cover);fd.append('upload_preset','semeando_memorias');fd.append('folder','semeando-memorias/capas');const cr=await fetch('https://api.cloudinary.com/v1_1/to3hnwdl/image/upload',{method:'POST',body:fd}),cd=await cr.json();if(!cr.ok)throw Error(cd?.error?.message||'Erro ao enviar capa.');coverUrl=cd.secure_url}const faceAuto=galleryAccess==='face_only'&&(!entitlements?.plan||entitlements?.allowed?.face_search),payload={title:title.trim(),slug:slugify(slug||title),event_date:date||null,location:locationV.trim()||null,status:visible?'published':'draft',face_search_enabled:faceAuto||editing?.face_search_enabled||false,gallery_access:galleryAccess,is_paid:paid,price_per_photo:paid&&perPhoto?Number(perPhoto.replace(',','.')):null,full_album_price:paid&&album?Number(album.replace(',','.')):null,preview_limit:paid?Math.max(1,Math.min(200,Number(limit||20))):20,cover_url:coverUrl};const r=await fetch(editing?`${SB}/rest/v1/events?id=eq.${editing.id}`:`${SB}/rest/v1/events`,{method:editing?'PATCH':'POST',headers:{...await adminHeaders(),Prefer:'return=representation'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.details||d.message||'Erro ao salvar evento.');setModal(false);await loadEvents();setMsg('Evento salvo com sucesso.')}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}
 async function del(e:Ev){if(!has('events.delete'))return setMsg('Seu perfil não permite excluir eventos.');if(!confirm(`Excluir o evento “${e.title}”?`))return;const r=await fetch(`${SB}/rest/v1/events?id=eq.${e.id}`,{method:'DELETE',headers:await adminHeaders()});r.ok?loadEvents():setMsg('Não foi possível excluir o evento.')}
 async function shareAlbum(e:Ev){await nativeShare(`${e.title} | Semeando Memórias`,`Veja as fotos do evento ${e.title}.`,`${location.origin}/evento/${e.slug}`)}
 async function createUser(ev:FormEvent){ev.preventDefault();if(!has('users.create'))return;setUsaving(true);try{const s=await ensure();if(!s)return;const r=await fetch(`${SB}/functions/v1/admin-users`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({full_name:ufull,email:uemail,password:upass,role:urole})}),d=await r.json();if(!r.ok)throw Error(d.error);setUserModal(false);setUfull('');setUemail('');setUpass('');setUrole('attendant');await loadUsers();setMsg('Usuário criado com sucesso.')}catch(e:any){setMsg(e.message)}finally{setUsaving(false)}}
 async function toggleUser(u:User){if(!has('users.edit'))return;const s=await ensure();if(!s)return;const r=await fetch(`${SB}/functions/v1/admin-users`,{method:'PATCH',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:u.user_id,is_active:!u.is_active})}),d=await r.json();r.ok?loadUsers():setMsg(d.error)}
 async function delUser(u:User){if(!has('users.delete'))return setMsg('Seu perfil não permite excluir usuários.');if(!confirm(`Excluir o acesso de ${u.full_name||u.email}?`))return;const s=await ensure();if(!s)return;const r=await fetch(`${SB}/functions/v1/admin-users`,{method:'DELETE',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({user_id:u.user_id})}),d=await r.json();r.ok?loadUsers():setMsg(d.error)}
 function logout(){localStorage.removeItem('semeando_admin_session');sessionStorage.removeItem('semeando_admin_session');location.href='/acesso'}
 if(!ready)return <main className="wrap"><div className="panel">Validando seu acesso...</div></main>;
 return <main className="admin admin-pro"><aside><div className="admin-brand"><img src={CHURCH_LOGO} alt=""/><div><h2>{access?.organization?.name||'Semeando Memórias'}</h2><span>{access?.role?.label||roleNames[access?.profile?.role]||'Painel administrativo'}</span></div></div><nav className="admin-nav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>⌂ Meu acesso</button>{has('events.view')&&<button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>▦ Eventos</button>}{has('leads.view')&&<button onClick={()=>location.href='/admin/leads'}>◎ Leads <b>{leads.length}</b></button>}{has('users.view')&&<button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>♙ Usuários</button>}</nav><div className="admin-side-bottom"><a href="/conta">Perfil e segurança</a><a href="/">↗ Site público</a><button onClick={logout}>Sair</button><div className="admin-byline"><span>Desenvolvido por</span><img src={LEGACY_LOGO} alt="Legacy Solar"/><b>Legacy Solar</b></div></div></aside><section className="admin-content"><header className="admin-header"><div><span className="eyebrow">{access?.organization?.name||'Acesso administrativo'}</span><h1>{tab==='home'?'Meu acesso':tab==='events'?'Eventos':tab==='leads'?'Leads':'Usuários'}</h1></div><div className="header-actions">{tab==='events'&&has('events.create')&&<button className="btn" disabled={!!(entitlements?.plan&&!entitlements?.allowed?.create_event)} onClick={()=>open()}>＋ Criar evento</button>}{tab==='users'&&has('users.create')&&<button className="btn" onClick={()=>setUserModal(true)}>＋ Criar usuário</button>}</div></header>{msg&&<p className="notice">{msg}</p>}
 {tab==='home'&&<><section className="panel"><span className="eyebrow">Perfil de acesso</span><h2>{access?.role?.label||roleNames[access?.profile?.role]}</h2><p className="muted">{access?.role?.description||'As ações disponíveis são controladas pelas permissões da sua organização.'}</p><div className="permission-chips">{[...perms].filter(x=>x!=='*').map(p=><span className="role-badge" key={p}>{p}</span>)}{perms.has('*')&&<span className="face-ready">Acesso mestre • todas as permissões</span>}</div></section><div className="stats stats-three"><article><span>Eventos visíveis</span><strong>{has('events.view')?events.length:'—'}</strong></article><article><span>Fotos</span><strong>{has('photos.view')?photos:'—'}</strong></article><article><span>Leads</span><strong>{has('leads.view')?leads.length:'—'}</strong></article></div></>}
 {tab==='events'&&has('events.view')&&<><div className="stats stats-three"><article><span>Eventos</span><strong>{events.length}</strong></article><article><span>Fotos</span><strong>{has('photos.view')?photos:'—'}</strong></article><article><span>Seu perfil</span><strong style={{fontSize:18}}>{access?.role?.label}</strong></article></div><div className="events">{events.map(e=><article className="event" key={e.id}>{e.cover_url?<div className="cover" style={{backgroundImage:`url(${e.cover_url})`}}/>:<div className="cover empty">📷</div>}<div className="grow"><h3>{e.title}</h3><p className="muted">{has('photos.view')?`${e.photo_count||0} fotos`:''}{e.location?` • ${e.location}`:''}</p></div><div className="actions event-actions">{has('photos.view')&&<a className="btn" href={`/admin/evento/${e.slug}/fotos`}>{has('photos.upload')?'Gerenciar fotos':'Ver fotos'}</a>}<a className="btn alt" href={`/evento/${e.slug}`}>Galeria</a><button className="btn alt" onClick={()=>shareAlbum(e)}>↗ Compartilhar</button>{has('events.edit')&&<button className="btn alt" onClick={()=>open(e)}>Editar</button>}{has('events.delete')&&<button className="btn danger" onClick={()=>del(e)}>Excluir</button>}</div></article>)}</div></>}
 {tab==='users'&&has('users.view')&&<div className="user-cards">{users.map(u=><article className="user-card" key={u.user_id}><div className="user-avatar">{(u.full_name||u.email||'?')[0]?.toUpperCase()}</div><div className="grow"><h3>{u.full_name||'Usuário'}</h3><p>{u.email}</p><span className="role-badge">{roleNames[u.role]||u.role}</span> <span className={u.is_active?'status-on':'status-off'}>{u.is_active?'Ativo':'Desativado'}</span></div><div className="actions">{has('users.edit')&&<button className="btn alt" onClick={()=>toggleUser(u)}>{u.is_active?'Desativar':'Ativar'}</button>}{has('users.delete')&&<button className="btn danger" onClick={()=>delUser(u)}>Excluir</button>}</div></article>)}</div>}
 </section>
 {modal&&<div className="back"><form className="panel modal" onSubmit={saveEvent}><span className="eyebrow">Configurações</span><h2>{editing?'Editar evento':'Criar evento'}</h2><label>Nome<input value={title} onChange={e=>{setTitle(e.target.value);if(!editing)setSlug(slugify(e.target.value))}} required/></label><label>Link<input value={slug} onChange={e=>setSlug(slugify(e.target.value))} required/></label><div className="form-row"><label>Data<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Local<input value={locationV} onChange={e=>setLocation(e.target.value)}/></label></div><fieldset className="event-access-box"><legend>Quem pode ver as fotos?</legend><label className="event-access-option"><input type="radio" checked={galleryAccess==='public'} onChange={()=>setGalleryAccess('public')}/><span><b>Álbum aberto</b></span></label><label className="event-access-option"><input type="radio" checked={galleryAccess==='face_only'} onChange={()=>setGalleryAccess('face_only')}/><span><b>Somente minhas fotos</b></span></label><label className="event-access-option"><input type="radio" checked={galleryAccess==='closed'} onChange={()=>setGalleryAccess('closed')}/><span><b>Não mostrar fotos ao público</b></span></label></fieldset><label className="event-access-option"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/><span><b>Evento visível</b></span></label><label>Imagem de capa<input type="file" accept="image/*" onChange={e=>setCover(e.target.files?.[0]||null)}/></label><div className="actions modal-actions"><button disabled={saving}>{saving?'Salvando...':'Salvar evento'}</button><button type="button" className="btn alt" onClick={()=>setModal(false)}>Cancelar</button></div></form></div>}
 {userModal&&<div className="back"><form className="panel modal user-form" onSubmit={createUser}><span className="eyebrow">Controle de acesso</span><h2>Criar usuário</h2><label>Nome<input value={ufull} onChange={e=>setUfull(e.target.value)} required/></label><label>E-mail<input type="email" value={uemail} onChange={e=>setUemail(e.target.value)} required/></label><label>Senha inicial<input type="password" minLength={8} value={upass} onChange={e=>setUpass(e.target.value)} required/></label><label>Perfil<select value={urole} onChange={e=>setUrole(e.target.value)}><option value="administrator">Administrador</option><option value="manager">Gerente</option><option value="photographer">Fotógrafo</option><option value="attendant">Atendimento</option><option value="finance">Financeiro</option><option value="viewer">Visualizador</option></select></label><div className="actions modal-actions"><button disabled={usaving}>{usaving?'Criando...':'Criar acesso'}</button><button type="button" className="btn alt" onClick={()=>setUserModal(false)}>Cancelar</button></div></form></div>}
 </main>}
