'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {SB,KEY,money,readSession} from '../../../lib/sb';
type Photo={id:string;secure_url?:string;original_url?:string;thumbnail_url?:string;display_url?:string;preview_url?:string;original_filename?:string;similarity?:number};
const roleLabel:Record<string,string>={administrator:'Administrador',manager:'Gerente',photographer:'Fotógrafo',attendant:'Atendente'};
const PAGE=24;
export default function EventPage({params}:{params:{slug:string}}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[visitor,setVisitor]=useState<any>(null),[faceOpen,setFaceOpen]=useState(false),[image,setImage]=useState(''),[preview,setPreview]=useState(''),[preparing,setPreparing]=useState(false),[consent,setConsent]=useState(false),[searching,setSearching]=useState(false),[faceMsg,setFaceMsg]=useState(''),[consentWarning,setConsentWarning]=useState(''),[matches,setMatches]=useState<Photo[]>([]),[visible,setVisible]=useState(PAGE),[viewer,setViewer]=useState<Photo|null>(null),[downloading,setDownloading]=useState<string|null>(null),[searchMs,setSearchMs]=useState<number|null>(null);
 useEffect(()=>{let v:any=null;try{v=JSON.parse(localStorage.getItem('semeando_visitor')||'null')}catch{};const admin=readSession();if(!v?.id&&!admin?.access_token){location.replace(`/cadastro?next=${encodeURIComponent(`/evento/${params.slug}`)}`);return}setVisitor(v);(async()=>{try{const headers:Record<string,string>={apikey:KEY};if(admin?.access_token)headers.Authorization=`Bearer ${admin.access_token}`;const r=await fetch(`${SB}/functions/v1/public-gallery?slug=${encodeURIComponent(params.slug)}`,{headers});const d=await r.json();if(!r.ok)throw new Error(d.error||'Evento não encontrado.');setData(d);if(v?.id){fetch(`${SB}/rest/v1/event_visitors`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({event_id:d.event.id,visitor_id:v.id})}).catch(()=>{})}}catch(e:any){setData({error:e.message})}finally{setLoading(false)}})()},[params.slug]);
 const shownMatches=useMemo(()=>matches.slice(0,visible),[matches,visible]);
 function isHeic(file:File){return /heic|heif/i.test(file.type)||/\.(heic|heif)$/i.test(file.name)}
 async function normalizeImage(file:File):Promise<Blob>{if(!isHeic(file))return file;const mod:any=await import('heic2any');const converted=await mod.default({blob:file,toType:'image/jpeg',quality:.88});return Array.isArray(converted)?converted[0]:converted}
 async function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];e.target.value='';if(!f)return;if(!f.type.startsWith('image/')&&!/\.(heic|heif|jpg|jpeg|png|webp)$/i.test(f.name)){setFaceMsg('Escolha um arquivo de imagem válido.');return}if(f.size>25*1024*1024){setFaceMsg('A imagem é muito grande. Escolha uma foto com até 25 MB.');return}if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);const objectUrl=URL.createObjectURL(f);setPreview(objectUrl);setImage('');setPreparing(true);setFaceMsg(isHeic(f)?'Convertendo a foto do iPhone...':'Preparando sua foto...');setMatches([]);setVisible(PAGE);try{const normalized=await normalizeImage(f);const url=await compress(normalized);setImage(url);if(isHeic(f))setPreview(url);setFaceMsg('Foto pronta. Confira o rosto e toque em “Buscar minhas fotos”.')}catch(err){console.error(err);setImage('');setFaceMsg('Não conseguimos preparar esta foto. Tente tirar uma nova selfie ou escolha outra imagem.')}finally{setPreparing(false)}}
 function fileToDataUrl(file:Blob):Promise<string>{return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(String(rd.result||''));rd.onerror=()=>reject(rd.error);rd.readAsDataURL(file)})}
 async function compress(file:Blob):Promise<string>{const src=await fileToDataUrl(file);return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{try{const max=1280,scale=Math.min(1,max/Math.max(im.naturalWidth||im.width,im.naturalHeight||im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round((im.naturalWidth||im.width)*scale));c.height=Math.max(1,Math.round((im.naturalHeight||im.height)*scale));const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas indisponível');ctx.drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.84))}catch(e){reject(e)}};im.onerror=()=>reject(new Error('Formato não suportado'));im.src=src})}
 async function faceSearch(){if(!image||!consent||preparing)return;const started=performance.now();setSearching(true);setSearchMs(null);setFaceMsg('Buscando suas fotos...');setMatches([]);setVisible(PAGE);try{const r=await fetch(`${SB}/functions/v1/face-search`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({event_slug:params.slug,image_base64:image,consent:true,visitor_id:visitor?.id||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível fazer a busca.');const found=d.photos||[];setMatches(found);setSearchMs(Math.max(.1,(performance.now()-started)/1000));setFaceMsg(found.length?`${found.length} foto(s) encontrada(s). As miniaturas carregam primeiro para você navegar mais rápido.`:'Não encontramos fotos deste rosto neste evento. Tente outra imagem com o rosto bem visível.');if(found.length){setFaceOpen(false);setTimeout(()=>document.getElementById('minhas-fotos')?.scrollIntoView({behavior:'smooth',block:'start'}),100)}}catch(e:any){setFaceMsg(e.message)}finally{setSearching(false)}}
 async function downloadPhoto(p:Photo){const src=p.original_url||p.secure_url;if(!src)return;setDownloading(p.id);try{const r=await fetch(src);if(!r.ok)throw new Error('download');const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=p.original_filename||`semeando-memorias-${p.id}.jpg`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}catch{window.open(src,'_blank','noopener,noreferrer')}finally{setDownloading(null)}}
 function clearSelectedImage(){if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);setPreview('');setImage('');setPreparing(false);setMatches([]);setVisible(PAGE);setSearchMs(null);setFaceMsg('')}
 function resetFace(){clearSelectedImage();setConsent(false);setConsentWarning('')}
 function openFaceSearch(){if(!consent){setConsentWarning('Para continuar, marque a autorização de uso temporário da imagem para o reconhecimento facial.');setTimeout(()=>document.getElementById('lgpd-public-consent')?.scrollIntoView({behavior:'smooth',block:'center'}),40);return}setConsentWarning('');setFaceOpen(true)}
 if(loading)return <main className="wrap"><div className="panel">Carregando galeria...</div></main>;
 if(data?.error)return <main className="wrap"><div className="panel"><h1>Galeria indisponível</h1><p className="muted">{data.error}</p><a className="btn alt" href="/">Voltar</a></div></main>;
 const ev=data.event,paid=!!ev.is_paid,photos:Photo[]=data.photos||[],staff=data.viewer?.mode==='staff',staffRole=data.viewer?.role;
 return <main className="wrap event-page"><a className="event-back-link" href="/">← Todos os eventos</a><div className="event-hero" style={ev.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,#0008),url(${ev.cover_url})`}:{}}/><div className="event-title-row"><div><span className="eyebrow">Galeria oficial</span><h1>{ev.title}</h1><p className="muted">{ev.location||'Evento'} • {data.total_photos||0} foto(s)</p></div>{staff?<span className="visitor-pill staff-pill">Equipe • {roleLabel[staffRole]||'Acesso autorizado'}</span>:visitor?.full_name&&<span className="visitor-pill">Olá, {visitor.full_name.split(' ')[0]} 👋</span>}</div>
 {staff&&<section className="staff-access-banner"><div>🔓</div><div><strong>Visualização da equipe</strong><p>Seu acesso administrativo está ativo. Você pode visualizar todas as fotos deste álbum.</p></div></section>}
 {!staff&&paid&&<section className="paid-gallery-banner"><div><span className="eyebrow">Galeria protegida</span><h2>Evento com fotos protegidas</h2><p>Depois da busca facial, você verá somente as prévias das fotos em que seu rosto foi localizado.</p></div><div className="paid-prices">{ev.price_per_photo!=null&&<div><span>Por foto</span><strong>{money(ev.price_per_photo)}</strong></div>}{ev.full_album_price!=null&&<div><span>Álbum completo</span><strong>{money(ev.full_album_price)}</strong></div>}</div></section>}
 {!staff&&ev.face_search_enabled&&<section className="panel private-search-panel"><div className="private-search-head"><span className="eyebrow">Acesso pessoal e protegido</span><h2>Encontre somente as suas fotos</h2><p>Use uma selfie ou foto nítida. O álbum completo não fica exposto ao público.</p></div><div className="search-steps"><article><span>1</span><div><strong>Escolha uma imagem</strong><p>Selfie ou foto do celular.</p></div></article><article><span>2</span><div><strong>Autorize a busca</strong><p>Consentimento específico para reconhecimento facial.</p></div></article><article><span>3</span><div><strong>Veja suas fotos</strong><p>Miniaturas leves aparecem primeiro.</p></div></article></div><div className="privacy-explain"><div>🛡️</div><div><strong>Privacidade protegida</strong><p>A imagem escolhida é usada somente para a comparação naquele momento e não fica armazenada como sua foto de referência.</p><a href="/privacidade">Política de Privacidade →</a></div></div><div id="lgpd-public-consent" className="public-consent-box"><label className="consent public-consent-label"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(e.target.checked)setConsentWarning('')}}/><span><b>Autorizo a busca facial</b><small>Autorizo o uso temporário da imagem exclusivamente para localizar minhas fotos neste evento.</small></span></label>{consentWarning&&<div className="consent-warning">⚠️ {consentWarning}</div>}</div><button className="btn face-main-btn private-face-btn" onClick={openFaceSearch}>◎ Encontrar minhas fotos</button></section>}
 {!staff&&!ev.face_search_enabled&&<section className="panel private-search-panel unavailable-search"><span className="eyebrow">Galeria protegida</span><h2>A busca das suas fotos está sendo preparada</h2></section>}
 {!staff&&ev.face_search_enabled&&<section id="minhas-fotos" className="private-result-section"><div className="section-title"><div><span className="eyebrow">Seu resultado</span><h2>{matches.length?`${matches.length} foto(s) encontrada(s)`:'Suas fotos aparecerão aqui'}</h2>{matches.length>0&&<small className="result-speed">⚡ Miniaturas rápidas{searchMs?` • busca em ${searchMs.toFixed(1)} s`:''} • toque para ampliar</small>}</div>{matches.length>0&&<button className="btn alt" onClick={()=>{resetFace();setFaceOpen(true)}}>Nova busca</button>}</div>{faceMsg&&!faceOpen&&<div className="face-status public-face-status">{faceMsg}</div>}{matches.length>0?<><div className="grid gallery-grid private-match-grid">{shownMatches.map(p=>paid?<button type="button" className="photo paid-photo" data-photo-id={p.id} data-preview-url={p.preview_url||''} aria-label={`Abrir prévia protegida de ${p.original_filename||'foto encontrada'}`} key={p.id}>{p.preview_url&&<><img className="paid-photo-backdrop" src={p.preview_url} alt="" aria-hidden="true" loading="lazy" decoding="async"/><img className="paid-photo-image" data-paid-preview="true" src={p.preview_url} alt={p.original_filename||'Foto encontrada'} loading="lazy" decoding="async"/></>}<span data-similarity>{Math.round(p.similarity||0)}% similar</span></button>:<article className="result-photo-card" key={p.id}><button className="photo result-photo-open" onClick={()=>setViewer(p)} aria-label="Abrir foto"><img src={p.thumbnail_url||p.secure_url} alt={p.original_filename||'Foto encontrada'} loading="lazy" decoding="async"/><span>{Math.round(p.similarity||0)}%</span></button><div className="result-photo-actions"><button className="result-action secondary" onClick={()=>setViewer(p)}>↗ Abrir</button><button className="result-action primary" disabled={downloading===p.id} onClick={()=>downloadPhoto(p)}>{downloading===p.id?'Preparando...':'↓ Baixar'}</button></div></article>)}</div>{visible<matches.length&&<div className="load-more-wrap"><button className="btn alt load-more" onClick={()=>setVisible(v=>v+PAGE)}>Carregar mais {Math.min(PAGE,matches.length-visible)} fotos</button><small>{visible} de {matches.length} exibidas</small></div>}</>:<div className="private-empty"><div>◎</div><strong>Nenhuma foto é exibida antes da sua busca</strong><p>Faça a busca facial para localizar suas imagens.</p></div>}</section>}
 {staff&&<><div className="section-title"><div><span className="eyebrow">Acesso da equipe</span><h2>Todas as fotos</h2></div></div><div className="grid gallery-grid">{photos.map(p=><a className="photo" href={p.secure_url} target="_blank" rel="noreferrer" key={p.id}><img src={p.thumbnail_url||p.secure_url} loading="lazy" decoding="async" alt={p.original_filename||'Foto'}/><span>{p.original_filename||'Abrir foto'}</span></a>)}</div></>}
 {(viewer?.display_url||viewer?.secure_url)&&<div className="photo-viewer" role="dialog" aria-modal="true"><button className="viewer-close" onClick={()=>setViewer(null)}>×</button><div className="viewer-frame"><img src={viewer.display_url||viewer.secure_url} alt={viewer.original_filename||'Foto encontrada'}/></div><div className="viewer-bar"><div><strong>{viewer.original_filename||'Sua foto'}</strong><span>{Math.round(viewer.similarity||0)}% de similaridade</span></div><div className="viewer-actions"><a className="viewer-btn secondary" href={viewer.original_url||viewer.secure_url} target="_blank" rel="noreferrer">↗ Abrir original</a><button className="viewer-btn primary" disabled={downloading===viewer.id} onClick={()=>downloadPhoto(viewer)}>{downloading===viewer.id?'Preparando...':'↓ Baixar foto'}</button></div></div></div>}
 {faceOpen&&<div className="back face-back"><section className="panel face-modal"><div className="face-modal-head"><div><span className="eyebrow">Busca facial protegida</span><h2>Encontre você no evento</h2></div><button className="face-close" onClick={()=>setFaceOpen(false)}>×</button></div>{!preview?<div className="face-choices"><label className="face-choice primary"><strong>🤳</strong><span>Tirar uma selfie</span><small>De frente e com boa iluminação</small><input hidden type="file" accept="image/*,.heic,.heif" capture="user" onChange={choose}/></label><label className="face-choice"><strong>🖼️</strong><span>Escolher uma foto</span><small>JPG, PNG, HEIC e HEIF</small><input hidden type="file" accept="image/*,.heic,.heif" onChange={choose}/></label></div>:<div className="face-selected"><img className="face-preview" src={preview} alt="Foto selecionada"/><button className="btn alt" disabled={preparing} onClick={clearSelectedImage}>Escolher outra foto</button><div className="lgpd-consent-card"><strong>🛡️ Autorização para reconhecimento facial</strong><p>A imagem é usada somente nesta busca e não fica armazenada como referência.</p><label className="consent consent-lgpd"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Li e autorizo o uso temporário desta imagem.</span></label></div><button className="btn face-search-btn" disabled={!consent||searching||preparing||!image} onClick={faceSearch}>{preparing?'Preparando...':searching?'Buscando...':'Buscar minhas fotos'}</button></div>}{faceMsg&&<div className="face-status">{faceMsg}</div>}</section></div>}
 <style jsx>{`
 .paid-photo{width:100%;padding:0;display:block;cursor:pointer;background:#17171c}.paid-photo>img{position:absolute;inset:0;width:100%;height:100%;display:block}.paid-photo-backdrop{object-fit:cover;filter:blur(16px);transform:scale(1.12);opacity:.45}.paid-photo-image{object-fit:contain;z-index:1}.paid-photo span{position:absolute;left:9px;bottom:9px}.result-speed{display:block;color:#8fd8ad;margin-top:5px}.result-photo-card{background:#121217;border:1px solid #2d2d34;border-radius:18px;overflow:hidden}.result-photo-open{width:100%;border-radius:0;display:block;aspect-ratio:1/1;position:relative;padding:0;background:#17171c;overflow:hidden}.result-photo-open img,.gallery-grid>a.photo>img{width:100%;height:100%;object-fit:cover;display:block}.result-photo-open span{position:absolute;left:9px;bottom:9px;padding:5px 8px;border-radius:999px;background:#070709d9;font-size:10px}.result-photo-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:8px}.result-action{border-radius:10px;padding:9px;font-size:11px}.result-action.secondary{background:#25252c}.result-action.primary{background:#ff7417}.load-more-wrap{display:grid;place-items:center;gap:7px;margin:20px 0}.load-more-wrap small{color:#8b8b96}.photo-viewer{position:fixed;inset:0;z-index:120;background:#050506f5;display:flex;flex-direction:column;padding:max(18px,env(safe-area-inset-top)) 18px max(18px,env(safe-area-inset-bottom));backdrop-filter:blur(14px)}.viewer-close{position:absolute;right:18px;top:max(18px,env(safe-area-inset-top));z-index:2;width:44px;height:44px;border-radius:50%;background:#232329dd;font-size:28px;padding:0}.viewer-frame{flex:1;min-height:0;display:grid;place-items:center;padding:55px 0 14px}.viewer-frame img{max-width:100%;max-height:100%;object-fit:contain}.viewer-bar{width:min(980px,100%);margin:auto;display:flex;align-items:center;justify-content:space-between;gap:15px;padding:14px 16px;background:#15151add;border:1px solid #323239;border-radius:16px}.viewer-bar>div:first-child{display:grid}.viewer-bar span{font-size:10px;color:#9b9ba6}.viewer-actions{display:flex;gap:8px}.viewer-btn{display:inline-flex;align-items:center;justify-content:center;border-radius:11px;padding:11px 14px;text-decoration:none;font-size:12px;font-weight:850}.viewer-btn.secondary{background:#292930}.viewer-btn.primary{background:#ff7417}@media(max-width:650px){.private-match-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.result-photo-actions{display:none}.viewer-bar{display:grid}.viewer-actions{display:grid;grid-template-columns:1fr 1fr}.result-speed{font-size:10px}}
 `}</style></main>
}
