'use client';
import {ChangeEvent,useEffect,useState} from 'react';
import {SB,KEY,money,readSession} from '../../../lib/sb';
type Photo={id:string;secure_url?:string;preview_url?:string;original_filename?:string;similarity?:number};
const roleLabel:Record<string,string>={administrator:'Administrador',manager:'Gerente',photographer:'Fotógrafo',attendant:'Atendente'};
export default function EventPage({params}:{params:{slug:string}}){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[visitor,setVisitor]=useState<any>(null),[faceOpen,setFaceOpen]=useState(false),[image,setImage]=useState(''),[preview,setPreview]=useState(''),[preparing,setPreparing]=useState(false),[consent,setConsent]=useState(false),[searching,setSearching]=useState(false),[faceMsg,setFaceMsg]=useState(''),[consentWarning,setConsentWarning]=useState(''),[matches,setMatches]=useState<Photo[]>([]);
 useEffect(()=>{let v:any=null;try{v=JSON.parse(localStorage.getItem('semeando_visitor')||'null')}catch{};const admin=readSession();if(!v?.id&&!admin?.access_token){location.replace(`/cadastro?next=${encodeURIComponent(`/evento/${params.slug}`)}`);return}setVisitor(v);(async()=>{try{const headers:Record<string,string>={apikey:KEY};if(admin?.access_token)headers.Authorization=`Bearer ${admin.access_token}`;const r=await fetch(`${SB}/functions/v1/public-gallery?slug=${encodeURIComponent(params.slug)}`,{headers});const d=await r.json();if(!r.ok)throw new Error(d.error||'Evento não encontrado.');setData(d);if(v?.id){fetch(`${SB}/rest/v1/event_visitors`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({event_id:d.event.id,visitor_id:v.id})}).catch(()=>{})}}catch(e:any){setData({error:e.message})}finally{setLoading(false)}})()},[params.slug]);
 function isHeic(file:File){return /heic|heif/i.test(file.type)||/\.(heic|heif)$/i.test(file.name)}
 async function normalizeImage(file:File):Promise<Blob>{if(!isHeic(file))return file;const mod:any=await import('heic2any');const converted=await mod.default({blob:file,toType:'image/jpeg',quality:.88});return Array.isArray(converted)?converted[0]:converted}
 async function choose(e:ChangeEvent<HTMLInputElement>){
  const f=e.target.files?.[0];e.target.value='';if(!f)return;
  if(!f.type.startsWith('image/')&&!/\.(heic|heif|jpg|jpeg|png|webp)$/i.test(f.name)){setFaceMsg('Escolha um arquivo de imagem válido.');return}
  if(f.size>25*1024*1024){setFaceMsg('A imagem é muito grande. Escolha uma foto com até 25 MB.');return}
  if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);
  const objectUrl=URL.createObjectURL(f);setPreview(objectUrl);setImage('');setPreparing(true);setFaceMsg(isHeic(f)?'Convertendo a foto do iPhone...':'Preparando sua foto...');setMatches([]);
  try{const normalized=await normalizeImage(f);const url=await compress(normalized);setImage(url);if(isHeic(f)){if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);setPreview(url)}setFaceMsg('Foto pronta. Confira o rosto e toque em “Buscar minhas fotos”.')}
  catch(err){console.error('Falha ao preparar imagem',err);setImage('');setFaceMsg('Não conseguimos preparar esta foto. Tente tirar uma nova selfie diretamente pela câmera ou escolha outra imagem.')}
  finally{setPreparing(false)}
 }
 function fileToDataUrl(file:Blob):Promise<string>{return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onload=()=>resolve(String(rd.result||''));rd.onerror=()=>reject(rd.error);rd.readAsDataURL(file)})}
 async function compress(file:Blob):Promise<string>{
  const src=await fileToDataUrl(file);
  return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{try{const max=1280,scale=Math.min(1,max/Math.max(im.naturalWidth||im.width,im.naturalHeight||im.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round((im.naturalWidth||im.width)*scale));c.height=Math.max(1,Math.round((im.naturalHeight||im.height)*scale));const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas indisponível');ctx.drawImage(im,0,0,c.width,c.height);const out=c.toDataURL('image/jpeg',.84);if(!out||out==='data:,')throw new Error('Conversão falhou');resolve(out)}catch(e){reject(e)}};im.onerror=()=>reject(new Error('Formato de imagem não suportado pelo navegador'));im.src=src})
 }
 async function faceSearch(){if(!image||!consent||preparing)return;setSearching(true);setFaceMsg('Buscando suas fotos...');setMatches([]);try{const r=await fetch(`${SB}/functions/v1/face-search`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({event_slug:params.slug,image_base64:image,consent:true,visitor_id:visitor?.id||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível fazer a busca.');const found=d.photos||[];setMatches(found);setFaceMsg(found.length?`${found.length} foto(s) encontrada(s) para o rosto enviado.`:'Não encontramos fotos deste rosto neste evento. Tente outra imagem com o rosto bem visível.');if(found.length){setFaceOpen(false);setTimeout(()=>document.getElementById('minhas-fotos')?.scrollIntoView({behavior:'smooth',block:'start'}),120)}}catch(e:any){setFaceMsg(e.message)}finally{setSearching(false)}}
 function clearSelectedImage(){if(preview.startsWith('blob:'))URL.revokeObjectURL(preview);setPreview('');setImage('');setPreparing(false);setMatches([]);setFaceMsg('')}
 function resetFace(){clearSelectedImage();setConsent(false);setConsentWarning('')}
 function openFaceSearch(){if(!consent){setConsentWarning('Para continuar, marque a autorização de uso temporário da imagem para o reconhecimento facial.');setTimeout(()=>document.getElementById('lgpd-public-consent')?.scrollIntoView({behavior:'smooth',block:'center'}),40);return}setConsentWarning('');setFaceOpen(true)}
 if(loading)return <main className="wrap"><div className="panel">Carregando galeria...</div></main>;
 if(data?.error)return <main className="wrap"><div className="panel"><h1>Galeria indisponível</h1><p className="muted">{data.error}</p><a className="btn alt" href="/">Voltar</a></div></main>;
 const ev=data.event,paid=!!ev.is_paid,photos:Photo[]=data.photos||[],staff=data.viewer?.mode==='staff',staffRole=data.viewer?.role;
 return <main className="wrap event-page"><a className="event-back-link" href="/">← Todos os eventos</a><div className="event-hero" style={ev.cover_url?{backgroundImage:`linear-gradient(180deg,transparent,#0008),url(${ev.cover_url})`}:{}}/><div className="event-title-row"><div><span className="eyebrow">Galeria oficial</span><h1>{ev.title}</h1><p className="muted">{ev.location||'Igreja Semeando Amor'} • {data.total_photos||0} foto(s)</p></div>{staff?<span className="visitor-pill staff-pill">Equipe • {roleLabel[staffRole]||'Acesso autorizado'}</span>:visitor?.full_name&&<span className="visitor-pill">Olá, {visitor.full_name.split(' ')[0]} 👋</span>}</div>
 {staff&&<section className="staff-access-banner"><div className="staff-access-icon">🔓</div><div><strong>Visualização da equipe</strong><p>Seu acesso administrativo está ativo. Por isso, você pode visualizar todas as fotos deste álbum.</p></div></section>}
 {!staff&&paid&&<section className="paid-gallery-banner"><div><span className="paid-kicker">Galeria protegida</span><h2>Evento com fotos protegidas</h2><p>Depois da busca facial, você verá somente as prévias das fotos em que seu rosto foi localizado. Os arquivos originais permanecem protegidos.</p></div><div className="paid-prices">{ev.price_per_photo!=null&&<div><span>Por foto</span><strong>{money(ev.price_per_photo)}</strong></div>}{ev.full_album_price!=null&&<div><span>Álbum completo</span><strong>{money(ev.full_album_price)}</strong></div>}</div></section>}
 {!staff&&ev.face_search_enabled&&<section className="panel private-search-panel"><div className="private-search-head"><span className="eyebrow">Acesso pessoal e protegido</span><h2>Encontre somente as suas fotos</h2><p>Para proteger a imagem das pessoas que participaram do evento, o álbum completo não fica aberto ao público. Você localiza suas fotos usando uma selfie ou uma foto em que seu rosto apareça com nitidez.</p></div><div className="search-steps"><article><span>1</span><div><strong>Escolha uma imagem</strong><p>Tire uma selfie agora ou selecione uma foto do seu celular.</p></div></article><article><span>2</span><div><strong>Autorize a busca</strong><p>Marque a autorização de uso temporário da imagem para o reconhecimento facial.</p></div></article><article><span>3</span><div><strong>Veja suas fotos</strong><p>O sistema mostra somente as fotos localizadas a partir do rosto enviado.</p></div></article></div><div className="privacy-explain"><div className="privacy-explain-icon">🛡️</div><div><strong>Por que existe a autorização da LGPD?</strong><p>O reconhecimento facial utiliza características biométricas, que são dados pessoais sensíveis. Por isso, antes da busca, pedimos sua autorização específica. A imagem escolhida é usada somente para fazer a comparação naquele momento e não fica armazenada como sua foto de referência.</p><a href="/privacidade">Leia nossa Política de Privacidade →</a></div></div><div id="lgpd-public-consent" className="public-consent-box"><label className="consent public-consent-label"><input type="checkbox" checked={consent} onChange={e=>{setConsent(e.target.checked);if(e.target.checked)setConsentWarning('')}}/><span><b>Autorizo a busca facial</b><small>Li a explicação acima e autorizo o uso temporário da selfie ou foto que eu escolher exclusivamente para localizar minhas imagens neste evento.</small></span></label>{consentWarning&&<div className="consent-warning" role="alert" aria-live="assertive">⚠️ {consentWarning}</div>}</div><button className="btn face-main-btn private-face-btn" onClick={openFaceSearch}>◎ Encontrar minhas fotos</button></section>}
 {!staff&&!ev.face_search_enabled&&<section className="panel private-search-panel unavailable-search"><span className="eyebrow">Galeria protegida</span><h2>A busca das suas fotos ainda está sendo preparada</h2><p className="muted">As fotos deste evento não ficam abertas ao público. Assim que o reconhecimento facial estiver ativado, você poderá enviar uma selfie ou uma foto para localizar somente as suas imagens.</p></section>}
 {!staff&&ev.face_search_enabled&&<section id="minhas-fotos" className="private-result-section"><div className="section-title"><div><span className="eyebrow">Seu resultado</span><h2>{matches.length?'Suas fotos encontradas':'Suas fotos aparecerão aqui'}</h2></div>{matches.length>0&&<button className="btn alt" onClick={()=>{resetFace();setFaceOpen(true)}}>Fazer nova busca</button>}</div>{faceMsg&&!faceOpen&&<div className="face-status public-face-status">{faceMsg}</div>}{matches.length>0?<div className="grid gallery-grid private-match-grid">{matches.map(p=>paid?<div className="photo paid-photo" style={{backgroundImage:`url(${p.preview_url})`}} key={p.id}><span>{Math.round(p.similarity||0)}% similar</span></div>:<a className="photo" style={{backgroundImage:`url(${p.secure_url})`}} href={p.secure_url} target="_blank" rel="noreferrer" key={p.id}><span>{Math.round(p.similarity||0)}% similar • Abrir foto</span></a>)}</div>:<div className="private-empty"><div>◎</div><strong>Nenhuma foto é exibida antes da sua busca</strong><p>Toque em “Encontrar minhas fotos”, envie uma imagem do seu rosto e autorize o uso temporário para a comparação.</p></div>}</section>}
 {staff&&<><div className="section-title"><div><span className="eyebrow">Acesso da equipe</span><h2>Todas as fotos</h2></div></div><div className="grid gallery-grid">{photos.map(p=><a className="photo" style={{backgroundImage:`url(${p.secure_url})`}} href={p.secure_url} target="_blank" rel="noreferrer" key={p.id}><span>{p.original_filename||'Abrir foto'}</span></a>)}</div></>}
 {faceOpen&&<div className="back face-back"><section className="panel face-modal"><div className="face-modal-head"><div><span className="eyebrow">Busca facial protegida</span><h2>Encontre você no evento</h2></div><button className="face-close" onClick={()=>setFaceOpen(false)}>×</button></div><div className="face-mini-guide"><b>Como funciona:</b> escolha uma foto com seu rosto bem visível. Fotos HEIC/HEIF do iPhone são convertidas automaticamente para a busca.</div>{!preview?<div className="face-choices"><label className="face-choice primary"><strong>🤳</strong><span>Tirar uma selfie</span><small>De frente e com boa iluminação</small><input hidden type="file" accept="image/*,.heic,.heif" capture="user" onChange={choose}/></label><label className="face-choice"><strong>🖼️</strong><span>Escolher uma foto</span><small>JPG, PNG, HEIC e HEIF são aceitos</small><input hidden type="file" accept="image/*,.heic,.heif" onChange={choose}/></label></div>:<div className="face-selected"><img className="face-preview" src={preview} alt="Foto selecionada"/><button className="btn alt" disabled={preparing} onClick={clearSelectedImage}>Escolher outra foto</button><div className="lgpd-consent-card"><div className="lgpd-title"><span>🛡️</span><div><strong>Autorização para reconhecimento facial</strong><small>Proteção de dados • LGPD</small></div></div><p>Precisamos da sua autorização porque a busca compara características do seu rosto, que são dados biométricos sensíveis. A imagem enviada é utilizada somente durante esta busca para localizar fotos correspondentes e não é armazenada como imagem de referência.</p><label className="consent consent-lgpd"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span><b>Li e autorizo</b> o uso temporário desta imagem exclusivamente para localizar minhas fotos neste evento.</span></label><a href="/privacidade" target="_blank" rel="noreferrer">Entenda como seus dados são tratados →</a></div><button className="btn face-search-btn" disabled={!consent||searching||preparing||!image} onClick={faceSearch}>{preparing?(isHeic as any)?'Preparando a foto...':'Preparando a foto...':searching?'Buscando suas fotos...':!image?'Aguardando processamento...':consent?'Buscar minhas fotos':'Marque a autorização para continuar'}</button></div>}{faceMsg&&<div className="face-status">{faceMsg}</div>}</section></div>}
 </main>
}
