'use client';
import {FormEvent,useEffect,useState} from 'react';
import AccountMenu from '../components/AccountMenu';
import {KEY,SB,readSession} from '../../lib/sb';

type UserInfo={email?:string;user_metadata?:{full_name?:string;name?:string;avatar_url?:string}};
export default function Conta(){
 const [user,setUser]=useState<UserInfo|null>(null),[name,setName]=useState(''),[avatar,setAvatar]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[tab,setTab]=useState('perfil');
 useEffect(()=>{const q=new URLSearchParams(location.search).get('tab');if(q)setTab(q);const s=readSession();if(!s?.access_token){location.href='/acesso';return}(async()=>{const r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});const d=await r.json();if(r.ok){setUser(d);setName(d.user_metadata?.full_name||d.user_metadata?.name||'');setAvatar(d.user_metadata?.avatar_url||'')}})()},[]);
 async function updateMeta(data:any){const s=readSession();if(!s?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({data})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Não foi possível atualizar sua conta.');setUser(d);return d}
 async function saveProfile(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await updateMeta({...(user?.user_metadata||{}),full_name:name.trim(),avatar_url:avatar});setMsg('Perfil atualizado com sucesso.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function uploadAvatar(file?:File){if(!file)return;setBusy(true);setMsg('Enviando sua foto...');try{const fd=new FormData();fd.append('file',file);fd.append('upload_preset','semeando_memorias');fd.append('folder','semeando-memorias/usuarios');const r=await fetch('https://api.cloudinary.com/v1_1/to3hnwdl/image/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Falha ao enviar a foto.');setAvatar(d.secure_url);await updateMeta({...(user?.user_metadata||{}),full_name:name.trim(),avatar_url:d.secure_url});setMsg('Foto do perfil atualizada.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function savePassword(e:FormEvent){e.preventDefault();if(password.length<8){setMsg('A senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){setMsg('As senhas não coincidem.');return}setBusy(true);setMsg('');try{const s=readSession();if(!s?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Não foi possível alterar a senha.');setPassword('');setConfirm('');setMsg('Senha alterada com sucesso.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="account-page"><AccountMenu/><section className="account-shell"><a className="back" href={document.referrer.includes('/developer')?'/developer':'/admin'}>← Voltar</a><div className="account-title"><span>MINHA CONTA</span><h1>Perfil e segurança</h1><p>Personalize sua identificação e gerencie seu acesso à plataforma.</p></div><div className="account-tabs"><button className={tab==='perfil'?'active':''} onClick={()=>setTab('perfil')}>Meu acesso</button><button className={tab==='seguranca'?'active':''} onClick={()=>setTab('seguranca')}>Segurança</button><button className={tab==='suporte'?'active':''} onClick={()=>setTab('suporte')}>Suporte</button></div>{msg&&<div className="account-notice">{msg}</div>}{tab==='perfil'&&<form className="account-card" onSubmit={saveProfile}><div className="avatar-row">{avatar?<img src={avatar} alt="Foto do usuário"/>:<div>{(name||user?.email||'U').charAt(0).toUpperCase()}</div>}<label>Trocar foto<input hidden type="file" accept="image/*" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label></div><label>Nome de exibição<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label><label>E-mail<input value={user?.email||''} disabled/></label><button disabled={busy}>{busy?'Salvando...':'Salvar perfil'}</button></form>}{tab==='seguranca'&&<form className="account-card" onSubmit={savePassword}><h2>Alterar senha</h2><p>Use uma senha exclusiva com pelo menos 8 caracteres.</p><label>Nova senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button disabled={busy}>{busy?'Salvando...':'Atualizar senha'}</button></form>}{tab==='suporte'&&<section className="account-card"><h2>Suporte da plataforma</h2><p>Para dúvidas operacionais, problemas de acesso ou suporte aos clientes, fale com a equipe responsável pelo Semeando Memórias.</p><a className="support" href="mailto:legacysolar07@gmail.com?subject=Suporte%20Semeando%20Memórias">✉ Enviar e-mail ao suporte</a><small>Ao pedir suporte, informe o nome da organização e descreva o que aconteceu.</small></section>}</section><style jsx>{`
.account-page{min-height:100vh;background:#090b0e;color:#f5f6f8;padding:96px 18px 50px;font-family:system-ui,-apple-system,sans-serif}.account-shell{width:min(760px,100%);margin:auto}.back{color:#a4a9b2;text-decoration:none;font-size:13px}.account-title{margin:22px 0}.account-title span{color:#ff8a3d;font-size:11px;font-weight:900;letter-spacing:.18em}.account-title h1{font-size:38px;margin:8px 0 5px}.account-title p{color:#969ca6}.account-tabs{display:flex;gap:8px;margin:22px 0}.account-tabs button{border:1px solid #30343b;background:#15181d;color:#aeb3bb;border-radius:12px;padding:11px 14px;font-weight:800}.account-tabs .active{background:#ff7417;color:#fff;border-color:#ff7417}.account-card{background:#12151a;border:1px solid #30343c;border-radius:22px;padding:22px;display:grid;gap:16px}.account-card h2{margin:0}.account-card p,.account-card small{color:#969ca6}.account-card label{display:grid;gap:7px;font-size:12px;color:#aab0b9;font-weight:800}.account-card input{background:#090b0e;border:1px solid #343842;border-radius:12px;color:#fff;padding:14px;font-size:14px}.account-card button,.support{background:#ff7417;color:#fff;border:0;border-radius:12px;padding:13px 16px;font-weight:900;text-decoration:none;text-align:center}.avatar-row{display:flex;align-items:center;gap:16px}.avatar-row img,.avatar-row>div{width:82px;height:82px;border-radius:22px;object-fit:cover;background:#ff7417;display:grid;place-items:center;font-size:30px;font-weight:950}.avatar-row label{background:#242830;border-radius:11px;padding:11px 14px;color:#fff;cursor:pointer}.account-notice{background:#2b1b12;border:1px solid #743a17;color:#ffd6bd;border-radius:13px;padding:12px 14px;margin-bottom:14px}@media(max-width:600px){.account-title h1{font-size:31px}.account-tabs{overflow:auto}.account-card{padding:17px}}
`}</style></main>
}
