'use client';
import {FormEvent,useEffect,useState} from 'react';
import AccountMenu from '../components/AccountMenu';
import {KEY,SB,readSession} from '../../lib/sb';

type UserInfo={email?:string;user_metadata?:{full_name?:string;name?:string;avatar_url?:string}};
export default function Conta(){
 const [user,setUser]=useState<UserInfo|null>(null),[name,setName]=useState(''),[avatar,setAvatar]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[tab,setTab]=useState('perfil'),[backHref,setBackHref]=useState('/admin');
 useEffect(()=>{const q=new URLSearchParams(location.search).get('tab');if(q)setTab(q);if(document.referrer.includes('/developer'))setBackHref('/developer');const s=readSession();if(!s?.access_token){location.href='/acesso';return}(async()=>{const r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`}});const d=await r.json();if(r.ok){setUser(d);setName(d.user_metadata?.full_name||d.user_metadata?.name||'');setAvatar(d.user_metadata?.avatar_url||'')}})()},[]);
 async function updateMeta(data:any){const s=readSession();if(!s?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({data})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Não foi possível atualizar sua conta.');setUser(d);window.dispatchEvent(new CustomEvent('semeando-profile-updated',{detail:d}));return d}
 async function saveProfile(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');try{await updateMeta({...(user?.user_metadata||{}),full_name:name.trim(),avatar_url:avatar});setMsg('Perfil atualizado com sucesso.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function uploadAvatar(file?:File){if(!file)return;setBusy(true);setMsg('Enviando sua foto...');try{if(file.size>8*1024*1024)throw new Error('Escolha uma imagem com até 8 MB.');const fd=new FormData();fd.append('file',file);fd.append('upload_preset','semeando_memorias');fd.append('folder','semeando-memorias/usuarios');const r=await fetch('https://api.cloudinary.com/v1_1/to3hnwdl/image/upload',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Falha ao enviar a foto.');setAvatar(d.secure_url);await updateMeta({...(user?.user_metadata||{}),full_name:name.trim(),avatar_url:d.secure_url});setMsg('Foto do perfil atualizada.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function removeAvatar(){setBusy(true);setMsg('');try{setAvatar('');await updateMeta({...(user?.user_metadata||{}),full_name:name.trim(),avatar_url:''});setMsg('Foto removida.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function savePassword(e:FormEvent){e.preventDefault();if(password.length<8){setMsg('A senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){setMsg('As senhas não coincidem.');return}setBusy(true);setMsg('');try{const s=readSession();if(!s?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:KEY,Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Não foi possível alterar a senha.');setPassword('');setConfirm('');setMsg('Senha alterada com sucesso.')}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main className="account-page"><AccountMenu/><section className="account-shell"><a className="back" href={backHref}>← Voltar</a><div className="account-title"><span>MINHA CONTA</span><h1>Perfil e segurança</h1><p>Personalize sua identificação e gerencie seu acesso à plataforma.</p></div><div className="account-tabs"><button className={tab==='perfil'?'active':''} onClick={()=>setTab('perfil')}>Meu acesso</button><button className={tab==='seguranca'?'active':''} onClick={()=>setTab('seguranca')}>Segurança</button><button className={tab==='suporte'?'active':''} onClick={()=>setTab('suporte')}>Suporte</button></div>{msg&&<div className="account-notice">{msg}</div>}{tab==='perfil'&&<form className="account-card" onSubmit={saveProfile}><div className="profile-heading"><div><span>FOTO DO PERFIL</span><h2>Personalize sua conta</h2><p>Essa imagem aparece no menu superior e identifica seu acesso nas telas de gestão.</p></div></div><div className="avatar-editor"><div className="avatar-preview">{avatar?<img src={avatar} alt="Foto do usuário"/>:<span>{(name||user?.email||'U').charAt(0).toUpperCase()}</span>}</div><div className="avatar-actions"><label className="upload-main">📷 Escolher foto<input hidden type="file" accept="image/*" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label><label className="upload-alt">🤳 Tirar foto<input hidden type="file" accept="image/*" capture="user" onChange={e=>uploadAvatar(e.target.files?.[0])}/></label>{avatar&&<button type="button" className="remove-photo" onClick={removeAvatar}>Remover foto</button>}</div></div><label>Nome de exibição<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome"/></label><label>E-mail<input value={user?.email||''} disabled/></label><button className="save-btn" disabled={busy}>{busy?'Salvando...':'Salvar perfil'}</button></form>}{tab==='seguranca'&&<form className="account-card" onSubmit={savePassword}><h2>Alterar senha</h2><p>Use uma senha exclusiva com pelo menos 8 caracteres.</p><label>Nova senha<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="save-btn" disabled={busy}>{busy?'Salvando...':'Atualizar senha'}</button></form>}{tab==='suporte'&&<section className="account-card"><h2>Suporte da plataforma</h2><p>Para dúvidas operacionais, problemas de acesso ou suporte aos clientes, fale com a equipe responsável pelo Semeando Memórias.</p><a className="support" href="mailto:legacysolar07@gmail.com?subject=Suporte%20Semeando%20Memórias">✉ Enviar e-mail ao suporte</a><small>Ao pedir suporte, informe o nome da organização e descreva o que aconteceu.</small></section>}</section><style jsx>{`
.account-page{min-height:100vh;background:#090b0e;color:#f7f8fa;padding:96px 18px 50px;font-family:system-ui,-apple-system,sans-serif}.account-shell{width:min(760px,100%);margin:auto}.back{color:#d2d6dc;text-decoration:none;font-size:14px;font-weight:750}.account-title{margin:22px 0}.account-title span,.profile-heading span{color:#ff8a3d;font-size:11px;font-weight:950;letter-spacing:.18em}.account-title h1{font-size:40px;margin:8px 0 5px;color:#fff}.account-title p{color:#c0c5ce;font-size:15px}.account-tabs{display:flex;gap:8px;margin:22px 0}.account-tabs button{border:1px solid #3a404a;background:#171a20;color:#d8dce2;border-radius:12px;padding:12px 16px;font-weight:850}.account-tabs .active{background:#ff7417;color:#fff;border-color:#ff7417}.account-card{background:#13171d;border:1px solid #363d47;border-radius:24px;padding:24px;display:grid;gap:18px;box-shadow:0 22px 60px #0005}.account-card h2{margin:0;color:#fff}.account-card p,.account-card small{color:#b0b6c0}.profile-heading h2{font-size:24px;margin:6px 0}.profile-heading p{margin:0;line-height:1.5}.account-card label{display:grid;gap:7px;font-size:13px;color:#d2d6dc;font-weight:850}.account-card input{background:#0a0d11;border:1px solid #3a414c;border-radius:13px;color:#fff;padding:15px;font-size:15px}.account-card input:disabled{opacity:1;color:#aeb4be;background:#101319}.save-btn,.support{background:#ff7417;color:#fff;border:0;border-radius:13px;padding:14px 16px;font-weight:950;text-decoration:none;text-align:center;font-size:14px}.avatar-editor{display:flex;align-items:center;gap:20px;background:#0d1015;border:1px solid #2d333c;border-radius:18px;padding:18px}.avatar-preview,.avatar-preview img{width:104px;height:104px;border-radius:26px}.avatar-preview{flex:0 0 auto;background:linear-gradient(135deg,#ff7417,#d64f00);display:grid;place-items:center;overflow:hidden;box-shadow:0 12px 30px #ff74172a}.avatar-preview img{object-fit:cover}.avatar-preview span{font-size:42px;font-weight:950;color:#fff}.avatar-actions{display:flex;gap:9px;flex-wrap:wrap}.avatar-actions label,.avatar-actions button{cursor:pointer;border-radius:11px;padding:11px 13px;font-size:12px;font-weight:900}.upload-main{background:#ff7417;color:#fff}.upload-alt{background:#272c34;color:#fff;border:1px solid #3b424d}.remove-photo{background:transparent;color:#ffaaa3;border:1px solid #67343a}.account-notice{background:#2b1b12;border:1px solid #743a17;color:#ffd6bd;border-radius:13px;padding:12px 14px;margin-bottom:14px}@media(max-width:600px){.account-page{padding:88px 16px 40px}.account-title h1{font-size:34px}.account-title p{font-size:14px}.account-tabs{overflow:auto}.account-tabs button{white-space:nowrap}.account-card{padding:18px}.avatar-editor{align-items:flex-start;flex-direction:column}.avatar-preview,.avatar-preview img{width:116px;height:116px}.avatar-actions{width:100%}.avatar-actions label,.avatar-actions button{flex:1 1 auto;text-align:center}}
`}</style></main>
}
