'use client';
import {useEffect,useMemo,useState} from 'react';
import {SB,adminHeaders,session} from '../../../lib/sb';
import s from './leads.module.css';

type Lead={id:string;full_name:string;email:string|null;cpf:string|null;birth_date:string|null;housing_type:string;street:string;neighborhood:string;city:string;whatsapp:string;has_solar:boolean|null;whatsapp_verified_at:string|null;email_validation_status:string|null;marketing_consent:boolean;created_at:string};
const houseLabel=(v:string)=>v==='house'?'Casa':v==='apartment'?'Apartamento':'Outro';
const yesNo=(v:boolean|null)=>v===true?'Sim':v===false?'Não':'';
const esc=(v:any)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const fmtDate=(v:string|null)=>{if(!v)return '—';const d=new Date(v.length===10?v+'T12:00:00':v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR')};
const fmtArrival=(v:string)=>{const d=new Date(v);return {date:d.toLocaleDateString('pt-BR'),time:d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}};
export default function Leads(){
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [q,setQ]=useState(''),[housing,setHousing]=useState(''),[solar,setSolar]=useState(''),[marketing,setMarketing]=useState(''),[city,setCity]=useState(''),[neighborhood,setNeighborhood]=useState(''),[street,setStreet]=useState('');
 useEffect(()=>{(async()=>{const ss=await session();if(!ss?.access_token){location.href='/admin/login';return}try{const r=await fetch(`${SB}/rest/v1/visitors?select=id,full_name,email,cpf,birth_date,housing_type,street,neighborhood,city,whatsapp,has_solar,whatsapp_verified_at,email_validation_status,marketing_consent,created_at&order=created_at.desc`,{headers:await adminHeaders(false)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível carregar os leads.');setLeads(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}})()},[]);
 const filtered=useMemo(()=>{const n=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return leads.filter(l=>{const text=n([l.full_name,l.email,l.cpf,l.whatsapp,l.street,l.neighborhood,l.city].join(' '));if(q&&!text.includes(n(q)))return false;if(housing&&l.housing_type!==housing)return false;if(solar==='yes'&&l.has_solar!==true)return false;if(solar==='no'&&l.has_solar!==false)return false;if(marketing==='yes'&&!l.marketing_consent)return false;if(marketing==='no'&&l.marketing_consent)return false;if(city&&!n(l.city).includes(n(city)))return false;if(neighborhood&&!n(l.neighborhood).includes(n(neighborhood)))return false;if(street&&!n(l.street).includes(n(street)))return false;return true})},[leads,q,housing,solar,marketing,city,neighborhood,street]);
 const activeFilters=[q,housing,solar,marketing,city,neighborhood,street].filter(Boolean).length;
 function clear(){setQ('');setHousing('');setSolar('');setMarketing('');setCity('');setNeighborhood('');setStreet('')}
 function exportExcel(){const headers=['Data de chegada','Nome completo','Data de nascimento','CPF','WhatsApp','WhatsApp verificado','E-mail','Validação e-mail','Tipo de moradia','Rua','Bairro','Cidade','Possui energia solar','Autorizou contato Legacy Solar'];const rows=filtered.map(l=>[new Date(l.created_at).toLocaleString('pt-BR'),l.full_name,fmtDate(l.birth_date),l.cpf||'',l.whatsapp,l.whatsapp_verified_at?'Sim':'Não',l.email||'',l.email_validation_status||'',houseLabel(l.housing_type),l.street,l.neighborhood,l.city,yesNo(l.has_solar),l.marketing_consent?'Sim':'Não']);const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Leads"><Table>${[headers,...rows].map(r=>`<Row>${r.map(c=>`<Cell><Data ss:Type="String">${esc(c)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;const blob=new Blob([xml],{type:'application/vnd.ms-excel;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`semeando-leads-${new Date().toISOString().slice(0,10)}.xls`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 return <main className="admin admin-pro"><section className={`admin-content ${s.page}`}>
  <header className={s.hero}><div><a href="/admin" className="muted">← Painel administrativo</a><span className="eyebrow" style={{marginTop:14}}>Gestão de contatos</span><h1 className={s.heroTitle}>Leads captados</h1><p className={s.heroText}>Segmentação profissional dos cadastros recebidos pelo Semeando Memórias.</p></div><div className={s.heroActions}><button className={`btn alt ${s.clearBtn}`} onClick={clear}>Limpar filtros</button><button className="btn" onClick={exportExcel} disabled={!filtered.length}>↓ Baixar Excel ({filtered.length})</button></div></header>
  {error&&<p className="notice">{error}</p>}{loading?<div className="panel">Carregando leads...</div>:<>
  <div className={s.metrics}><article className={s.metric}><span>Total cadastrado</span><strong>{leads.length}</strong></article><article className={s.metric}><span>No filtro atual</span><strong>{filtered.length}</strong></article><article className={s.metric}><span>Autorizaram contato</span><strong>{filtered.filter(x=>x.marketing_consent).length}</strong></article></div>
  <section className={s.filterCard}><div className={s.filterHead}><div><h2>Filtros de segmentação</h2><p>Combine os campos abaixo para encontrar exatamente o público desejado.</p></div>{activeFilters>0&&<span className={s.activeBadge}>{activeFilters} filtro{activeFilters>1?'s':''} ativo{activeFilters>1?'s':''}</span>}</div>
   <div className={s.filterGrid}><label className={`${s.field} ${s.search}`}><span>Busca geral</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nome, CPF, WhatsApp, e-mail ou endereço"/></label><label className={`${s.field} ${s.smallField}`}><span>Tipo de moradia</span><select value={housing} onChange={e=>setHousing(e.target.value)}><option value="">Todos</option><option value="house">Casa</option><option value="apartment">Apartamento</option><option value="other">Outro</option></select></label><label className={`${s.field} ${s.smallField}`}><span>Energia solar</span><select value={solar} onChange={e=>setSolar(e.target.value)}><option value="">Todos</option><option value="yes">Possui</option><option value="no">Não possui</option></select></label><label className={`${s.field} ${s.mediumField}`}><span>Rua</span><input value={street} onChange={e=>setStreet(e.target.value)} placeholder="Ex.: Clóvis Arrault"/></label><label className={`${s.field} ${s.mediumField}`}><span>Bairro</span><input value={neighborhood} onChange={e=>setNeighborhood(e.target.value)} placeholder="Ex.: Goitacazes"/></label><label className={`${s.field} ${s.mediumField}`}><span>Cidade</span><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ex.: Campos dos Goytacazes"/></label><label className={`${s.field} ${s.smallField}`}><span>Contato Legacy Solar</span><select value={marketing} onChange={e=>setMarketing(e.target.value)}><option value="">Todos</option><option value="yes">Autorizado</option><option value="no">Não autorizado</option></select></label></div>
   <div className={s.filterFooter}><span className={s.resultText}>Exibindo <b>{filtered.length}</b> de <b>{leads.length}</b> cadastros</span>{activeFilters>0&&<button className={`btn alt ${s.clearBtn}`} onClick={clear}>Remover todos os filtros</button>}</div></section>
  <div className={s.tableWrap}><table className={s.table}><thead><tr><th>Chegada</th><th>Nome</th><th>Nascimento / CPF</th><th>WhatsApp</th><th>E-mail</th><th>Moradia</th><th>Endereço</th><th>Solar</th><th>Marketing</th></tr></thead><tbody>{filtered.map(l=>{const a=fmtArrival(l.created_at);return <tr key={l.id}><td className={s.arrival}><strong>{a.date}</strong><span>{a.time}</span></td><td><b className={s.name}>{l.full_name}</b></td><td>{fmtDate(l.birth_date)}<span className={s.sub}>{l.cpf||'—'}</span></td><td>{l.whatsapp}<span className={s.sub}>{l.whatsapp_verified_at?'✓ Verificado':'Não verificado'}</span></td><td>{l.email||'—'}<span className={s.sub}>{l.email_validation_status||''}</span></td><td>{houseLabel(l.housing_type)}</td><td><b>{l.street}</b><span className={s.sub}>{l.neighborhood} • {l.city}</span></td><td>{yesNo(l.has_solar)||'—'}</td><td>{l.marketing_consent?<span className={s.pillOn}>Autorizado</span>:<span className={s.pillOff}>Não autorizado</span>}</td></tr>})}</tbody></table>{!filtered.length&&<div className={s.empty}>Nenhum lead encontrado com os filtros atuais.</div>}</div>
  <div className={s.mobileCards}>{filtered.map(l=>{const a=fmtArrival(l.created_at);return <article className={s.leadCard} key={l.id}><div className={s.leadCardTop}><div><h3>{l.full_name}</h3><small>{l.email||'Sem e-mail'}</small></div><div className={s.arrival}><strong>{a.date}</strong><span>{a.time}</span></div></div><div className={s.leadMeta}><div><span>Nascimento</span><b>{fmtDate(l.birth_date)}</b></div><div><span>WhatsApp</span><b>{l.whatsapp}</b></div><div><span>Moradia</span><b>{houseLabel(l.housing_type)}</b></div><div><span>CPF</span><b>{l.cpf||'—'}</b></div></div><div className={s.leadAddress}>{l.street} • {l.neighborhood} • {l.city}</div><div className={s.statusRow}><span className={s.pillNeutral}>Solar: {yesNo(l.has_solar)||'—'}</span>{l.marketing_consent?<span className={s.pillOn}>Contato autorizado</span>:<span className={s.pillOff}>Sem autorização comercial</span>}</div></article>})}{!filtered.length&&<div className={s.empty}>Nenhum lead encontrado com os filtros atuais.</div>}</div>
  </>}</section></main>
}
