'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {SB,adminHeaders,session} from '../../../lib/sb';
import s from './leads.module.css';

type Lead={id:string;full_name:string;email:string|null;cpf:string|null;birth_date:string|null;housing_type:string;street:string;neighborhood:string;city:string;whatsapp:string;has_solar:boolean|null;marketing_consent:boolean;created_at:string;source_type?:string|null;source_label?:string|null;source_event_id?:string|null;source_campaign?:string|null;utm_source?:string|null;utm_medium?:string|null;utm_campaign?:string|null;utm_content?:string|null;utm_term?:string|null;referrer?:string|null;landing_path?:string|null};
const n=(v:any)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const fmt=(v:string)=>new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'});
const fmtDate=(v?:string|null)=>v?new Date(v.length===10?v+'T12:00:00':v).toLocaleDateString('pt-BR'):'—';
const house=(v:string)=>v==='house'?'Casa':v==='apartment'?'Apartamento':'Outro';
const pct=(a:number,b:number)=>b?Math.round(a/b*100):0;
const sourceName=(l:Lead)=>String(l.source_label||l.source_campaign||l.utm_campaign||l.utm_source||l.source_type||'Não identificado').trim()||'Não identificado';
const sourceDetail=(l:Lead)=>[l.source_type,l.utm_source,l.utm_medium].filter(Boolean).join(' • ')||'Origem não identificada';

export default function Leads(){
 const [leads,setLeads]=useState<Lead[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [q,setQ]=useState(''),[city,setCity]=useState(''),[neighborhood,setNeighborhood]=useState(''),[source,setSource]=useState(''),[solar,setSolar]=useState(''),[marketing,setMarketing]=useState('');
 const [seen,setSeen]=useState<string[]>([]),[selected,setSelected]=useState<Lead|null>(null),[deleting,setDeleting]=useState(false);const listRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{try{setSeen(JSON.parse(localStorage.getItem('semeando_leads_seen')||'[]'))}catch{};(async()=>{const ss=await session();if(!ss?.access_token){location.href='/admin/login';return}try{const r=await fetch(`${SB}/rest/v1/visitors?select=id,full_name,email,cpf,birth_date,housing_type,street,neighborhood,city,whatsapp,has_solar,marketing_consent,created_at,source_type,source_label,source_event_id,source_campaign,utm_source,utm_medium,utm_campaign,utm_content,utm_term,referrer,landing_path&order=created_at.desc`,{headers:await adminHeaders(false)});const d=await r.json();if(!r.ok)throw new Error(d.message||'Não foi possível carregar os leads.');setLeads(d)}catch(e:any){setError(e.message)}finally{setLoading(false)}})()},[]);
 const unread=useMemo(()=>leads.filter(l=>!seen.includes(l.id)),[leads,seen]);
 const filtered=useMemo(()=>leads.filter(l=>{if(q&&!n([l.full_name,l.email,l.cpf,l.whatsapp,l.street,l.neighborhood,l.city,sourceName(l),l.source_campaign,l.utm_source,l.utm_campaign].join(' ')).includes(n(q)))return false;if(city&&n(l.city)!==n(city))return false;if(neighborhood&&n(l.neighborhood)!==n(neighborhood))return false;if(source&&n(sourceName(l))!==n(source))return false;if(solar==='yes'&&l.has_solar!==true)return false;if(solar==='no'&&l.has_solar!==false)return false;if(marketing==='yes'&&!l.marketing_consent)return false;if(marketing==='no'&&l.marketing_consent)return false;return true}),[leads,q,city,neighborhood,source,solar,marketing]);
 const byNeighborhood=useMemo(()=>Object.entries(leads.reduce((a:any,l)=>{const k=(l.neighborhood||'Não informado').trim()||'Não informado';a[k]=(a[k]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,8) as [string,number][],[leads]);
 const byCity=useMemo(()=>Object.entries(leads.reduce((a:any,l)=>{const k=(l.city||'Não informado').trim()||'Não informado';a[k]=(a[k]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6) as [string,number][],[leads]);
 const bySource=useMemo(()=>Object.entries(leads.reduce((a:any,l)=>{const k=sourceName(l);a[k]=(a[k]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,8) as [string,number][],[leads]);
 const byCampaign=useMemo(()=>Object.entries(leads.reduce((a:any,l)=>{const k=String(l.source_campaign||l.utm_campaign||'Sem campanha').trim()||'Sem campanha';a[k]=(a[k]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6) as [string,number][],[leads]);
 function focusGeo(kind:'city'|'neighborhood',value:string){if(kind==='city'){setCity(value);setNeighborhood('')}else{setNeighborhood(value);setCity('')}setTimeout(()=>listRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 function focusSource(value:string){setSource(value);setTimeout(()=>listRef.current?.scrollIntoView({behavior:'smooth',block:'start'}),80)}
 function markSeen(id:string){if(seen.includes(id))return;const next=[...seen,id];setSeen(next);localStorage.setItem('semeando_leads_seen',JSON.stringify(next))}
 function openLead(l:Lead){markSeen(l.id);setSelected(l)}
 function markAll(){const ids=leads.map(l=>l.id);setSeen(ids);localStorage.setItem('semeando_leads_seen',JSON.stringify(ids))}
 function clear(){setQ('');setCity('');setNeighborhood('');setSource('');setSolar('');setMarketing('')}
 async function deleteLead(){if(!selected||deleting)return;if(!confirm(`Excluir permanentemente o lead “${selected.full_name}”? Esta ação não pode ser desfeita.`))return;setDeleting(true);setError('');try{const ss=await session();if(!ss?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/functions/v1/admin-leads`,{method:'POST',headers:{...(await adminHeaders(true)),Authorization:`Bearer ${ss.access_token}`},body:JSON.stringify({action:'delete_lead',id:selected.id})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Não foi possível excluir o lead.');const id=selected.id;setLeads(x=>x.filter(l=>l.id!==id));const nextSeen=seen.filter(x=>x!==id);setSeen(nextSeen);localStorage.setItem('semeando_leads_seen',JSON.stringify(nextSeen));setSelected(null)}catch(e:any){setError(e.message)}finally{setDeleting(false)}}
 function exportCsv(){const head=['Nome','WhatsApp','E-mail','Rua','Bairro','Cidade','Origem','Campanha','UTM Source','UTM Medium','Solar','Marketing','Chegada'];const rows=filtered.map(l=>[l.full_name,l.whatsapp,l.email||'',l.street,l.neighborhood,l.city,sourceName(l),l.source_campaign||l.utm_campaign||'',l.utm_source||'',l.utm_medium||'',l.has_solar===true?'Sim':l.has_solar===false?'Não':'',l.marketing_consent?'Sim':'Não',fmt(l.created_at)]);const csv='\ufeff'+[head,...rows].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='leads-semeando.csv';a.click()}
 return <main className={s.page}>
  <header className={s.hero}><div><a href="/admin">← Painel administrativo</a><span>VISÃO COMERCIAL</span><h1>Leads</h1><p>Veja quem chegou, de onde veio e onde estão as maiores concentrações.</p></div><div className={s.heroActions}>{unread.length>0&&<button className={s.secondary} onClick={markAll}>Marcar novos como vistos</button>}<button onClick={exportCsv}>↓ Exportar</button></div></header>
  {error&&<div className={s.notice}>{error}</div>}{loading?<div className={s.card}>Carregando leads...</div>:<>
  <section className={s.kpis}><article><span>Total de leads</span><strong>{leads.length}</strong><small>cadastros acumulados</small></article><article className={unread.length?s.hot:''}><span>Novos</span><strong>{unread.length}</strong><small>ainda não visualizados</small></article><article><span>Contato autorizado</span><strong>{leads.filter(l=>l.marketing_consent).length}</strong><small>{pct(leads.filter(l=>l.marketing_consent).length,leads.length)}% da base</small></article><article><span>Sem energia solar</span><strong>{leads.filter(l=>l.has_solar===false).length}</strong><small>oportunidade comercial</small></article></section>
  <section className={s.grid}><article className={s.card}><div className={s.cardHead}><div><span>DISTRIBUIÇÃO</span><h2>Leads por bairro</h2></div><small>Toque para filtrar</small></div><div className={s.rank}>{byNeighborhood.map(([name,count])=><button key={name} onClick={()=>focusGeo('neighborhood',name)} className={neighborhood===name?s.activeRank:''}><div><b>{name}</b><em>{count} lead{count!==1?'s':''}</em></div><strong>{pct(count,leads.length)}%</strong><i><u style={{width:`${pct(count,leads.length)}%`}}/></i></button>)}</div></article>
   <article className={s.card}><div className={s.cardHead}><div><span>REGIÕES</span><h2>Leads por cidade</h2></div><small>Visão geográfica</small></div><div className={s.cityGrid}>{byCity.map(([name,count])=><button key={name} onClick={()=>focusGeo('city',name)} className={city===name?s.activeCity:''}><span>{name}</span><strong>{count}</strong><small>{pct(count,leads.length)}% da base</small></button>)}</div></article></section>
  <section className={s.grid}><article className={s.card}><div className={s.cardHead}><div><span>AQUISIÇÃO</span><h2>De onde vieram os leads</h2></div><small>Toque para abrir os contatos</small></div><div className={s.rank}>{bySource.map(([name,count])=><button key={name} onClick={()=>focusSource(name)} className={source===name?s.activeRank:''}><div><b>{name}</b><em>{count} lead{count!==1?'s':''}</em></div><strong>{pct(count,leads.length)}%</strong><i><u style={{width:`${pct(count,leads.length)}%`}}/></i></button>)}</div></article>
   <article className={s.card}><div className={s.cardHead}><div><span>CAMPANHAS</span><h2>Leads por campanha</h2></div><small>UTM / QR / evento</small></div><div className={s.cityGrid}>{byCampaign.map(([name,count])=><button key={name} onClick={()=>{const hit=leads.find(l=>(l.source_campaign||l.utm_campaign||'Sem campanha')===name);focusSource(hit?sourceName(hit):'')}}><span>{name}</span><strong>{count}</strong><small>{pct(count,leads.length)}% da base</small></button>)}</div></article></section>
  {unread.length>0&&<section className={`${s.card} ${s.newBox}`}><div className={s.cardHead}><div><span>NOVIDADES</span><h2>Novos leads</h2></div><b>{unread.length} novo{unread.length!==1?'s':''}</b></div><div className={s.newLeads}>{unread.slice(0,6).map(l=><button key={l.id} onClick={()=>openLead(l)}><i>●</i><div><strong>{l.full_name}</strong><small>{sourceName(l)} • {l.neighborhood||'Bairro não informado'}</small></div><span>{fmt(l.created_at)}</span></button>)}</div></section>}
  <section className={s.filters}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar nome, WhatsApp, CPF, rua, origem..."/><select value={source} onChange={e=>setSource(e.target.value)}><option value="">Origem: todas</option>{bySource.map(([name])=><option value={name} key={name}>{name}</option>)}</select><select value={solar} onChange={e=>setSolar(e.target.value)}><option value="">Solar: todos</option><option value="no">Sem solar</option><option value="yes">Com solar</option></select><select value={marketing} onChange={e=>setMarketing(e.target.value)}><option value="">Contato: todos</option><option value="yes">Autorizado</option><option value="no">Não autorizado</option></select><button className={s.secondary} onClick={clear}>Limpar</button></section>
  {(city||neighborhood||source)&&<div className={s.activeFilter}>Exibindo <b>{source||neighborhood||city}</b> <button onClick={clear}>× remover filtro</button></div>}
  <section className={s.card} ref={listRef}><div className={s.cardHead}><div><span>CONTATOS</span><h2>{filtered.length} lead{filtered.length!==1?'s':''}</h2></div><small>Toque no cartão para abrir a ficha completa</small></div><div className={s.leadList}>{filtered.map(l=>{const isNew=!seen.includes(l.id);return <article key={l.id} onClick={()=>openLead(l)} className={isNew?s.unread:''}><div className={s.avatar}>{l.full_name?.charAt(0)?.toUpperCase()||'L'}</div><div className={s.leadMain}><div><h3>{l.full_name}{isNew&&<span>NOVO</span>}</h3><p>{l.neighborhood||'—'} • {l.city||'—'} • {sourceName(l)}</p></div><div className={s.tags}><span>{house(l.housing_type)}</span><span>{l.has_solar===false?'Sem solar':l.has_solar===true?'Com solar':'Solar não informado'}</span>{l.marketing_consent&&<span className={s.ok}>Contato autorizado</span>}</div></div><div className={s.contact}><a href={`https://wa.me/55${String(l.whatsapp||'').replace(/\D/g,'')}`} onClick={e=>e.stopPropagation()} target="_blank">WhatsApp</a><small>{fmt(l.created_at)}</small></div></article>})}{!filtered.length&&<div className={s.empty}>Nenhum lead encontrado.</div>}</div></section>
  </>}
  {selected&&<div className={s.drawerBack} onClick={()=>setSelected(null)}><aside className={s.drawer} onClick={e=>e.stopPropagation()}><header><div><span>FICHA DO LEAD</span><h2>{selected.full_name}</h2><p>{selected.neighborhood||'Bairro não informado'} • {selected.city||'Cidade não informada'}</p></div><button onClick={()=>setSelected(null)}>×</button></header><div className={s.profileTop}><div className={s.bigAvatar}>{selected.full_name?.charAt(0)?.toUpperCase()||'L'}</div><div><b>{selected.full_name}</b><small>Cadastrado em {fmt(selected.created_at)}</small></div></div><div className={s.detailGrid}><div><span>WhatsApp</span><b>{selected.whatsapp||'—'}</b></div><div><span>E-mail</span><b>{selected.email||'—'}</b></div><div><span>CPF</span><b>{selected.cpf||'—'}</b></div><div><span>Nascimento</span><b>{fmtDate(selected.birth_date)}</b></div><div><span>Moradia</span><b>{house(selected.housing_type)}</b></div><div><span>Energia solar</span><b>{selected.has_solar===true?'Possui':selected.has_solar===false?'Não possui':'Não informado'}</b></div><div className={s.full}><span>Endereço</span><b>{selected.street||'—'}</b><small>{selected.neighborhood||'—'} • {selected.city||'—'}</small></div><div className={s.full}><span>Origem do lead</span><b>{sourceName(selected)}</b><small>{sourceDetail(selected)}</small></div>{(selected.source_campaign||selected.utm_campaign)&&<div><span>Campanha</span><b>{selected.source_campaign||selected.utm_campaign}</b></div>}{selected.landing_path&&<div><span>Página de entrada</span><b>{selected.landing_path}</b></div>}<div className={s.full}><span>Contato comercial</span><b>{selected.marketing_consent?'Autorizado':'Não autorizado'}</b></div></div><footer style={{flexWrap:'wrap'}}><a href={`https://wa.me/55${String(selected.whatsapp||'').replace(/\D/g,'')}`} target="_blank">Abrir WhatsApp</a>{selected.email&&<a href={`mailto:${selected.email}`}>Enviar e-mail</a>}<button onClick={deleteLead} disabled={deleting} style={{width:'100%',marginTop:8,border:'1px solid #6f2830',background:'#36171b',color:'#ff9aa3',borderRadius:10,padding:'11px 10px',fontWeight:850,cursor:'pointer'}}>{deleting?'Excluindo...':'🗑 Excluir lead'}</button></footer></aside></div>}
 </main>
}
