'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {KEY,SB,money,session} from '../../../../lib/sb';
import s from './client360.module.css';

type Plan={id:string;name:string;monthly_price:number;event_limit?:number|null;photo_limit?:number|null;storage_gb?:number|null;platform_fee_percent?:number;features?:Record<string,boolean>};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const dateTime=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const typeLabel:any={church:'Igreja',event_company:'Empresa de eventos',photographer:'Fotógrafo',school:'Escola',company:'Empresa',other:'Outro'};
const accessLabel:any={active:'Ativo',trial:'Em teste',grace:'Tolerância',blocked:'Bloqueado',suspended:'Suspenso',trial_expired:'Teste encerrado',payment_overdue:'Inadimplente'};
const actionLabel:any={organization_created:'Cliente criado',organization_updated:'Dados da conta alterados',subscription_created:'Assinatura criada',subscription_updated:'Assinatura alterada',access_blocked:'Acesso bloqueado',access_unblocked:'Acesso liberado',payment_confirmed:'Pagamento confirmado'};

export default function Client360(){
 const params=useParams<{id:string}>(),id=String(params?.id||'');
 const [consoleData,setConsoleData]=useState<any>(null),[detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const [planId,setPlanId]=useState(''),[trialDays,setTrialDays]=useState('0'),[blockReason,setBlockReason]=useState('');
 async function auth(){const ss=await session();if(!ss?.access_token){location.href='/admin/login';throw new Error('Sessão expirada.')}return ss.access_token}
 async function call(body?:any){const token=await auth();const r=await fetch(`${SB}/functions/v1/developer-console`,{method:body?'POST':'GET',headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar cliente.');return d}
 async function getDetail(){const token=await auth();const r=await fetch(`${SB}/functions/v1/developer-client360?organization_id=${encodeURIComponent(id)}`,{headers:{apikey:KEY,Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar visão 360º.');return d}
 async function load(){setLoading(true);try{const [c,d]=await Promise.all([call(),getDetail()]);setConsoleData(c);setDetail(d);const o=(c.organizations||[]).find((x:any)=>x.id===id);if(!o)throw new Error('Cliente não encontrado.');setPlanId(o.plan_id||'');setBlockReason(o.access_block_reason||'')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[id]);
 const org=useMemo(()=>consoleData?.organizations?.find((x:any)=>x.id===id),[consoleData,id]);
 const plans:Plan[]=consoleData?.plans||[];const plan=plans.find(p=>p.id===org?.plan_id);const sub=detail?.subscription||org?.subscription||{};const fin=detail?.finance||org?.organization_finance_settings?.[0]||{};const access=org?.access_state||{};const stats=detail?.stats||{};const audit:any[]=detail?.audit||[];const events:any[]=detail?.events||[];
 async function action(body:any,ok:string){setSaving(true);setMsg('');try{await call(body);await load();setMsg(ok)}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}
 if(loading)return <main className={s.loading}><div/><b>Carregando ficha do cliente...</b></main>;
 if(!org)return <main className={s.loading}><b>{msg||'Cliente não encontrado.'}</b><a href="/developer/clientes">Voltar</a></main>;
 return <main className={s.page}>
  <header className={s.top}><div><a href="/developer/clientes">← Clientes</a><span>CLIENTE 360º</span><h1>{org.name}</h1><p>{typeLabel[org.organization_type]||org.organization_type} • /{org.slug}</p></div><div className={s.topActions}><a href={`/cadastro?org=${encodeURIComponent(org.slug)}`} target="_blank">Ver cadastro</a><a href="/developer">Console</a></div></header>
  {msg&&<div className={s.notice}>{msg}</div>}
  <section className={s.heroGrid}><article className={s.health}><div><span>STATUS DE ACESSO</span><strong className={access.allowed?s.good:s.bad}>{accessLabel[access.state]||access.state||org.status}</strong><small>{access.reason||'Acesso liberado para operação.'}</small></div><i>{access.allowed?'✓':'!'}</i></article><article><span>Plano atual</span><strong>{plan?.name||'Sem plano'}</strong><small>{plan?`${money(sub.amount??plan.monthly_price)}/mês`:'Defina uma assinatura'}</small></article><article><span>Próxima cobrança</span><strong>{date(sub.next_billing_at)}</strong><small>{sub.status||'Sem assinatura'}</small></article><article><span>Teste</span><strong>{date(org.trial_ends_at||sub.trial_ends_at)}</strong><small>{org.status==='trial'?'Período de avaliação':'Não está em teste'}</small></article></section>
  <section className={s.heroGrid}><article><span>Eventos</span><strong>{stats.events||0}</strong><small>cadastrados</small></article><article><span>Fotos</span><strong>{stats.photos||0}</strong><small>arquivos ativos</small></article><article><span>Visitantes / leads</span><strong>{stats.visitors||0}</strong><small>cadastros da organização</small></article><article><span>Usuários ativos</span><strong>{stats.members||0}</strong><small>membros com acesso</small></article></section>
  <div className={s.cols}><section className={s.card}><header><div><span>NEGÓCIO</span><h2>Resultado da conta</h2></div></header><div className={s.info}><div><span>Vendas pagas</span><b>{stats.paid_orders||0}</b></div><div><span>GMV</span><b>{money(stats.gmv||0)}</b></div><div><span>Receita da plataforma</span><b>{money(stats.platform_revenue||0)}</b></div><div><span>Gateway</span><b>{fin.payment_provider&&fin.payment_provider!=='none'?fin.payment_provider:'Não conectado'}</b></div><div><span>E-mail</span><b>{org.email||'—'}</b></div><div><span>Telefone</span><b>{org.phone||'—'}</b></div></div></section><section className={s.card}><header><div><span>ASSINATURA</span><h2>Plano e ciclo</h2></div></header><div className={s.info}><div><span>Status</span><b>{sub.status||org.status}</b></div><div><span>Mensalidade</span><b>{money(sub.amount??plan?.monthly_price??0)}</b></div><div><span>Período</span><b>{date(sub.current_period_start)} → {date(sub.current_period_end)}</b></div><div><span>Último pagamento</span><b>{dateTime(sub.last_payment_at)}</b></div><div><span>Em atraso desde</span><b>{date(sub.overdue_since)}</b></div><div><span>Tolerância até</span><b>{date(sub.grace_ends_at)}</b></div></div></section></div>
  <div className={s.cols}><section className={s.card}><header><div><span>EVENTOS</span><h2>Atividade recente</h2></div><small>{events.length} evento{events.length!==1?'s':''}</small></header><div className={s.info}>{events.slice(0,8).map((e:any)=><div key={e.id}><span>{e.status==='published'?'Publicado':'Rascunho'}</span><b>{e.title}</b><small>{date(e.event_date||e.created_at)}</small></div>)}{!events.length&&<div><span>Sem atividade</span><b>Nenhum evento cadastrado</b></div>}</div></section><section className={s.card}><header><div><span>HISTÓRICO</span><h2>Linha do tempo</h2></div><small>ações comerciais</small></header><div className={s.info}>{audit.slice(0,10).map((a:any)=><div key={a.id}><span>{dateTime(a.created_at)}</span><b>{a.summary||actionLabel[a.action]||a.action}</b><small>{a.actor_role||'sistema'}</small></div>)}{!audit.length&&<div><span>Histórico</span><b>As próximas alterações aparecerão aqui.</b></div>}</div></section></div>
  <section className={s.card}><header><div><span>CONTROLE DA CONTA</span><h2>Assinatura e acesso</h2></div><small>Alterações afetam imediatamente este cliente.</small></header><div className={s.controls}><label><span>Plano</span><select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.monthly_price)}/mês</option>)}</select></label><label><span>Dias de teste</span><input type="number" min="0" max="90" value={trialDays} onChange={e=>setTrialDays(e.target.value)}/></label><button disabled={saving||!planId} onClick={()=>action({action:'set_subscription',organization_id:org.id,plan_id:planId,trial_days:Number(trialDays)},'Plano e assinatura atualizados.')}>Salvar plano</button><button className={s.success} disabled={saving||!sub.id} onClick={()=>action({action:'mark_payment',organization_id:org.id},'Pagamento confirmado e acesso renovado por 30 dias.')}>Confirmar pagamento</button></div><div className={s.danger}><div><b>{access.allowed?'Bloquear acesso manualmente':'Acesso atualmente bloqueado'}</b><p>O bloqueio por teste vencido ou inadimplência continua automático.</p></div>{access.allowed?<><input value={blockReason} onChange={e=>setBlockReason(e.target.value)} placeholder="Motivo do bloqueio"/><button disabled={saving} onClick={()=>action({action:'set_access',organization_id:org.id,blocked:true,reason:blockReason||'Bloqueado pelo desenvolvedor'},'Acesso bloqueado.')}>Bloquear acesso</button></>:<button className={s.success} disabled={saving} onClick={()=>action({action:'set_access',organization_id:org.id,blocked:false},'Bloqueio manual removido.')}>Desbloquear</button>}</div></section>
  <section className={s.shortcuts}><a href="/developer/clientes">← Carteira de clientes</a><a href={`/cadastro?org=${encodeURIComponent(org.slug)}`} target="_blank">Cadastro público ↗</a></section>
 </main>
}