'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {KEY,SB,money,session} from '../../../../lib/sb';
import s from './client360.module.css';

type Plan={id:string;name:string;code:string;monthly_price:number;event_limit?:number|null;photo_limit?:number|null;storage_gb?:number|null;platform_fee_percent?:number;features?:Record<string,boolean>};
type Org={id:string;name:string;slug:string;organization_type:string;email?:string;phone?:string;status:string;plan_id?:string;trial_ends_at?:string;access_blocked_at?:string;access_block_reason?:string;grace_period_days?:number;created_at?:string;subscription?:any;access_state?:any;organization_finance_settings?:any[];branding?:any;registration_fields?:any[]};
const date=(v?:string|null)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const dateTime=(v?:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const typeLabel:any={church:'Igreja',event_company:'Empresa de eventos',photographer:'Fotógrafo',school:'Escola',company:'Empresa',other:'Outro'};
const accessLabel:any={active:'Ativo',trial:'Em teste',grace:'Tolerância',blocked:'Bloqueado',suspended:'Suspenso',trial_expired:'Teste encerrado',payment_overdue:'Inadimplente'};
export default function Client360(){
 const params=useParams<{id:string}>(),id=String(params?.id||'');
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const [planId,setPlanId]=useState(''),[trialDays,setTrialDays]=useState('0'),[blockReason,setBlockReason]=useState('');
 async function call(body?:any){const ss=await session();if(!ss?.access_token){location.href='/admin/login';throw new Error('Sessão expirada.')}const r=await fetch(`${SB}/functions/v1/developer-console`,{method:body?'POST':'GET',headers:{apikey:KEY,Authorization:`Bearer ${ss.access_token}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar cliente.');return d}
 async function load(){setLoading(true);try{const d=await call();setData(d);const o=(d.organizations||[]).find((x:any)=>x.id===id);if(!o)throw new Error('Cliente não encontrado.');setPlanId(o.plan_id||'');setBlockReason(o.access_block_reason||'')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[id]);
 const org:Org|undefined=useMemo(()=>data?.organizations?.find((x:any)=>x.id===id),[data,id]);
 const plans:Plan[]=data?.plans||[];const plan=plans.find(p=>p.id===org?.plan_id);const sub=org?.subscription||{};const fin=org?.organization_finance_settings?.[0]||{};const access=org?.access_state||{};
 async function action(body:any,ok:string){setSaving(true);setMsg('');try{await call(body);await load();setMsg(ok)}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}
 if(loading)return <main className={s.loading}><div/><b>Carregando ficha do cliente...</b></main>;
 if(!org)return <main className={s.loading}><b>{msg||'Cliente não encontrado.'}</b><a href="/developer">Voltar</a></main>;
 return <main className={s.page}>
  <header className={s.top}><div><a href="/developer">← Developer Workspace</a><span>CLIENTE 360º</span><h1>{org.name}</h1><p>{typeLabel[org.organization_type]||org.organization_type} • /{org.slug}</p></div><div className={s.topActions}><a href={`/cadastro?org=${encodeURIComponent(org.slug)}`} target="_blank">Ver cadastro</a><a href="/developer">Console</a></div></header>
  {msg&&<div className={s.notice}>{msg}</div>}
  <section className={s.heroGrid}><article className={s.health}><div><span>STATUS DE ACESSO</span><strong className={access.allowed?s.good:s.bad}>{accessLabel[access.state]||access.state||org.status}</strong><small>{access.reason||'Acesso liberado para operação.'}</small></div><i>{access.allowed?'✓':'!'}</i></article><article><span>Plano atual</span><strong>{plan?.name||'Sem plano'}</strong><small>{plan?`${money(plan.monthly_price)}/mês`:'Defina uma assinatura'}</small></article><article><span>Próxima cobrança</span><strong>{date(sub.next_billing_at)}</strong><small>{sub.status||'Sem assinatura'}</small></article><article><span>Teste</span><strong>{date(org.trial_ends_at||sub.trial_ends_at)}</strong><small>{org.status==='trial'?'Período de avaliação':'Não está em teste'}</small></article></section>
  <div className={s.cols}><section className={s.card}><header><div><span>CONTA</span><h2>Visão geral</h2></div></header><div className={s.info}><div><span>Organização</span><b>{org.name}</b></div><div><span>Segmento</span><b>{typeLabel[org.organization_type]||org.organization_type}</b></div><div><span>E-mail</span><b>{org.email||'—'}</b></div><div><span>Telefone</span><b>{org.phone||'—'}</b></div><div><span>Criado em</span><b>{date(org.created_at)}</b></div><div><span>Campos de cadastro</span><b>{org.registration_fields?.length||0}</b></div></div></section>
   <section className={s.card}><header><div><span>ASSINATURA</span><h2>Plano e ciclo</h2></div></header><div className={s.info}><div><span>Status</span><b>{sub.status||org.status}</b></div><div><span>Mensalidade</span><b>{money(sub.amount??plan?.monthly_price??0)}</b></div><div><span>Período atual</span><b>{date(sub.current_period_start)} → {date(sub.current_period_end)}</b></div><div><span>Último pagamento</span><b>{dateTime(sub.last_payment_at)}</b></div><div><span>Em atraso desde</span><b>{date(sub.overdue_since)}</b></div><div><span>Tolerância até</span><b>{date(sub.grace_ends_at)}</b></div></div></section>
  </div>
  <div className={s.cols}><section className={s.card}><header><div><span>LIMITES</span><h2>Recursos do plano</h2></div></header><div className={s.limits}><div><b>{plan?.event_limit??'∞'}</b><span>Eventos</span></div><div><b>{plan?.photo_limit??'∞'}</b><span>Fotos</span></div><div><b>{plan?.storage_gb??'∞'}{plan?.storage_gb?' GB':''}</b><span>Armazenamento</span></div><div><b>{plan?.platform_fee_percent??0}%</b><span>Taxa plataforma</span></div></div>{plan?.features&&<div className={s.features}>{Object.entries(plan.features).filter(([,v])=>v).map(([k])=><span key={k}>✓ {k.replaceAll('_',' ')}</span>)}</div>}</section>
   <section className={s.card}><header><div><span>FINANCEIRO</span><h2>Recebimentos</h2></div></header><div className={s.info}><div><span>Gateway</span><b>{fin.payment_provider&&fin.payment_provider!=='none'?fin.payment_provider:'Não conectado'}</b></div><div><span>Status</span><b>{fin.provider_status||'Não configurado'}</b></div><div><span>Pix</span><b>{fin.pix_enabled?'Ativo':'Inativo'}</b></div><div><span>Cartão</span><b>{fin.card_enabled?'Ativo':'Inativo'}</b></div><div><span>Boleto</span><b>{fin.boleto_enabled?'Ativo':'Inativo'}</b></div><div><span>Split</span><b>{fin.platform_fee_percent||0}%</b></div></div></section>
  </div>
  <section className={s.card}><header><div><span>CONTROLE DA CONTA</span><h2>Assinatura e acesso</h2></div><small>Alterações feitas aqui afetam este cliente.</small></header><div className={s.controls}><label><span>Plano</span><select value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Selecione</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.monthly_price)}/mês</option>)}</select></label><label><span>Dias de teste</span><input type="number" min="0" max="90" value={trialDays} onChange={e=>setTrialDays(e.target.value)}/></label><button disabled={saving||!planId} onClick={()=>action({action:'set_subscription',organization_id:org.id,plan_id:planId,trial_days:Number(trialDays)},'Plano e assinatura atualizados.')}>Salvar plano</button><button className={s.success} disabled={saving||!sub.id} onClick={()=>action({action:'mark_payment',organization_id:org.id},'Pagamento confirmado e acesso renovado por 30 dias.')}>Confirmar pagamento</button></div><div className={s.danger}><div><b>{access.allowed?'Bloquear acesso manualmente':'Acesso atualmente bloqueado'}</b><p>Use somente para suspensão administrativa. O bloqueio por teste vencido ou inadimplência é calculado automaticamente.</p></div>{access.allowed?<><input value={blockReason} onChange={e=>setBlockReason(e.target.value)} placeholder="Motivo do bloqueio"/><button disabled={saving} onClick={()=>action({action:'set_access',organization_id:org.id,blocked:true,reason:blockReason||'Bloqueado pelo desenvolvedor'},'Acesso bloqueado.')}>Bloquear acesso</button></>:<button className={s.success} disabled={saving} onClick={()=>action({action:'set_access',organization_id:org.id,blocked:false},'Bloqueio manual removido.')}>Desbloquear</button>}</div></section>
  <section className={s.shortcuts}><a href="/developer">← Voltar ao Console</a><a href={`/cadastro?org=${encodeURIComponent(org.slug)}`} target="_blank">Cadastro público ↗</a></section>
 </main>
}