'use client';
import {FormEvent,useEffect,useState} from 'react';
import {KEY,SB,money,session,slugify} from '../../../lib/sb';
import s from './onboarding.module.css';

export default function Onboarding(){
 const [plans,setPlans]=useState<any[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[done,setDone]=useState<any>(null);
 const [f,setF]=useState<any>({name:'',slug:'',organization_type:'church',document_number:'',email:'',phone:'',plan_id:'',trial_days:'7',admin_name:'',admin_email:'',admin_password:'',notes:''});
 useEffect(()=>{(async()=>{try{const ss=await session();if(!ss?.access_token){location.href='/admin/login';return}const r=await fetch(`${SB}/functions/v1/developer-console`,{headers:{apikey:KEY,Authorization:`Bearer ${ss.access_token}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar planos.');setPlans(d.plans||[]);if(d.plans?.[0])setF((x:any)=>({...x,plan_id:d.plans[0].id}))}catch(e:any){setMsg(e.message)}finally{setLoading(false)}})()},[]);
 function set(k:string,v:any){setF((x:any)=>({...x,[k]:v,...(k==='name'&&!x.slug?{slug:slugify(v)}:{})}))}
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');setDone(null);try{const ss=await session();if(!ss?.access_token)throw new Error('Sessão expirada.');const r=await fetch(`${SB}/functions/v1/developer-onboarding`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${ss.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao criar cliente.');setDone(d);setMsg('Onboarding concluído com sucesso.')}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}
 if(loading)return <main className={s.loading}>Carregando onboarding...</main>;
 const plan=plans.find(p=>p.id===f.plan_id);
 return <main className={s.page}>
  <header><div><a href="/developer/clientes">← Clientes</a><span>ONBOARDING COMERCIAL</span><h1>Novo cliente</h1><p>Crie a organização, assinatura e primeiro administrador em uma única operação.</p></div><a className={s.back} href="/developer">Console</a></header>
  {msg&&<div className={s.notice}>{msg}</div>}
  {done?<section className={s.success}><div className={s.check}>✓</div><h2>{done.organization.name} está pronto</h2><p>A organização, plano e administrador foram criados.</p><div className={s.summary}><div><span>Plano</span><b>{done.plan.name}</b></div><div><span>Mensalidade</span><b>{money(done.plan.monthly_price)}</b></div><div><span>Administrador</span><b>{done.administrator.full_name}</b></div><div><span>Login</span><b>{done.administrator.email}</b></div><div><span>Status</span><b>{done.organization.status==='trial'?'Em teste':'Ativo'}</b></div><div><span>Teste até</span><b>{done.organization.trial_ends_at?new Date(done.organization.trial_ends_at).toLocaleDateString('pt-BR'):'Sem teste'}</b></div></div><div className={s.actions}><a href={`/developer/clientes/${done.organization.id}`}>Abrir ficha 360º</a><a href="/developer/onboarding" onClick={()=>{setDone(null);setMsg('');setF({name:'',slug:'',organization_type:'church',document_number:'',email:'',phone:'',plan_id:plans[0]?.id||'',trial_days:'7',admin_name:'',admin_email:'',admin_password:'',notes:''})}}>Criar outro cliente</a></div></section>:
  <form onSubmit={submit} className={s.form}>
   <section className={s.card}><div className={s.head}><span>1</span><div><h2>Organização</h2><p>Dados principais do novo cliente.</p></div></div><div className={s.grid}><label><span>Nome da organização *</span><input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Ex.: Igreja Central"/></label><label><span>Slug *</span><input required value={f.slug} onChange={e=>set('slug',slugify(e.target.value))} placeholder="igreja-central"/></label><label><span>Segmento</span><select value={f.organization_type} onChange={e=>set('organization_type',e.target.value)}><option value="church">Igreja</option><option value="event_company">Empresa de eventos</option><option value="photographer">Fotógrafo</option><option value="school">Escola</option><option value="company">Empresa</option><option value="other">Outro</option></select></label><label><span>CPF/CNPJ</span><input value={f.document_number} onChange={e=>set('document_number',e.target.value)} placeholder="Necessário para cobrança Asaas"/></label><label><span>E-mail comercial</span><input type="email" value={f.email} onChange={e=>set('email',e.target.value)}/></label><label><span>Telefone</span><input value={f.phone} onChange={e=>set('phone',e.target.value)}/></label></div></section>
   <section className={s.card}><div className={s.head}><span>2</span><div><h2>Plano e teste</h2><p>Defina como a conta começa.</p></div></div><div className={s.grid}><label className={s.wide}><span>Plano *</span><select required value={f.plan_id} onChange={e=>set('plan_id',e.target.value)}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.monthly_price)}/mês</option>)}</select></label><label><span>Dias de teste</span><input type="number" min="0" max="90" value={f.trial_days} onChange={e=>set('trial_days',e.target.value)}/></label><div className={s.planBox}><span>Resumo</span><b>{plan?.name||'Sem plano'}</b><strong>{money(plan?.monthly_price||0)}/mês</strong><small>{Number(f.trial_days)>0?`${f.trial_days} dias grátis antes da cobrança`:'Ativação imediata'}</small></div></div></section>
   <section className={s.card}><div className={s.head}><span>3</span><div><h2>Primeiro administrador</h2><p>Esse usuário receberá o controle da organização.</p></div></div><div className={s.grid}><label><span>Nome completo *</span><input required value={f.admin_name} onChange={e=>set('admin_name',e.target.value)}/></label><label><span>E-mail de login *</span><input required type="email" value={f.admin_email} onChange={e=>set('admin_email',e.target.value)}/></label><label className={s.wide}><span>Senha temporária *</span><input required minLength={8} type="password" value={f.admin_password} onChange={e=>set('admin_password',e.target.value)} placeholder="Mínimo 8 caracteres"/><small>O administrador poderá trocar depois pelo perfil.</small></label></div></section>
   <section className={s.card}><div className={s.head}><span>4</span><div><h2>Finalização</h2><p>Revise antes de ativar.</p></div></div><label className={s.notes}><span>Observações internas</span><textarea rows={4} value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder="Informações comerciais, negociação, origem do cliente..."/></label><div className={s.review}><div><b>{f.name||'Nova organização'}</b><small>/{f.slug||'slug'}</small></div><div><span>{plan?.name||'Plano'}</span><strong>{money(plan?.monthly_price||0)}/mês</strong></div><div><span>Administrador</span><strong>{f.admin_email||'—'}</strong></div></div><button className={s.submit} disabled={saving}>{saving?'Criando organização...':'Criar cliente e ativar onboarding'}</button></section>
  </form>}
 </main>;
}