'use client';
import {FormEvent,useEffect,useState} from 'react';
import {KEY,SB} from '../../../lib/sb';
import s from './first-access.module.css';

export default function FirstAccess(){
 const [token,setToken]=useState(''),[refresh,setRefresh]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{try{const hash=new URLSearchParams(location.hash.replace(/^#/,''));const access=hash.get('access_token')||'',ref=hash.get('refresh_token')||'';if(!access)throw new Error('Este link é inválido ou expirou. Solicite um novo link de acesso.');setToken(access);setRefresh(ref);const r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${access}`}});const d=await r.json();if(!r.ok)throw new Error('Não foi possível validar este acesso.');setEmail(d.email||'')}catch(e:any){setMsg(e.message)}finally{setLoading(false)}})()},[]);
 async function destination(access:string){const dev=await fetch(`${SB}/functions/v1/developer-console`,{headers:{apikey:KEY,Authorization:`Bearer ${access}`}});if(dev.ok)return '/developer';const adm=await fetch(`${SB}/functions/v1/admin-access`,{headers:{apikey:KEY,Authorization:`Bearer ${access}`}});if(adm.ok)return '/admin';return '/acesso'}
 async function submit(e:FormEvent){e.preventDefault();if(password.length<8){setMsg('A senha precisa ter pelo menos 8 caracteres.');return}if(password!==confirm){setMsg('As senhas não coincidem.');return}setSaving(true);setMsg('');try{const r=await fetch(`${SB}/auth/v1/user`,{method:'PUT',headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d?.msg||d?.message||'Não foi possível definir a senha.');await fetch(`${SB}/functions/v1/first-access-complete`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'}).catch(()=>null);const expiresAt=Math.floor(Date.now()/1000)+3600;localStorage.setItem('semeando_admin_session',JSON.stringify({access_token:token,refresh_token:refresh,expires_at:expiresAt,user:d}));location.hash='';location.href=await destination(token)}catch(e:any){setMsg(e.message)}finally{setSaving(false)}}
 if(loading)return <main className={s.page}><section className={s.card}><div className={s.spinner}/><b>Validando acesso...</b></section></main>;
 if(!token)return <main className={s.page}><section className={s.card}><div className={s.brand}>SM</div><h1>Link indisponível</h1><p>{msg}</p><a href="/acesso">Ir para o acesso</a></section></main>;
 return <main className={s.page}><section className={s.card}><div className={s.brand}>SM</div><span>PRIMEIRO ACESSO</span><h1>Crie sua senha</h1><p>Defina sua senha pessoal. Depois disso, o sistema abrirá somente o painel correspondente à sua permissão.</p>{email&&<div className={s.email}>{email}</div>}{msg&&<div className={s.notice}>{msg}</div>}<form onSubmit={submit}><label><span>Nova senha</span><input autoFocus required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/></label><label><span>Confirmar senha</span><input required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repita a senha"/></label><small>Use uma senha exclusiva, com letras, números e, de preferência, um símbolo.</small><button disabled={saving}>{saving?'Salvando...':'Criar senha e entrar'}</button></form><a className={s.login} href="/acesso">Já defini minha senha</a></section></main>;
}
