'use client';
import {useEffect,useMemo,useState} from 'react';
import {SB,KEY,session} from '../../../../lib/sb';
type Backend={id:string;code:string;provider:string;label:string;bucket_name:string;endpoint?:string|null;active:boolean;is_default:boolean;max_file_bytes?:number|null;capacity_bytes?:number|null;reserve_percent?:number;readiness_status:string;readiness_message?:string|null;config?:any};type Space={event_id:string;organization_id:string;backend_id:string;object_prefix:string;bytes_used:number;object_count:number;expected_files?:number|null;expected_bytes?:number|null;launch_critical:boolean;readiness_status:string;readiness_message?:string|null;events?:{title:string;slug:string}|null};
const fmt=(n:any)=>{const x=Number(n||0);return x>=1073741824?`${(x/1073741824).toFixed(2)} GB`:x>=1048576?`${(x/1048576).toFixed(1)} MB`:`${Math.round(x/1024)} KB`};
export default function StorageIntegration(){const[backends,setBackends]=useState<Backend[]>([]),[spaces,setSpaces]=useState<Space[]>([]),[secrets,setSecrets]=useState<any>({}),[account,setAccount]=useState(''),[bucket,setBucket]=useState(''),[busy,setBusy]=useState(''),[msg,setMsg]=useState('');
 async function token(){const s=await session();if(!s?.access_token){location.href='/acesso';throw Error('Sessão expirada.')}return s.access_token}
 async function api(body?:any){const t=await token(),r=await fetch(`${SB}/functions/v1/developer-storage`,{method:body?'POST':'GET',headers:{apikey:KEY,Authorization:`Bearer ${t}`,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Falha na integração de storage.');return d}
 async function load(){try{const d=await api();setBackends(d.backends||[]);setSpaces(d.spaces||[]);setSecrets(d.secrets||{});const r=(d.backends||[]).find((x:Backend)=>x.code==='r2-originals');if(r){setBucket(r.bucket_name==='pending-r2-bucket'?'':r.bucket_name||'');setAccount(r.config?.account_id||'')}}catch(e:any){setMsg(e.message)}}useEffect(()=>{load()},[]);
 const supa=useMemo(()=>backends.find(x=>x.code==='supabase-originals'),[backends]),r2=useMemo(()=>backends.find(x=>x.code==='r2-originals'),[backends]);
 async function act(action:string,extra:any={}){setBusy(action+(extra.event_id||''));setMsg('');try{const d=await api({action,...extra});setMsg(action==='configure_r2'?'Configuração salva. Agora execute o teste de conexão.':action==='test_r2'?'R2 conectado e validado com sucesso.':action==='set_default'?'R2 definido como padrão para novos eventos.':'Evento preparado para usar R2.');await load();return d}catch(e:any){setMsg(e.message)}finally{setBusy('')}}
 return <main className="page"><header><div><a href="/developer">← Developer Workspace</a><span>INFRAESTRUTURA • STORAGE</span><h1>Armazenamento da plataforma</h1><p>Separe banco e autenticação do volume pesado de fotos. Nenhum evento crítico é liberado para um backend sem capacidade e teste.</p></div></header>{msg&&<div className="notice">{msg}</div>}
 <section className="grid"><article><div className="top"><div><span>ATUAL</span><h2>{supa?.label||'Supabase Originals'}</h2></div><b className="warn">{supa?.readiness_status||'warning'}</b></div><div className="stats"><div><small>Provider</small><strong>SUPABASE</strong></div><div><small>Capacidade registrada</small><strong>{supa?.capacity_bytes?fmt(supa.capacity_bytes):'—'}</strong></div><div><small>Máx. arquivo</small><strong>{supa?.max_file_bytes?fmt(supa.max_file_bytes):'—'}</strong></div><div><small>Padrão</small><strong>{supa?.is_default?'Sim':'Não'}</strong></div></div><p>{supa?.readiness_message}</p></article>
 <article className={r2?.active?'r2 ready':'r2'}><div className="top"><div><span>RECOMENDADO PARA PRODUÇÃO</span><h2>Cloudflare R2</h2></div><b className={r2?.active?'ok':'off'}>{r2?.active?'VALIDADO':'AGUARDANDO'}</b></div><div className="stats"><div><small>Access Key secret</small><strong>{secrets.r2_access_key?'✓ Presente':'✕ Ausente'}</strong></div><div><small>Secret Key</small><strong>{secrets.r2_secret_key?'✓ Presente':'✕ Ausente'}</strong></div><div><small>Bucket</small><strong>{r2?.bucket_name&&r2.bucket_name!=='pending-r2-bucket'?r2.bucket_name:'Não configurado'}</strong></div><div><small>Padrão</small><strong>{r2?.is_default?'Sim':'Não'}</strong></div></div><p>{r2?.readiness_message||'Configure o R2 antes do evento principal.'}</p></article></section>
 <section className="setup"><div><span>CONFIGURAÇÃO NÃO SENSÍVEL</span><h2>Conectar Cloudflare R2</h2><p>O Account ID e o nome do bucket podem ficar aqui. As chaves secretas permanecem somente nos Secrets do Supabase.</p></div><div className="fields"><label><span>Cloudflare Account ID</span><input value={account} onChange={e=>setAccount(e.target.value)} placeholder="Account ID"/></label><label><span>Nome do bucket R2</span><input value={bucket} onChange={e=>setBucket(e.target.value)} placeholder="Ex.: semeando-memorias-originals"/></label></div><div className="actions"><button disabled={!account||!bucket||!!busy} onClick={()=>act('configure_r2',{account_id:account,bucket_name:bucket})}>Salvar configuração</button><button className="test" disabled={!bucket||!!busy} onClick={()=>act('test_r2')}>{busy==='test_r2'?'Testando...':'Testar escrita no R2'}</button><button className="default" disabled={!r2?.active||!!busy} onClick={()=>act('set_default')}>Tornar padrão para novos eventos</button></div><div className="secretHelp"><b>Secrets necessários no Supabase</b><code>R2_ACCESS_KEY_ID</code><code>R2_SECRET_ACCESS_KEY</code><small>Não cole essas chaves no GitHub nem em campos públicos.</small></div></section>
 <section className="events"><div className="sectionHead"><div><span>EVENTOS E BACKENDS</span><h2>Onde cada álbum guarda os originais</h2></div><b>{spaces.length} espaços</b></div><div className="list">{spaces.map(s=>{const b=backends.find(x=>x.id===s.backend_id);return <article key={s.event_id}><div><small>{s.launch_critical?'⚠ EVENTO CRÍTICO':'Evento'}</small><h3>{s.events?.title||s.event_id}</h3><p>{s.object_prefix}</p></div><div className="eventStats"><span>{b?.provider?.toUpperCase()||'—'}</span><span>{s.object_count||0} originais</span><span>{fmt(s.bytes_used||0)}</span>{s.expected_files? <span>Previsto: {s.expected_files.toLocaleString('pt-BR')} • {fmt(s.expected_bytes||0)}</span>:null}</div><button disabled={!r2?.active||b?.provider==='r2'||Number(s.object_count||0)>0||!!busy} onClick={()=>act('assign_event',{event_id:s.event_id})}>{b?.provider==='r2'?'R2 ativo':Number(s.object_count||0)>0?'Requer migração':'Usar R2 neste evento'}</button></article>})}</div></section>
 <section className="launch"><b>Regra para o evento principal</b><p>Não iniciar o lote de milhares de fotos enquanto o R2 não estiver como <strong>VALIDADO</strong>, o evento não estiver apontando para R2 e o teste de carga não tiver sido concluído.</p><a href="/developer/saude">Ver saúde da plataforma →</a></section>
 <style jsx>{`.page{max-width:1180px;margin:auto;padding:90px 18px 60px;color:#f4f6f8}header a{color:#9ca4ae;text-decoration:none;font-weight:850}header span,.top span,.setup>div>span,.sectionHead span{display:block;color:#ff9250;font-size:10px;letter-spacing:.15em;font-weight:950;margin-top:10px}h1{font-size:48px;margin:7px 0}header p,.grid p,.setup p,.launch p{color:#9da5af;line-height:1.55}.notice{margin:14px 0;background:#26180f;border:1px solid #623a20;border-radius:13px;padding:12px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.grid article,.setup,.events,.launch{background:#12161b;border:1px solid #303740;border-radius:20px;padding:18px}.grid article.r2{border-color:#4d3525}.grid article.ready{border-color:#276047}.top,.sectionHead{display:flex;justify-content:space-between;align-items:start;gap:12px}.top b{font-size:9px;padding:7px 9px;border-radius:999px}.warn{background:#362616;color:#ffc182}.off{background:#32201a;color:#ff9f87}.ok{background:#153629;color:#7be0ac}.stats{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:13px 0}.stats div{display:grid;background:#0c1014;border:1px solid #293039;padding:10px;border-radius:11px}.stats small{color:#838c97}.stats strong{font-size:12px;margin-top:3px}.setup,.events,.launch{margin-top:14px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:9px}.fields label{display:grid;gap:5px}.fields label span{font-size:9px;color:#a2a9b2}.fields input{background:#0b0e12;color:#fff;border:1px solid #353c45;border-radius:10px;padding:11px}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.actions button,.events button{border:0;border-radius:10px;padding:10px 12px;font-weight:900;background:#ff7417;color:#111}.actions .test{background:#28523e;color:#c8f5dd}.actions .default{background:#282f37;color:#fff}.actions button:disabled,.events button:disabled{opacity:.42}.secretHelp{display:flex;gap:7px;align-items:center;flex-wrap:wrap;border-top:1px solid #2b3138;padding-top:12px}.secretHelp b{font-size:11px}.secretHelp code{background:#090c0f;border:1px solid #30363e;padding:7px 9px;border-radius:8px;color:#ffae79}.secretHelp small{color:#808893}.list{display:grid;gap:7px;margin-top:12px}.list article{display:grid;grid-template-columns:1.4fr 1fr auto;gap:12px;align-items:center;background:#0c1014;border:1px solid #293039;border-radius:13px;padding:11px}.list h3{margin:3px 0}.list p{margin:0;color:#727b86;font-size:9px;overflow:hidden;text-overflow:ellipsis}.list small{color:#ff9858;font-size:8px;font-weight:900}.eventStats{display:flex;gap:5px;flex-wrap:wrap}.eventStats span{font-size:8px;background:#1d232a;color:#a9b0ba;border-radius:999px;padding:6px 8px}.events button{font-size:9px}.launch a{color:#ff9250;text-decoration:none;font-weight:900}@media(max-width:760px){.page{padding:82px 11px 45px}h1{font-size:36px}.grid,.fields{grid-template-columns:1fr}.list article{grid-template-columns:1fr}.events button{width:100%}}`}</style></main>;
}
